import type {ReproductionPlan} from '../../packages/findings/reproduction.ts';
import type {Pool,PoolClient} from 'pg';
import {canonical,digest} from '../../packages/review/engine.ts';
import type {Snapshot} from '../../packages/review/types.ts';
import type {ReviewSubject} from '../../packages/reviewers/context.ts';
import {validateFindingHistoryLink,type FindingHistoryRecord} from '../../packages/findings/history.ts';
import {reproductionWorkflowId} from '../../packages/findings/workflow-identity.ts';
import {appliedReproductionConfig} from '../../packages/runtime/reproduction-catalog.ts';
import {ReproductionPermissionDenied,type ReproductionAuthorityStore} from '../../packages/storage/reproduction-authority.ts';
import {ReproductionEvalInputLimit,type ReproductionEvalStore} from '../../packages/storage/reproduction-evals.ts';
import type {FindingReproductionStore} from '../../packages/storage/finding-reproduction.ts';
import type {FindingHistoryStore} from '../../packages/storage/finding-history.ts';
import type {ReproductionNonExecutionStore} from '../../packages/storage/reproduction-non-execution.ts';
import type {EvalStore} from '../../packages/storage/evals.ts';
import type {ReproductionDispatchStore,ReproductionDispatchClaim,DispatchSettlementReader} from '../../packages/storage/reproduction-dispatch.ts';
import type {AdmittedReproductionActivities,ReproductionStopCause} from './admitted-reproduction-workflows.ts';
import type {ReproductionRuntimeObservation} from './reproduction-consumer-recovery.ts';
interface Dependencies {pool:Pool;scope:{organizationId:string;repository:string};authority:ReproductionAuthorityStore;staging:ReproductionEvalStore;reproduction:FindingReproductionStore;history:FindingHistoryStore;proofs:ReproductionNonExecutionStore;evals:EvalStore;dispatch:ReproductionDispatchStore;snapshots:(subject:ReviewSubject,side:'base'|'head')=>Promise<Snapshot>;evalTaskQueue:string;prepareStaging?:(plan:ReproductionPlan,base:Snapshot,head:Snapshot)=>Promise<ReproductionEvalStore>}
const fail=():never=>{throw Error('reproduction-runtime-conflict');};
/** Trusted activity boundary; inputs are retained IDs only, never approval documents or commands. */
export function createReproductionConsumerRuntime(d:Dependencies){
 const scope=structuredClone(d.scope),quiescent=new Map<string,{token:string;identity:string}>();
 const keys=(id:string)=>[scope.organizationId,scope.repository,id];
 const history=async(c:Pool|PoolClient,id:string,subject:ReviewSubject)=>{const rows=(await c.query('SELECT version,operation_id,digest,event FROM agentci_finding_events WHERE organization_id=$1 AND repository=$2 AND finding_id=$3 ORDER BY version LIMIT 10001',keys(id))).rows;if(!rows.length||rows.length>10000||Buffer.byteLength(canonical(rows))>32*1024*1024)fail();const out:FindingHistoryRecord[]=[];for(const row of rows){if(Number(row.version)!==out.length+1||row.operation_id!==row.event?.operationId)fail();out.push(await validateFindingHistoryLink({digest:row.digest,event:row.event},subject,out.at(-1)));}return out;};
 const context=async(operationId:string,token?:string)=>{const entry=await d.dispatch.get(operationId);if(!entry) return fail();const plan=await d.reproduction.get(entry.planId);if(!plan||canonical(plan.finding.subject.organizationId)!==canonical(scope.organizationId)||plan.finding.subject.repository!==scope.repository)fail();if(token===undefined){if(entry.binding||entry.attempt||entry.runId)fail();}else{let after:string|undefined,found=false;for(;;){const page=await d.dispatch.attempts(operationId,after);if(page.some(a=>a.token===token)){found=true;break;}if(page.length<100)break;after=page.at(-1)!.token;}if(!found||!entry.binding||entry.binding.planDigest!==digest(canonical(plan))||entry.binding.evalTaskQueue!==d.evalTaskQueue||entry.runId&&entry.attempt?.token!==token)fail();}return {entry,plan:plan!};};
 const locks=async(c:PoolClient,plan:NonNullable<Awaited<ReturnType<FindingReproductionStore['get']>>>)=>{await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[canonical([...keys(plan.id),'eval-stage'])]);await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[canonical(keys(plan.finding.id))]);};
 const cancelled=async(c:Pool|PoolClient,operationId:string,planId:string)=>!!(await c.query('SELECT 1 FROM agentci_reproduction_cancellations WHERE organization_id=$1 AND repository=$2 AND id=$3 UNION ALL SELECT 1 FROM agentci_reproduction_dispatch_state WHERE organization_id=$1 AND repository=$2 AND operation_id=$4 AND cancellation_at IS NOT NULL',[...keys(planId),operationId])).rowCount;
 const inspect=async(operationId:string,token?:string)=>{const {plan}=await context(operationId,token),retained=await d.staging.recoveryPlan(plan.id);return {jobId:retained?.id??null,evalTaskQueue:d.evalTaskQueue,unitIds:(retained?.unitIds??[]).map(unitId=>({unitId,unitWorkflowId:reproductionWorkflowId(scope,plan.id,'unit',unitId),cleanupWorkflowId:reproductionWorkflowId(scope,plan.id,'cleanup',unitId)}))};};
 const queued=async(c:Pool|PoolClient,plan:NonNullable<Awaited<ReturnType<FindingReproductionStore['get']>>>)=>canonical((await history(c,plan.finding.id,plan.finding.subject)).at(-1)!.event.finding)===canonical(plan.finding);
 const proofHistory=async(plan:NonNullable<Awaited<ReturnType<FindingReproductionStore['get']>>>,inputLimit?:ReproductionEvalInputLimit)=>{if(!await queued(d.pool,plan))return;const proof=inputLimit?await d.proofs.inputLimit(plan.id,inputLimit):await d.proofs.cancelled(plan.id);try{await d.history.unavailable(plan.finding.id,plan.finding.subject,{type:'unavailable',proofId:proof.id},plan.finding.version,proof.id);}catch(error){const latest=(await d.history.get(plan.finding.id,plan.finding.subject)).at(-1)!;if(!['false-positive','resolve'].includes(latest.event.action.type))throw error;}};
 const stop=async(operationId:string,token:string|undefined,cause:ReproductionStopCause)=>{const {plan,entry}=await context(operationId,token);quiescent.delete(operationId);
  // Durable cancellation precedes config/permission lookups; cleanup never needs a live approval.
  await d.reproduction.cancel(plan.id);
  if(!entry.cancellation){let retained:'user'|'revoked'|'expired'|'permission-denied'|'superseded'|'unavailable'=cause==='unavailable'?'unavailable':cause==='superseded'?'superseded':cause==='cancelled'?'user':'permission-denied';if(cause==='denied'){if((await d.pool.query('SELECT 1 FROM agentci_reproduction_revocations WHERE organization_id=$1 AND repository=$2 AND plan_id=$3',keys(plan.id))).rowCount)retained='revoked';else{const config=await appliedReproductionConfig(d.pool,scope);const ref=config.config.approvals.find(a=>a.planId===plan.id);if(ref&&(await d.pool.query('SELECT clock_timestamp()>=$1::timestamptz AS expired',[ref.expiresAt])).rows[0].expired)retained='expired';}}await d.dispatch.requestCancellation(operationId,retained);}
  const result=await inspect(operationId,token);if(!result.jobId)await proofHistory(plan);return {unitIds:result.unitIds,evalTaskQueue:result.evalTaskQueue,staged:result.jobId!==null};};
 const locallyAllowed=async(planId:string,current:Awaited<ReturnType<typeof appliedReproductionConfig>>)=>{const reference=current.config.approvals.find(a=>a.planId===planId);return !!reference?.enabled&&!(await d.pool.query('SELECT 1 FROM agentci_reproduction_revocations WHERE organization_id=$1 AND repository=$2 AND plan_id=$3',keys(planId))).rowCount&&!!(await d.pool.query('SELECT clock_timestamp()<$1::timestamptz AS live',[reference.expiresAt])).rows[0].live;};
 const activities:AdmittedReproductionActivities={
  inspectAdmittedReproduction:inspect,
  stageAdmittedReproduction:async(operationId,token)=>{const {plan,entry}=await context(operationId,token);if(entry.settlement)return {kind:'not-started'};if(await cancelled(d.pool,operationId,plan.id)){await stop(operationId,token,'cancelled');return {kind:'not-started'};}if(!await locallyAllowed(plan.id,await appliedReproductionConfig(d.pool,scope))){await stop(operationId,token,'denied');return {kind:'not-started'};}const [base,head]=await Promise.all([d.snapshots(plan.finding.subject,'base'),d.snapshots(plan.finding.subject,'head')]);const staging=d.prepareStaging?await d.prepareStaging(plan,base,head):d.staging;let prepared;try{prepared=await staging.prepare(plan.id,base,head);}catch(error){if(error instanceof ReproductionEvalInputLimit){await proofHistory(plan,error);return {kind:'not-started'};}throw error;}
   const current=await appliedReproductionConfig(d.pool,scope);try{await d.authority.withApproval(current.identity,plan.id,async c=>{await locks(c,plan);if(await cancelled(c,operationId,plan.id)||!await queued(c,plan))fail();await staging.stagePrepared(c,prepared);});}catch(error){if(!(error instanceof ReproductionPermissionDenied)&&await locallyAllowed(plan.id,await appliedReproductionConfig(d.pool,scope)))throw error;await stop(operationId,token,'denied');return {kind:'not-started'};}const staged=await staging.committed(prepared);return {kind:'staged',...staged,unitWorkflowId:reproductionWorkflowId(scope,plan.id,'unit',staged.unitId),cleanupWorkflowId:reproductionWorkflowId(scope,plan.id,'cleanup',staged.unitId),evalTaskQueue:d.evalTaskQueue};},
  checkAdmittedReproduction:async(operationId,token)=>{const {plan,entry}=await context(operationId,token);if(entry.settlement||await cancelled(d.pool,operationId,plan.id))return {allowed:false};const current=await appliedReproductionConfig(d.pool,scope);if(!await locallyAllowed(plan.id,current))return {allowed:false};try{return await d.authority.withApproval(current.identity,plan.id,async c=>{await locks(c,plan);return {allowed:!await cancelled(c,operationId,plan.id)&&await queued(c,plan)};});}catch(error){if(error instanceof ReproductionPermissionDenied)return {allowed:false};throw error;}},
  cancelAdmittedReproduction:stop,
  finalizeAdmittedReproduction:async(operationId,token)=>{const {plan}=await context(operationId,token);const staged=await d.staging.recoveryPlan(plan.id);if(!staged){if(await cancelled(d.pool,operationId,plan.id))await proofHistory(plan);return;}try{await d.reproduction.finalize(plan.id);}catch(error){const latest=(await d.history.get(plan.finding.id,plan.finding.subject)).at(-1)!;if(!['false-positive','resolve'].includes(latest.event.action.type))throw error;await d.reproduction.readReceipt(plan.id,plan.finding.subject);}},
 };
 const identity=(entry:{runId:string|null;binding:unknown;attempt:unknown})=>canonical({runId:entry.runId,binding:entry.binding,attempt:entry.attempt});
 const markRuntimeQuiescent=async(entry:ReproductionDispatchClaim,observation:ReproductionRuntimeObservation)=>{observation=structuredClone(observation);const current=await d.dispatch.get(entry.operationId);if(!current)return fail();if(identity(current)!==identity(entry)||observation.runId!==current.runId)fail();const actual=await inspect(entry.operationId,current.attempt?.token);if(current.runId===null){if(current.binding||current.attempt||observation.status!=='NOT_STARTED'||actual.jobId||observation.units.length||observation.cleanup.length)fail();}else{if(!['COMPLETED','FAILED','CANCELLED','TERMINATED','TIMED_OUT'].includes(observation.status)||observation.units.length!==actual.unitIds.length)fail();for(const unit of actual.unitIds){const observed=observation.units.filter(u=>u.unitId===unit.unitId&&u.workflowId===unit.unitWorkflowId);if(observed.length!==1||!['COMPLETED','FAILED','CANCELLED','TERMINATED','TIMED_OUT','NOT_STARTED'].includes(observed[0]!.status))fail();const storedUnit=await d.evals.unit(unit.unitId);if(!storedUnit)fail();if(observation.status==='COMPLETED'&&(observed[0]!.status!=='COMPLETED'||storedUnit!.status!=='completed'||!observed[0]!.runId))fail();if(observation.status!=='COMPLETED'&&observation.cleanup.filter(u=>u.unitId===unit.unitId&&u.workflowId===unit.cleanupWorkflowId&&typeof u.runId==='string').length!==1)fail();}if(observation.cleanup.some(c=>!actual.unitIds.some(u=>u.unitId===c.unitId&&u.cleanupWorkflowId===c.workflowId)))fail();}quiescent.set(entry.operationId,{token:entry.token,identity:identity(current)});};
 const settlementReader:DispatchSettlementReader=async(c,ctx)=>{const observation=quiescent.get(ctx.operationId),lease=(await c.query('SELECT lease_token FROM agentci_reproduction_dispatch_state WHERE organization_id=$1 AND repository=$2 AND operation_id=$3',keys(ctx.operationId))).rows[0];if(!observation||observation.token!==lease?.lease_token||observation.identity!==identity(ctx.dispatch))return undefined;
  // Consume the ephemeral observation. A rolled-back settlement is re-observed
  // by recovery; settled operations must not accumulate in controller memory.
  quiescent.delete(ctx.operationId);
  const records=await history(c,ctx.plan.finding.id,ctx.subject),last=records.at(-1)!;const receiptRow=(await c.query('SELECT receipt FROM agentci_reproduction_receipts WHERE organization_id=$1 AND repository=$2 AND id=$3',keys(ctx.plan.id))).rows[0];const proofRow=(await c.query('SELECT id FROM agentci_reproduction_non_execution WHERE organization_id=$1 AND repository=$2 AND plan_id=$3',keys(ctx.plan.id))).rows[0];const receipt=receiptRow?await d.reproduction.readReceipt(ctx.plan.id,ctx.subject):null,proof=proofRow?await d.proofs.read(proofRow.id,ctx.subject):null;
  if(['false-positive','resolve'].includes(last.event.action.type))return {kind:'superseded',history:last,receipt,proof};const reproduced=records.find(r=>r.event.action.type==='reproduce'&&r.event.action.receiptId===ctx.plan.id);if(receipt&&reproduced)return {kind:'receipt-retained',history:reproduced,receipt};const unavailable=records.find(r=>r.event.action.type==='unavailable'&&r.event.action.proofId===proof?.id);if(proof&&unavailable)return {kind:'never-staged',history:unavailable,proof};return undefined;};
 return {activities,settlementReader,markRuntimeQuiescent};
}
