import {nameUuid} from '../evals/request-id.ts';
import {validateFindingHistoryRecord,type FindingHistoryRecord} from '../findings/history.ts';
import {validateNonExecutionProof,type ReproductionNonExecutionProof} from '../findings/non-execution.ts';
import type {FindingReceipt} from '../findings/lifecycle.ts';
import type {ReproductionPlan} from '../findings/reproduction.ts';
import {reproductionWorkflowId} from '../findings/workflow-identity.ts';
import {randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {canonical,digest} from '../review/engine.ts';
import {validateReproductionConfig,type ReproductionConfigIdentity} from '../findings/reproduction-config.ts';
import type {ReviewSubject} from '../reviewers/context.ts';
export class ReproductionDispatchConflict extends Error {constructor(){super('reproduction-dispatch-conflict');}}
export class ReproductionDispatchLeaseLost extends Error {constructor(){super('reproduction-dispatch-lease-lost');}}
import type {ReproductionCancellationCause} from '../findings/reproduction-transport.ts';
export type {ReproductionCancellationCause} from '../findings/reproduction-transport.ts';
export interface ReproductionDispatchBinding {schemaVersion:'v1alpha1';workflowType:'reproduceAdmittedFinding';workflowId:string;taskQueue:string;evalTaskQueue:string;operationId:string;planId:string;planDigest:string;requestDigest:string;subject:ReviewSubject}
export interface ReproductionDispatchRecord {operationId:string;planId:string;workflowId:string;binding:ReproductionDispatchBinding|null;attempt:{token:string;config:ReproductionConfigIdentity}|null;runId:string|null;acknowledged:boolean;settlement:{retainedReceiptDigest:string|null;retainedProofDigest:string|null;kind:DispatchSettlementEvidence['kind'];findingId:string;findingVersion:number;historyDigest:string;evidenceDigest:string}|null;cancellation:{cause:ReproductionCancellationCause;requestedAt:string}|null}
export interface ReproductionDispatchClaim extends ReproductionDispatchRecord {token:string}
export type DispatchSettlementEvidence =
 | {kind:'receipt-retained';history:FindingHistoryRecord;receipt:FindingReceipt}
 | {kind:'never-staged';history:FindingHistoryRecord;proof:ReproductionNonExecutionProof}
 | {kind:'superseded';history:FindingHistoryRecord;receipt:FindingReceipt|null;proof:ReproductionNonExecutionProof|null};
/** Trusted controller reader; return undefined until remote workflow/runner cleanup is verified.
 * A retained event alone does not prove execution quiescence. Do not bind to caller input. */
export type DispatchSettlementReader=(client:PoolClient,context:{operationId:string;plan:ReproductionPlan;subject:ReviewSubject;dispatch:ReproductionDispatchRecord},signal:AbortSignal)=>Promise<DispatchSettlementEvidence|undefined>;
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(v);
const hash=(v:unknown)=>typeof v==='string'&&/^sha256:[a-f0-9]{64}$/.test(v);
const fail=():never=>{throw new ReproductionDispatchConflict();};
const queue=(v:unknown)=>typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(v);
/** Persistence only. A binding is a retained dispatch identity, not live authority,
 * Temporal acknowledgement evidence, execution completion or a finding verdict. */
export class ReproductionDispatchStore {
 private scope:{organizationId:string;repository:string};
 constructor(private pool:Pool,scope:{organizationId:string;repository:string},private settlementReader?:DispatchSettlementReader){if(!uuid(scope.organizationId)||typeof scope.repository!=='string'||scope.repository.length>256||!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(scope.repository))fail();this.scope={...scope};}
 private args(id:string){if(!uuid(id))fail();return [this.scope.organizationId,this.scope.repository,id];}
 private async tx<T>(fn:(c:PoolClient)=>Promise<T>){let c:PoolClient;try{c=await this.pool.connect();}catch{throw Error('reproduction-dispatch-unavailable');}let released=false;const destroy=()=>{if(!released){released=true;c.release(true);}};c.on('error',destroy);try{await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='5s'");await c.query("SET LOCAL statement_timeout='10s'");await c.query("SET LOCAL transaction_timeout='15s'");const result=await fn(c);await c.query('COMMIT');return result;}catch(e){destroy();if(e instanceof ReproductionDispatchConflict||e instanceof ReproductionDispatchLeaseLost)throw e;throw Error('reproduction-dispatch-unavailable');}finally{if(!released)c.release();c.off('error',destroy);}}
 async ready(){await this.pool.query('SELECT s.binding,s.attempt_token,s.settlement,s.settled_at,a.config_revision,s.lease_token,s.retry_after,s.cancellation_cause FROM agentci_reproduction_dispatch_state s LEFT JOIN agentci_reproduction_dispatch_attempts a ON false LIMIT 0');}
 /** Read retained lineage on the caller's coherent snapshot; never claims a lease. */
 async readRetained(c:PoolClient,id:string){const r=await this.row(c,id);return r?{dispatch:this.decode(r),plan:structuredClone(r.plan) as ReproductionPlan,request:structuredClone(r.request),result:structuredClone(r.result)}:undefined;}
 async backfill(){return this.tx(async c=>{const r=await c.query('INSERT INTO agentci_reproduction_dispatch_state(organization_id,repository,operation_id) SELECT organization_id,repository,operation_id FROM agentci_reproduction_dispatch_intents WHERE organization_id=$1 AND repository=$2 ON CONFLICT DO NOTHING',[this.scope.organizationId,this.scope.repository]);return r.rowCount??0;});}
 private async row(c:PoolClient,id:string,lock=false){const r=(await c.query(`SELECT s.*,s.lease_until>clock_timestamp() AS lease_live,i.workflow_id,p.plan,p.digest AS plan_digest,o.reproduction_id,o.request,o.request_digest,o.result,o.result_digest FROM agentci_reproduction_dispatch_state s JOIN agentci_reproduction_dispatch_intents i USING(organization_id,repository,operation_id) JOIN agentci_reproduction_operations o USING(organization_id,repository,operation_id) JOIN agentci_reproduction_plans p ON p.organization_id=o.organization_id AND p.repository=o.repository AND p.id=o.reproduction_id WHERE s.organization_id=$1 AND s.repository=$2 AND s.operation_id=$3 ${lock?'FOR UPDATE OF s':''}`,this.args(id))).rows[0];if(!r)return undefined;
  if(r.plan_digest!==digest(canonical(r.plan))||r.request_digest!==digest(canonical(r.request))||r.result_digest!==digest(canonical(r.result))||r.plan.id!==r.reproduction_id||r.workflow_id!==reproductionWorkflowId(this.scope,r.reproduction_id)||r.request.operationId!==id||r.request.approvalId!==r.reproduction_id||r.request.approvalDigest!==r.plan_digest||r.result.operationId!==id||r.result.reproductionId!==r.reproduction_id||r.result.planDigest!==r.plan_digest||r.result.requestDigest!==r.request_digest||r.result.findingId!==r.plan.finding.id||r.result.reviewId!==r.plan.approval.reviewId||r.result.queuedVersion!==r.plan.finding.version||r.request.expectedVersion+1!==r.plan.finding.version||canonical(r.request.subject)!==canonical(r.plan.finding.subject)||r.plan.finding.subject.organizationId!==this.scope.organizationId||r.plan.finding.subject.repository!==this.scope.repository)fail();
  if(r.binding){if(r.binding_digest!==digest(canonical(r.binding)))fail();const b=r.binding as ReproductionDispatchBinding;if(canonical(b)!==canonical(this.binding(r,b.taskQueue,b.evalTaskQueue)))fail();}else if(r.binding_digest!==null||r.run_id!==null||r.acknowledged_at!==null)fail();if(r.attempt_token){const a=(await c.query('SELECT * FROM agentci_reproduction_dispatch_attempts WHERE organization_id=$1 AND repository=$2 AND operation_id=$3 AND token=$4',[...this.args(id),r.attempt_token])).rows[0];if(!a||a.binding_digest!==r.binding_digest)fail();r.attempt={token:a.token,config:{revision:Number(a.config_revision),digest:a.config_digest}};await this.config(c,r,r.attempt.config);}else if(r.binding||r.run_id)fail();return r;
 }
 private binding(r:any,taskQueue:string,evalTaskQueue:string):ReproductionDispatchBinding{if(!queue(taskQueue)||!queue(evalTaskQueue))fail();return {schemaVersion:'v1alpha1',workflowType:'reproduceAdmittedFinding',workflowId:r.workflow_id,taskQueue,evalTaskQueue,operationId:r.operation_id,planId:r.reproduction_id,planDigest:r.plan_digest,requestDigest:r.request_digest,subject:structuredClone(r.plan.finding.subject)};}
 private async config(c:PoolClient,r:any,id:ReproductionConfigIdentity){if(!id||Object.keys(id).sort().join(',')!=='digest,revision'||!Number.isSafeInteger(id.revision)||id.revision<1||!hash(id.digest))fail();const row=(await c.query('SELECT config,digest FROM agentci_reproduction_config_versions WHERE organization_id=$1 AND repository=$2 AND revision=$3',[this.scope.organizationId,this.scope.repository,id.revision])).rows[0];if(!row||row.digest!==id.digest||row.digest!==digest(canonical(row.config)))fail();const cfg=validateReproductionConfig(row.config),ref=cfg.approvals.find(p=>p.planId===r.reproduction_id);if(cfg.organizationId!==this.scope.organizationId||cfg.repository!==this.scope.repository||cfg.revision!==id.revision||!ref?.enabled||ref.planDigest!==r.plan_digest||ref.findingId!==r.plan.finding.id||ref.findingVersion!==r.request.expectedVersion)fail();}
 private decode(r:any):ReproductionDispatchRecord{return {operationId:r.operation_id,planId:r.reproduction_id,workflowId:r.workflow_id,binding:r.binding?structuredClone(r.binding):null,attempt:r.attempt?structuredClone(r.attempt):null,runId:r.run_id,acknowledged:r.acknowledged_at!==null,settlement:r.settlement?structuredClone(r.settlement):null,cancellation:r.cancellation_at?{cause:r.cancellation_cause,requestedAt:new Date(r.cancellation_at).toISOString()}:null};}
 private async fence(c:PoolClient,r:any,e:ReproductionDispatchClaim){if(!r||!uuid(e.token)||r.lease_token!==e.token||!(await c.query('SELECT lease_until>clock_timestamp() AS live FROM agentci_reproduction_dispatch_state WHERE organization_id=$1 AND repository=$2 AND operation_id=$3',this.args(e.operationId))).rows[0]?.live)throw new ReproductionDispatchLeaseLost();if(e.planId!==r.reproduction_id||e.workflowId!==r.workflow_id)fail();}
 async get(id:string){return this.tx(async c=>{const r=await this.row(c,id);return r?this.decode(r):undefined;});}
 /** Bounded immutable attempt history for remote-start reconciliation; token is the continuation key. */
 async attempts(id:string,after?:string){if(after!==undefined&&!uuid(after))fail();return this.tx(async c=>{const r=await this.row(c,id);if(!r)return [];const rows=(await c.query('SELECT token,config_revision,config_digest,binding_digest FROM agentci_reproduction_dispatch_attempts WHERE organization_id=$1 AND repository=$2 AND operation_id=$3 AND ($4::uuid IS NULL OR token>$4) ORDER BY token LIMIT 100',[...this.args(id),after??null])).rows;for(const a of rows){if(a.binding_digest!==r.binding_digest)fail();await this.config(c,r,{revision:Number(a.config_revision),digest:a.config_digest});}return rows.map(a=>({token:a.token,config:{revision:Number(a.config_revision),digest:a.config_digest}}));});}
 async claim(kind:'dispatch'|'recovery'='dispatch'):Promise<ReproductionDispatchClaim|undefined>{if(!['dispatch','recovery'].includes(kind))fail();return this.tx(async c=>{const r=(await c.query(`SELECT operation_id FROM agentci_reproduction_dispatch_state WHERE organization_id=$1 AND repository=$2 AND settlement IS NULL AND (lease_until IS NULL OR lease_until<clock_timestamp()) AND (retry_after IS NULL OR retry_after<=clock_timestamp()) AND ${kind==='dispatch'?'run_id IS NULL AND cancellation_at IS NULL':'(binding IS NOT NULL OR cancellation_at IS NOT NULL)'} ORDER BY operation_id LIMIT 1 FOR UPDATE SKIP LOCKED`,[this.scope.organizationId,this.scope.repository])).rows[0];if(!r)return undefined;await this.row(c,r.operation_id);const token=randomUUID();await c.query("UPDATE agentci_reproduction_dispatch_state SET lease_token=$4,lease_until=clock_timestamp()+interval '120 seconds' WHERE organization_id=$1 AND repository=$2 AND operation_id=$3",[...this.args(r.operation_id),token]);return {...this.decode(await this.row(c,r.operation_id)),token};});}
 async bind(entry:ReproductionDispatchClaim,options:{taskQueue:string;evalTaskQueue:string;config:ReproductionConfigIdentity}){options=structuredClone(options);return this.tx(async c=>{const r=await this.row(c,entry.operationId,true);await this.fence(c,r,entry);if(r.cancellation_at||r.run_id||r.settlement)fail();const b=this.binding(r,options.taskQueue,options.evalTaskQueue);await this.config(c,r,options.config);const active=(await c.query('SELECT revision FROM agentci_reproduction_authority WHERE organization_id=$1 AND repository=$2 FOR SHARE',[this.scope.organizationId,this.scope.repository])).rows[0];if(Number(active?.revision)!==options.config.revision||(await c.query('SELECT 1 FROM agentci_reproduction_revocations WHERE organization_id=$1 AND repository=$2 AND plan_id=$3',[this.scope.organizationId,this.scope.repository,r.reproduction_id])).rowCount)fail();if(r.binding&&canonical(r.binding)!==canonical(b))fail();const prior=(await c.query('SELECT config_revision,config_digest,binding_digest FROM agentci_reproduction_dispatch_attempts WHERE organization_id=$1 AND repository=$2 AND operation_id=$3 AND token=$4',[...this.args(entry.operationId),entry.token])).rows[0];if(prior&&(Number(prior.config_revision)!==options.config.revision||prior.config_digest!==options.config.digest||prior.binding_digest!==digest(canonical(b))))fail();await this.fence(c,r,entry);if(!prior)await c.query('INSERT INTO agentci_reproduction_dispatch_attempts(organization_id,repository,operation_id,token,binding_digest,config_revision,config_digest) VALUES($1,$2,$3,$4,$5,$6,$7)',[...this.args(entry.operationId),entry.token,digest(canonical(b)),options.config.revision,options.config.digest]);await this.fence(c,r,entry);await c.query('UPDATE agentci_reproduction_dispatch_state SET binding=$4,binding_digest=$5,attempt_token=$6 WHERE organization_id=$1 AND repository=$2 AND operation_id=$3',[...this.args(entry.operationId),b,digest(canonical(b)),entry.token]);return {...this.decode(await this.row(c,entry.operationId)),token:entry.token};});}
 async renew(entry:ReproductionDispatchClaim){return this.tx(async c=>{const r=await this.row(c,entry.operationId,true);await this.fence(c,r,entry);await c.query("UPDATE agentci_reproduction_dispatch_state SET lease_until=clock_timestamp()+interval '120 seconds' WHERE organization_id=$1 AND repository=$2 AND operation_id=$3",this.args(entry.operationId));});}
 /** Called only after trusted Temporal describe/history validates exact memo, type, queues and run. */
 async adoptObservedRun(entry:ReproductionDispatchClaim,observed:{attemptToken:string;runId:string}){entry=structuredClone(entry);observed=structuredClone(observed);if(!uuid(observed.runId)||!uuid(observed.attemptToken))fail();return this.tx(async c=>{const r=await this.row(c,entry.operationId,true);if(!r||r.settlement||!r.binding||canonical(entry.binding)!==canonical(r.binding))fail();if(r.acknowledged_at){if(r.run_id!==observed.runId||r.attempt_token!==observed.attemptToken)fail();return this.decode(r);}await this.fence(c,r,entry);if(canonical(entry.attempt)!==canonical(r.attempt))fail();const a=(await c.query('SELECT binding_digest,config_revision,config_digest FROM agentci_reproduction_dispatch_attempts WHERE organization_id=$1 AND repository=$2 AND operation_id=$3 AND token=$4',[...this.args(entry.operationId),observed.attemptToken])).rows[0];if(!a||a.binding_digest!==r.binding_digest)fail();await this.config(c,r,{revision:Number(a.config_revision),digest:a.config_digest});await this.fence(c,r,entry);await c.query('UPDATE agentci_reproduction_dispatch_state SET attempt_token=$4,run_id=$5,acknowledged_at=clock_timestamp(),lease_token=NULL,lease_until=NULL WHERE organization_id=$1 AND repository=$2 AND operation_id=$3',[...this.args(entry.operationId),observed.attemptToken,observed.runId]);return this.decode(await this.row(c,entry.operationId));});}
 async acknowledge(entry:ReproductionDispatchClaim,runId:string){const attempt=entry.attempt;if(!attempt)return fail();return this.adoptObservedRun(entry,{attemptToken:attempt.token,runId});}
 async release(entry:ReproductionDispatchClaim,retryAfterMs=10000){if(!Number.isSafeInteger(retryAfterMs)||retryAfterMs<0||retryAfterMs>3600000)fail();return this.tx(async c=>{const r=await this.row(c,entry.operationId,true);await this.fence(c,r,entry);await c.query("UPDATE agentci_reproduction_dispatch_state SET lease_token=NULL,lease_until=NULL,retry_after=clock_timestamp()+($4*interval '1 millisecond') WHERE organization_id=$1 AND repository=$2 AND operation_id=$3",[...this.args(entry.operationId),retryAfterMs]);});}
 /** Settlement classifies retained evidence, never execution success or a finding verdict. */
 async settle(entry:ReproductionDispatchClaim){entry=structuredClone(entry);if(!this.settlementReader)fail();return this.tx(async c=>{const r=await this.row(c,entry.operationId,true);if(!r||entry.planId!==r.reproduction_id||entry.workflowId!==r.workflow_id)fail();if(r.settlement)return this.decode(r);await this.fence(c,r,entry);
  await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[canonical([this.scope.organizationId,this.scope.repository,r.reproduction_id,'eval-stage'])]);
  await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[canonical([this.scope.organizationId,this.scope.repository,r.plan.finding.id])]);
  const abort=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;let evidence:DispatchSettlementEvidence|undefined;
  try{evidence=await Promise.race([this.settlementReader!(c,{operationId:entry.operationId,plan:structuredClone(r.plan),subject:structuredClone(r.plan.finding.subject),dispatch:this.decode(r)},abort.signal),new Promise<never>((_,reject)=>{timer=setTimeout(()=>{abort.abort();reject(Error('settlement-reader-unavailable'));},5000);})]);}finally{if(timer)clearTimeout(timer);abort.abort();}
  await this.fence(c,r,entry);if(!evidence)return undefined;evidence=structuredClone(evidence);const h=validateFindingHistoryRecord(evidence.history,r.plan.finding.subject);if(h.event.finding.id!==r.plan.finding.id||h.event.finding.version<=r.plan.finding.version)fail();
  const stored=(await c.query('SELECT digest,event FROM agentci_finding_events WHERE organization_id=$1 AND repository=$2 AND finding_id=$3 AND version=$4',[this.scope.organizationId,this.scope.repository,r.plan.finding.id,h.event.finding.version])).rows[0];if(!stored||canonical(stored)!==canonical(h))fail();
  const receipts=(await c.query('SELECT unit_id,digest,receipt FROM agentci_reproduction_receipts WHERE organization_id=$1 AND repository=$2 AND id=$3',[this.scope.organizationId,this.scope.repository,r.reproduction_id])).rows;
  const proofs=(await c.query('SELECT id,plan_id,operation_id,digest,proof FROM agentci_reproduction_non_execution WHERE organization_id=$1 AND repository=$2 AND plan_id=$3',[this.scope.organizationId,this.scope.repository,r.reproduction_id])).rows;
  const units=(await c.query('SELECT u.id,u.status FROM agentci_eval_jobs j JOIN agentci_eval_units u ON u.job_id=j.id WHERE j.source_organization_id=$1 AND j.repository=$2 AND j.source_operation_id=$3',this.args(entry.operationId))).rows;if(units.some(u=>!['completed','cancelled'].includes(u.status)))fail();let evidenceDigest:string;
  if(evidence.kind==='receipt-retained'){const receipt=receipts[0];if(!receipt||proofs.length||receipt.digest!==digest(canonical(receipt.receipt))||canonical(receipt.receipt)!==canonical(evidence.receipt)||canonical(h.event.receipt)!==canonical(evidence.receipt)||h.event.action.type!=='reproduce'||h.event.action.receiptId!==r.reproduction_id||h.event.operationId!==r.reproduction_id||h.event.finding.version!==r.plan.finding.version+1||!units.some(u=>u.id===receipt.unit_id)||evidence.receipt?.assertionDigest!==r.plan.assertionDigest)fail();evidenceDigest=receipt.digest;
  }else if(evidence.kind==='never-staged'){const p=validateNonExecutionProof(evidence.proof,r.plan.finding),proof=proofs[0];if(!proof||receipts.length||units.length||proof.id!==p.id||p.id!==nameUuid(r.reproduction_id,'agentci:non-execution:v1')||proof.plan_id!==r.reproduction_id||proof.operation_id!==entry.operationId||proof.digest!==digest(canonical(p))||canonical(proof.proof)!==canonical(p)||p.planId!==r.reproduction_id||p.planDigest!==r.plan_digest||p.reservationOperationId!==entry.operationId||p.queuedVersion!==r.plan.finding.version||p.queuedFindingDigest!==digest(canonical(r.plan.finding))||h.event.action.type!=='unavailable'||h.event.action.proofId!==p.id||h.event.receipt!==null||canonical(h.event.nonExecution)!==canonical(p))fail();evidenceDigest=proof.digest;
  }else if(evidence.kind==='superseded'){if(!['resolve','false-positive'].includes(h.event.action.type)||h.event.receipt?.actor!=='operator'||receipts.length&&proofs.length)fail();const receipt=receipts[0],proof=proofs[0];if(receipt){if(receipt.digest!==digest(canonical(receipt.receipt))||canonical(receipt.receipt)!==canonical(evidence.receipt)||evidence.receipt?.findingId!==r.plan.finding.id||evidence.receipt?.subjectDigest!==digest(canonical(r.plan.finding.subject))||evidence.receipt?.assertionDigest!==r.plan.assertionDigest||evidence.receipt?.actor!=='reproduction'||!units.some(u=>u.id===receipt.unit_id))fail();}else if(evidence.receipt!==null)fail();if(proof){const p=validateNonExecutionProof(evidence.proof,r.plan.finding);if(units.length||proof.id!==p.id||p.id!==nameUuid(r.reproduction_id,'agentci:non-execution:v1')||proof.plan_id!==r.reproduction_id||proof.operation_id!==entry.operationId||proof.digest!==digest(canonical(p))||canonical(proof.proof)!==canonical(p)||p.planId!==r.reproduction_id||p.planDigest!==r.plan_digest||p.reservationOperationId!==entry.operationId||p.queuedVersion!==r.plan.finding.version||p.queuedFindingDigest!==digest(canonical(r.plan.finding)))fail();}else if(evidence.proof!==null)fail();const latest=(await c.query('SELECT digest FROM agentci_finding_events WHERE organization_id=$1 AND repository=$2 AND finding_id=$3 ORDER BY version DESC LIMIT 1',[this.scope.organizationId,this.scope.repository,r.plan.finding.id])).rows[0];if(latest?.digest!==h.digest)fail();evidenceDigest=h.event.receipt!.evidenceDigest;
  }else return fail();
  const settlement={retainedReceiptDigest:receipts[0]?.digest??null,retainedProofDigest:proofs[0]?.digest??null,kind:evidence.kind,findingId:r.plan.finding.id,findingVersion:h.event.finding.version,historyDigest:h.digest,evidenceDigest};await this.fence(c,r,entry);await c.query('UPDATE agentci_reproduction_dispatch_state SET settlement=$4,settled_at=clock_timestamp(),lease_token=NULL,lease_until=NULL,retry_after=NULL WHERE organization_id=$1 AND repository=$2 AND operation_id=$3',[...this.args(entry.operationId),settlement]);return this.decode(await this.row(c,entry.operationId));});}
 async requestCancellation(id:string,cause:ReproductionCancellationCause){if(!['user','revoked','expired','permission-denied','superseded','unavailable'].includes(cause))fail();return this.tx(async c=>{const r=await this.row(c,id,true);if(!r)fail();if(!r.cancellation_at)await c.query('UPDATE agentci_reproduction_dispatch_state SET cancellation_at=clock_timestamp(),cancellation_cause=$4,retry_after=NULL WHERE organization_id=$1 AND repository=$2 AND operation_id=$3',[...this.args(id),cause]);return this.decode(await this.row(c,id));});}
}
