import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {ModelStreamValidator} from '../packages/providers/stream.ts';import {validateModelRequest} from '../packages/providers/request.ts';
function fixture(){const request=validateModelRequest(JSON.parse(readFileSync(new URL('../specs/api/fixtures/model-request.json',import.meta.url),'utf8'))),attemptId='attempt-1';const start={type:'start',requestId:request.requestId,attemptId,provider:request.provider,model:request.model};const response={schemaVersion:'v1alpha1',requestId:request.requestId,attemptId,provider:request.provider,model:request.model,status:'completed',text:'hello',structuredOutput:{claim:'fixture'},toolCalls:[],usage:{inputTokens:null,outputTokens:null,costUsdMicros:null,costKind:'unknown',pricingRevision:null},providerRequestId:null};return {request,start,response,validator:new ModelStreamValidator(request,attemptId)};}
test('stream binds identity and matches assembled text and final usage',()=>{const f=fixture();f.validator.accept(f.start);f.validator.accept({type:'text-delta',text:'hel'});f.validator.accept({type:'text-delta',text:'lo'});f.validator.accept({type:'usage',usage:f.response.usage});f.validator.accept({type:'terminal',response:f.response});assert.deepEqual(f.validator.finish(),f.response);assert.notEqual(f.validator.finish(),f.response);});
test('stream rejects missing start/end, duplicate start/end and mismatched text',()=>{
 for(const mode of ['missing-start','missing-end','duplicate-start','wrong-identity','wrong-text','duplicate-end']){const f=fixture();if(mode==='missing-start'){assert.throws(()=>f.validator.accept({type:'text-delta',text:'hello'}),/invalid-output/);continue;}if(mode==='wrong-identity'){assert.throws(()=>f.validator.accept({...f.start,attemptId:'other'}),/invalid-output/);continue;}f.validator.accept(f.start);if(mode==='duplicate-start'){assert.throws(()=>f.validator.accept(f.start),/invalid-output/);continue;}if(mode==='missing-end'){assert.throws(()=>f.validator.finish(),/invalid-output/);continue;}f.validator.accept({type:'text-delta',text:'hello'});if(mode==='wrong-text'){assert.throws(()=>f.validator.accept({type:'terminal',response:{...f.response,text:'different'}}),/invalid-output/);continue;}f.validator.accept({type:'terminal',response:f.response});assert.throws(()=>f.validator.accept({type:'terminal',response:f.response}),/invalid-output/);}
});
test('tool argument deltas assemble strictly and agree with final proposals',()=>{
 const f=fixture();f.request.tools=[{name:'inspect',description:'inspect',inputSchema:{type:'object',properties:{path:{type:'string'}},required:['path'],additionalProperties:false}}];
 const validator=new ModelStreamValidator(f.request,'attempt-1');validator.accept(f.start);validator.accept({type:'text-delta',text:'hello'});validator.accept({type:'tool-delta',id:'call-1',name:'inspect',argumentsDelta:'{"path":'});validator.accept({type:'tool-delta',id:'call-1',name:null,argumentsDelta:'"a.ts"}'});const response={...f.response,toolCalls:[{id:'call-1',name:'inspect',arguments:{path:'a.ts'}}]};validator.accept({type:'terminal',response});assert.deepEqual(validator.finish(),response);
 const bad=new ModelStreamValidator(f.request,'attempt-1');bad.accept(f.start);assert.throws(()=>bad.accept({type:'tool-delta',id:'call-1',name:'execute',argumentsDelta:'{}'}),/invalid-output/);
});
test('stream rejects excessive output and usage disagreement; usage must follow deltas',()=>{
 for(const mode of ['large','usage-change','late-delta']){const f=fixture();f.validator.accept(f.start);if(mode==='large'){assert.throws(()=>f.validator.accept({type:'text-delta',text:'x'.repeat(524289)}),/invalid-output/);continue;}f.validator.accept({type:'text-delta',text:'hello'});f.validator.accept({type:'usage',usage:f.response.usage});if(mode==='late-delta')assert.throws(()=>f.validator.accept({type:'text-delta',text:'more'}),/invalid-output/);else assert.throws(()=>f.validator.accept({type:'terminal',response:{...f.response,usage:{...f.response.usage,inputTokens:1}}}),/invalid-output/);}
});
test('a stream stays failed after invalid output, even after a previously valid terminal',()=>{const f=fixture();f.validator.accept(f.start);f.validator.accept({type:'text-delta',text:'hello'});f.validator.accept({type:'terminal',response:f.response});assert.throws(()=>f.validator.accept({type:'text-delta',text:'extra'}),/invalid-output/);assert.throws(()=>f.validator.finish(),/invalid-output/);});
