import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {once} from 'node:events';import {readFileSync} from 'node:fs';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {ModelReviewClient,AgentCIError,type ReviewAdmissionRequest,type ReproductionReference} from '../packages/client/index.ts';import {canonical,digest} from '../packages/review/engine.ts';
const f=JSON.parse(readFileSync(new URL('../specs/api/drafts/finding-reproduction-examples.json',import.meta.url),'utf8'));
const reviews=JSON.parse(readFileSync(new URL('../specs/api/drafts/model-review-examples.json',import.meta.url),'utf8'));
const reference=f.accepted as ReproductionReference,request={...reviews.request,id:reference.reviewId,subject:reference.subject} as ReviewAdmissionRequest;
const review={...reviews.statuses.queued,admission:{request,digest:digest(canonical(request))}},readToken='read-client-test-'.repeat(4),operatorToken='operator-client-test-'.repeat(4);
const code=(c:string)=>(e:unknown)=>e instanceof AgentCIError&&e.code===c;
async function server(t:any,handler:(req:any,res:any)=>void){const s=createServer(handler);s.listen(0,'127.0.0.1');await once(s,'listening');t.after(()=>new Promise<void>(r=>{s.closeAllConnections();s.close(()=>r());}));return `http://127.0.0.1:${(s.address() as any).port}`;}
const reply=(res:any,value:any,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value));};

test('public reproduction client pins all references and preserves every frozen status meaning',async t=>{let value=f.states[0].value;const calls:string[]=[];const url=await server(t,(req,res)=>{calls.push(req.url);assert.equal(req.headers.authorization,`Bearer ${readToken}`);reply(res,req.url.startsWith('/v1/model-reviews/')?review:value);});const client=new ModelReviewClient({url,readToken,maxAttempts:1});for(const state of f.states){value=state.value;assert.deepEqual(await client.reproductionStatus(request,reference),value,state.name);}assert.equal(calls.length,f.states.length*2);assert.ok(calls.filter(p=>p.startsWith('/v1/finding-reproductions/')).every(p=>p===`/v1/finding-reproductions/${reference.id}?reviewId=${request.id}`));});

test('invalid pins fail before I/O and wrong admission or response references prevent mutation',async t=>{let calls=0,mutations=0,mode='status';const url=await server(t,(req,res)=>{calls++;if(req.method==='POST')mutations++;const wrong=structuredClone(review);wrong.admission.request.subject.repository='other/repo';wrong.admission.digest=digest(canonical(wrong.admission.request));reply(res,req.url.startsWith('/v1/model-reviews/')?mode==='review'?wrong:review:{...f.states[0].value,planDigest:digest('wrong')});});const client=new ModelReviewClient({url,readToken,operatorToken,maxAttempts:1});for(const pin of [null,{...reference,id:'../private'},{...reference,command:['sh']},{...reference,reviewId:'11111111-1111-4111-8111-111111111111'},{...reference,subject:{...reference.subject,repository:'other/repo'}}])await assert.rejects(client.reproductionStatus(request,pin as any),code('invalid-reproduction-reference'));assert.equal(calls,0);for(mode of ['review','status'])await assert.rejects(client.cancelReproduction(request,reference),code(mode==='review'?'identity-mismatch':'invalid-response'));assert.equal(mutations,0);});

test('operator required before reads; ambiguous cancellation retries only the exact empty mutation',async t=>{const calls:any[]=[];let posts=0;const url=await server(t,(req,res)=>{calls.push({url:req.url,method:req.method,auth:req.headers.authorization});if(req.method==='POST'){assert.equal(req.headers['content-type'],undefined);let body='';req.on('data',(chunk:any)=>{body+=chunk;});req.on('end',()=>{assert.equal(body,'');posts++;if(posts===1){req.socket.destroy();return;}reply(res,f.cancellation,202);});return;}reply(res,req.url.startsWith('/v1/model-reviews/')?review:f.states[0].value);});await assert.rejects(new ModelReviewClient({url,readToken}).cancelReproduction(request,reference),code('operator-token-required'));assert.equal(calls.length,0);const client=new ModelReviewClient({url,readToken,operatorToken,maxAttempts:2});assert.deepEqual(await client.cancelReproduction(request,reference),f.cancellation);assert.equal(posts,2);assert.ok(calls.slice(0,2).every(c=>c.auth===`Bearer ${readToken}`));assert.ok(calls.slice(2).every(c=>c.auth===`Bearer ${operatorToken}`&&c.url===`/v1/finding-reproductions/${reference.id}/cancellation`));});

test('bounded malformed/redirect/error responses cannot claim status or cancellation success',async t=>{let mode='oversize';const url=await server(t,(req,res)=>{if(req.url.startsWith('/v1/model-reviews/')){reply(res,review);return;}if(mode==='redirect'){res.writeHead(302,{location:'/private'});res.end();return;}if(mode==='oversize'){res.writeHead(200,{'content-type':'application/json'});res.end('x'.repeat(4*1024*1024+1));return;}if(mode==='private'){reply(res,{error:{code:'private-sql-detail'}},503);return;}if(mode==='not-found'){reply(res,{error:{code:'not-found'}},404);return;}if(req.method!=='POST'){reply(res,f.states[0].value);return;}reply(res,{...f.cancellation,id:'11111111-1111-4111-8111-111111111111'},202);});const client=new ModelReviewClient({url,readToken,operatorToken,maxAttempts:1});for(const [m,c] of [['oversize','response-too-large'],['redirect','transport-failure'],['private','invalid-response'],['not-found','not-found']]){mode=m!;await assert.rejects(client.reproductionStatus(request,reference),code(c!));}mode='ack';await assert.rejects(client.cancelReproduction(request,reference),code('invalid-response'));});

test('caller abort interrupts identity preflight and status without mutation',async t=>{let mode='review',reached:()=>void=()=>{},posts=0;const url=await server(t,(req,res)=>{if(req.method==='POST')posts++;if(mode==='review'||!req.url.startsWith('/v1/model-reviews/')){reached();return;}reply(res,review);});const client=new ModelReviewClient({url,readToken,operatorToken,timeoutMs:120000,maxAttempts:1});for(mode of ['review','status']){const abort=new AbortController(),waiting=new Promise<void>(r=>{reached=r;});const rejected=assert.rejects(client.cancelReproduction(request,reference,{signal:abort.signal}),code('transport-failure'));await waiting;abort.abort();await rejected;}assert.equal(posts,0);});

test('one overall reproduction deadline includes admission and status body',async t=>{let statusReached=false;const url=await server(t,(req,res)=>{if(req.url.startsWith('/v1/model-reviews/'))setTimeout(()=>reply(res,review),70);else{statusReached=true;setTimeout(()=>reply(res,f.states[0].value),90);}});const client=new ModelReviewClient({url,readToken,timeoutMs:130,maxAttempts:1});await assert.rejects(client.reproductionStatus(request,reference),code('transport-failure'));assert.equal(statusReached,true);});

test('finding CLI requires bounded exact reference files and keeps errors/token output private',async t=>{let calls=0,posts=0;const url=await server(t,(req,res)=>{calls++;if(req.method==='POST'){posts++;reply(res,f.cancellation,202);}else reply(res,req.url.startsWith('/v1/model-reviews/')?review:f.states[0].value);});const dir=await mkdtemp(join(tmpdir(),'repro-cli-'));t.after(()=>rm(dir,{recursive:true,force:true}));const admission=join(dir,'request.json'),pin=join(dir,'reference.json');await writeFile(admission,JSON.stringify(request));await writeFile(pin,JSON.stringify(reference));const env={...process.env,AGENTCI_API_URL:url,AGENTCI_EVIDENCE_TOKEN:readToken,AGENTCI_OPERATOR_TOKEN:operatorToken},exec=promisify(execFile),main=new URL('../cmd/agentci/main.ts',import.meta.url).pathname;const run=(args:string[],e=env)=>exec(process.execPath,['--import','tsx',main,'finding',...args],{env:e});const args=['--request',admission,'--reproduction',pin];assert.match((await run(['--help'])).stdout,/cancel-reproduction/);assert.equal(calls,0);for(const invalid of [['reproduction-status',...args,'--id',reference.finding.id],['cancel-reproduction','--request',admission],['reproduction-status',...args,'--reproduction',pin]])await assert.rejects(run(invalid),(e:any)=>e.code===2&&e.stdout===''&&!e.stderr.includes(operatorToken));assert.equal(calls,0);assert.equal(JSON.parse((await run(['reproduction-status',...args])).stdout).dispatch.state,'queued');assert.deepEqual(JSON.parse((await run(['cancel-reproduction',...args])).stdout),f.cancellation);assert.equal(posts,1);await writeFile(pin,'x'.repeat(8193));await assert.rejects(run(['cancel-reproduction',...args]),(e:any)=>e.code===2&&e.stdout===''&&JSON.parse(e.stderr).error.code==='invalid-reproduction-reference-file');assert.equal(posts,1);});
