import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {OpenAIStreamTranslator} from '../packages/providers/openai-stream.ts';
const request=()=>({...JSON.parse(readFileSync(new URL('../specs/api/fixtures/model-request.json',import.meta.url),'utf8')),provider:'openai'});
function events(){return [{type:'response.created',response:{id:'resp-fixture'}},{type:'response.output_item.added',output_index:0,item:{id:'msg-1',type:'message'}},{type:'response.output_text.delta',item_id:'msg-1',output_index:0,delta:'{"claim":'},{type:'response.output_text.delta',item_id:'msg-1',output_index:0,delta:'"fixture"}'},{type:'response.completed',response:{id:'resp-fixture',model:request().model,status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'{"claim":"fixture"}'}]}],usage:{input_tokens:1,output_tokens:1,total_tokens:2}}}].map((event,sequence_number)=>({...event,sequence_number}));}
test('OpenAI stream translates ordered text, usage and exact final response',()=>{const translator=new OpenAIStreamTranslator(request(),'attempt-1');const output=events().flatMap(event=>translator.accept(event,'req-fixture'));assert.deepEqual(output.map(e=>e.type),['start','text-delta','text-delta','usage','terminal']);assert.deepEqual(translator.finish().structuredOutput,{claim:'fixture'});});
test('OpenAI stream rejects gaps, wrong item identity, unexpected events and missing terminal',()=>{
 for(const mode of ['gap','item','unknown','terminal']){const translator=new OpenAIStreamTranslator(request(),'attempt-1'),input=events();if(mode==='gap')input[2]!.sequence_number=9;if(mode==='item')(input[2] as any).item_id='other';if(mode==='unknown')(input[2] as any).type='new.unknown';if(mode==='terminal'){for(const event of input.slice(0,-1))translator.accept(event,null);assert.throws(()=>translator.finish(),/invalid-output/);}else{assert.throws(()=>input.forEach(event=>translator.accept(event,null)),/invalid-output/);assert.throws(()=>translator.finish(),/invalid-output/);}}
});
test('OpenAI tool stream requires matching argument completion and declared tool schema',()=>{
 const req={...request(),responseSchema:null,tools:[{name:'inspect',description:'Inspect',inputSchema:{type:'object',properties:{path:{type:'string'}},required:['path'],additionalProperties:false}}]};
 const input=[{type:'response.created',response:{id:'resp-fixture'}},{type:'response.output_item.added',output_index:0,item:{id:'item-1',type:'function_call',call_id:'call-1',name:'inspect',arguments:''}},{type:'response.function_call_arguments.delta',output_index:0,item_id:'item-1',delta:'{"path":"a.ts"}'},{type:'response.function_call_arguments.done',output_index:0,item_id:'item-1',arguments:'{"path":"a.ts"}'},{type:'response.completed',response:{id:'resp-fixture',model:req.model,status:'completed',output:[{type:'function_call',call_id:'call-1',name:'inspect',arguments:'{"path":"a.ts"}'}],usage:null}}].map((e,sequence_number)=>({...e,sequence_number}));const translator=new OpenAIStreamTranslator(req,'attempt-1');input.forEach(e=>translator.accept(e,null));assert.deepEqual(translator.finish().toolCalls,[{id:'call-1',name:'inspect',arguments:{path:'a.ts'}}]);
 const bad=new OpenAIStreamTranslator(req,'attempt-1');input.slice(0,3).forEach(e=>bad.accept(e,null));assert.throws(()=>bad.accept({...input[3],arguments:'{}'},null),/invalid-output/);
});
test('OpenAI refusal and incomplete streams preserve non-actionable outcomes',()=>{
 for(const refusal of [true,false]){const req=request(),translator=new OpenAIStreamTranslator(req,'attempt-1');const text=refusal?'Unable to comply':'{"claim":';const input=[{type:'response.created',response:{id:'resp-fixture'}},{type:'response.output_item.added',output_index:0,item:{id:'msg-1',type:'message'}},{type:refusal?'response.refusal.delta':'response.output_text.delta',output_index:0,item_id:'msg-1',delta:text},{type:refusal?'response.completed':'response.incomplete',response:{id:'resp-fixture',model:req.model,status:refusal?'completed':'incomplete',output:[{type:'message',role:'assistant',status:refusal?'completed':'incomplete',content:[refusal?{type:'refusal',refusal:text}:{type:'output_text',text}]}],usage:null}}];input.forEach((event,sequence_number)=>translator.accept({...event,sequence_number},null));const result=translator.finish();assert.equal(result.status,refusal?'refused':'incomplete');assert.equal(result.structuredOutput,null);assert.deepEqual(result.toolCalls,[]);}
});
