import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createOpenAITransport} from '../packages/providers/openai-transport.ts';
const request=()=>({...JSON.parse(readFileSync(new URL('../specs/api/fixtures/model-request.json',import.meta.url),'utf8')),provider:'openai',policy:{deadlineAt:Date.now()+5000,maxAttempts:2,baseDelayMs:1,maxDelayMs:5}});
const context=()=>({attemptId:'attempt-1',signal:new AbortController().signal});
const response=()=>({id:'resp-fixture',model:request().model,status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:'{"claim":"fixture"}',annotations:[]}]}],usage:{input_tokens:1,output_tokens:1,total_tokens:2}});
test('official SDK transport targets fixed origin and disables storage/redirects with normalized output',async()=>{
 let calls=0;const transport=createOpenAITransport('synthetic-fixture',async(input,init)=>{calls++;assert.equal(String(input),'https://api.openai.com/v1/responses');assert.equal(init?.redirect,'error');const headers=new Headers(init?.headers);assert.equal(headers.get('authorization'),'Bearer synthetic-fixture');assert.equal(headers.has('openai-organization'),false);assert.equal(headers.has('openai-project'),false);assert.equal(JSON.parse(init!.body as string).store,false);return new Response(JSON.stringify(response()),{headers:{'content-type':'application/json','x-request-id':'req-fixture'}});});const result=await transport.invoke(request(),context());assert.equal(result.providerRequestId,'req-fixture');assert.equal(result.status,'completed');assert.equal(calls,1);
});
test('official SDK cannot multiply retries, and provider error text is redacted',async()=>{
 let calls=0;const transport=createOpenAITransport('synthetic-fixture',async()=>{calls++;return new Response(JSON.stringify({error:{code:'rate_limit_exceeded',message:'private-fixture'}}),{status:429,headers:{'content-type':'application/json','retry-after':'2'}});});await assert.rejects(transport.invoke(request(),context()),(error:any)=>error.code==='rate-limit'&&error.retryAfterMs===2000&&!error.message.includes('private'));assert.equal(calls,1);
});
test('expired requests and cancellation fail before fetch; oversized bodies fail closed',async()=>{
 let calls=0;const transport=createOpenAITransport('synthetic-fixture',async()=>{calls++;return new Response('x'.repeat(4194305),{headers:{'content-type':'application/json'}});});const req=request();req.policy.deadlineAt=Date.now()-1;await assert.rejects(transport.invoke(req,context()),/deadline/);assert.equal(calls,0);const controller=new AbortController();controller.abort();await assert.rejects(transport.invoke(request(),{attemptId:'a',signal:controller.signal}),/cancelled/);assert.equal(calls,0);await assert.rejects(transport.invoke(request(),context()),/invalid-output/);assert.equal(calls,1);
});
test('official SDK parses incremental SSE events through the bounded transport',async()=>{
 const events=[{type:'response.created',sequence_number:0,response:{id:'resp-fixture'}},{type:'response.completed',sequence_number:1,response:response()}];const transport=createOpenAITransport('synthetic-fixture',async()=>new Response(events.map(event=>`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`).join(''),{headers:{'content-type':'text/event-stream','x-request-id':'req-stream'}}));const observed=[];for await(const frame of transport.events(request(),context())){observed.push(frame.event.type);assert.equal(frame.requestId,'req-stream');}assert.deepEqual(observed,['response.created','response.completed']);
});
