import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,writeFile,chmod,rm,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {generateKeyPairSync,randomUUID} from 'node:crypto';import {createServer} from 'node:http';import {once} from 'node:events';import type {Octokit} from '@octokit/rest';
import {loadReviewOperatorConfig,requestOperatorReview,OperatorReviewError,type ReviewOperatorConfig} from '../packages/operator/review.ts';import {createControlApi} from '../apps/control/server.ts';import {DeliveryConflict} from '../packages/storage/postgres.ts';import {reviewJob,webhookConfig} from './fixtures/control.ts';
const config:ReviewOperatorConfig={url:'http://127.0.0.1:3000',repository:reviewJob.repository,appId:42,installationId:reviewJob.installationId,privateKey:'private-test-key-never-transmitted',webhookSecret:webhookConfig.secret};
const pr=()=>({number:reviewJob.pullRequest,state:'open',base:{sha:reviewJob.baseSha,repo:{full_name:reviewJob.repository}},head:{sha:reviewJob.headSha}});
const github=(read:()=>unknown=pr)=>({pulls:{get:async()=>({data:read()})}} as unknown as Pick<Octokit,'pulls'>);
const code=(expected:string)=>(e:unknown)=>e instanceof OperatorReviewError&&e.code===expected&&!JSON.stringify(e).includes(config.privateKey)&&!JSON.stringify(e).includes(config.webhookSecret);
test('private operator config rejects extra/read-only credentials, unsafe origins and nonprivate/symlink files',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'agentci-operator-config-'));try{
  const key=generateKeyPairSync('rsa',{modulusLength:2048}).privateKey.export({type:'pkcs8',format:'pem'}),keyPath=join(directory,'app.pem'),secretPath=join(directory,'secret'),path=join(directory,'operator.json');await writeFile(keyPath,key,{mode:0o600});await writeFile(secretPath,config.webhookSecret,{mode:0o600});
  const values={url:config.url,repository:config.repository,appId:42,installationId:config.installationId,privateKeyFile:'app.pem',webhookSecretFile:'secret'};const save=async(v:unknown)=>writeFile(path,JSON.stringify(v),{mode:0o600});await save(values);const loaded=await loadReviewOperatorConfig(path);assert.equal(loaded.repository,config.repository);assert.equal(loaded.webhookSecret,config.webhookSecret);
  for(const url of ['http://public.example','https://user:password@example.com','https://example.com/path','https://example.com?token=x','https://example.com#secret']){await save({...values,url});await assert.rejects(loadReviewOperatorConfig(path),code('invalid-operator-origin'));}
  await save({...values,evidenceToken:'read-only-token'});await assert.rejects(loadReviewOperatorConfig(path),code('invalid-operator-config'));await save(values);await chmod(secretPath,0o644);await assert.rejects(loadReviewOperatorConfig(path),code('invalid-private-operator-file'));await chmod(secretPath,0o600);
  await symlink(secretPath,join(directory,'secret-link'));await save({...values,webhookSecretFile:'secret-link'});await assert.rejects(loadReviewOperatorConfig(path),code('invalid-private-operator-file'));
  await save(values);await chmod(path,0o644);await assert.rejects(loadReviewOperatorConfig(path),code('invalid-private-operator-file'));await chmod(path,0o600);await writeFile(path,'x'.repeat(16385));await assert.rejects(loadReviewOperatorConfig(path),code('invalid-private-operator-file'));
 }finally{await rm(directory,{recursive:true,force:true});}
});
test('operator review queues a fresh signed exact subject and safely repeats ambiguous submission UUID against the actual API',async t=>{
 const deliveries=new Map<string,string>(),jobs:unknown[]=[];const server=createControlApi(webhookConfig,{ready:async()=>{},evidence:async()=>undefined,recordDelivery:async(id,hash,job)=>{if(deliveries.has(id)){if(deliveries.get(id)!==hash)throw new DeliveryConflict();return 'duplicate';}deliveries.set(id,hash);jobs.push(job);return 'accepted';}});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const local={...config,url:`http://127.0.0.1:${(server.address() as {port:number}).port}`};
 const requestId=randomUUID();await assert.rejects(requestOperatorReview(local,reviewJob.pullRequest,{requestId,github:github(),fetch:async(...args)=>{const response=await fetch(...args);await response.body?.cancel();throw new Error('Lost response with private transport diagnostics');}}),e=>code('submission-unknown')(e)&&(e as OperatorReviewError).requestId===requestId);assert.equal(jobs.length,1);
 const duplicate=await requestOperatorReview(local,reviewJob.pullRequest,{requestId,github:github()});assert.equal(duplicate.status,'duplicate');assert.equal(duplicate.requestId,requestId);assert.deepEqual(duplicate.subject,reviewJob);assert.equal(jobs.length,1);const fresh=await requestOperatorReview(local,reviewJob.pullRequest,{github:github()});assert.equal(fresh.status,'queued');assert.notEqual(fresh.requestId,requestId);assert.equal(jobs.length,2);assert.ok(!JSON.stringify(fresh).includes(config.privateKey));assert.ok(!JSON.stringify(fresh).includes(config.webhookSecret));
 await assert.rejects(requestOperatorReview({...local,webhookSecret:'wrong'.repeat(10)},reviewJob.pullRequest,{github:github()}),code('signature-rejected'));await assert.rejects(requestOperatorReview(local,reviewJob.pullRequest,{requestId,github:github(()=>({...pr(),head:{sha:'c'.repeat(40)}}))}),code('request-id-conflict'));assert.equal(jobs.length,2);
});
test('operator review rejects closed/mismatched subjects, forged/oversized receipts and redirects without leaking provider failures',async t=>{
 let sent=0;const transport:typeof fetch=async()=>{sent++;return new Response('{}',{status:202,headers:{'content-type':'application/json'}});};
 for(const invalid of [{...pr(),state:'closed'},{...pr(),number:999},{...pr(),base:{sha:reviewJob.baseSha,repo:{full_name:'other/repo'}}},{...pr(),base:undefined}])await assert.rejects(requestOperatorReview(config,reviewJob.pullRequest,{github:github(()=>invalid),fetch:transport}),code(invalid.state==='closed'?'pull-request-not-open':'pull-request-identity-mismatch'));assert.equal(sent,0);
 await assert.rejects(requestOperatorReview(config,reviewJob.pullRequest,{github:github(()=>{throw Object.assign(new Error(config.privateKey),{request:{headers:{authorization:config.webhookSecret}}});}),fetch:transport}),code('github-read-unavailable'));assert.equal(sent,0);
 for(const body of ['{}',JSON.stringify({deliveryId:randomUUID(),status:'queued'}),'x'.repeat(16385)])await assert.rejects(requestOperatorReview(config,reviewJob.pullRequest,{github:github(),fetch:async()=>new Response(body,{status:202,headers:{'content-type':'application/json'}})}),code('invalid-review-receipt'));
 for(const [status,expected] of [[403,'scope-rejected'],[503,'service-unavailable']] as const)await assert.rejects(requestOperatorReview(config,reviewJob.pullRequest,{github:github(),fetch:async()=>new Response(config.privateKey,{status})}),code(expected));
 const server=createServer((_req,res)=>{res.writeHead(302,{location:'https://example.invalid/do-not-send'});res.end();});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));await assert.rejects(requestOperatorReview({...config,url:`http://127.0.0.1:${(server.address() as {port:number}).port}`},reviewJob.pullRequest,{github:github()}),code('submission-unknown'));
 await assert.rejects(requestOperatorReview(config,0,{github:github()}),code('invalid-review-arguments'));await assert.rejects(requestOperatorReview(config,reviewJob.pullRequest,{requestId:'invalid',github:github()}),code('invalid-review-arguments'));
});
