import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile,writeFile,rm,mkdtemp,realpath} from 'node:fs/promises';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';import {once} from 'node:events';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {reproductionStagingFixture} from '../helpers/reproduction-staging-fixture.ts';import {Store} from '../../packages/storage/postgres.ts';import {canonical,digest} from '../../packages/review/engine.ts';import {OperatorReceipts} from '../../packages/storage/operator-receipts.ts';import {operatorDispositionReceiptId} from '../../packages/findings/disposition-transport.ts';
if(!process.env.AGENTCI_TEST_DATABASE_URL)throw Error('Disposition acceptance requires real PostgreSQL; never silently skip');
const root=process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT??new URL('../../',import.meta.url).pathname,probe=resolve(process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT?resolve(root,'../..'):root,`disposition-client-${randomUUID()}.mjs`);
await writeFile(probe,"export {ModelReviewClient,AgentCIError} from 'agentci/client';export const resolved=import.meta.resolve('agentci/client');\n");let pub:any;try{pub=await import(pathToFileURL(probe).href);}finally{await rm(probe);}assert.equal(pub.resolved,pathToFileURL(await realpath(resolve(root,'dist/packages/client/index.js'))).href);
const {ModelReviewClient,AgentCIError}=pub,{createModelReviewControl}=await import(pathToFileURL(resolve(root,'dist/apps/control/model-reviews.js')).href),{createControlApi}=await import(pathToFileURL(resolve(root,'dist/apps/control/server.js')).href);
async function fixture(loseReply=false){const f=await reproductionStagingFixture(),servers:any[]=[],bodies:string[]=[];try{
 await new Store(f.pool,f.scope.organizationId,f.scope.repository).ready();for(const name of ['015_m3_reproduction_eval_source','016_m3_reproduction_authority','017_m3_reproduction_dispatch_state','018_m3_reproduction_dispatch_settlement','019_m3_reproduction_dispatch_initialization','020_m3_operator_receipts'])await f.pool.query(await readFile(new URL(`../../deploy/migrations/${name}.sql`,import.meta.url),'utf8'));await f.store.reserve(f.f.initial.id,f.selector);
 const config={...f.scope,installationId:123,cursorKey:'independent-cursor-'.repeat(3),evidenceToken:'reader-test-'.repeat(4),operatorToken:'operator-test-'.repeat(4),secret:'hook-test-'.repeat(4)};
 const start=async()=>{const control=await createModelReviewControl(f.pool,config),s=createControlApi(config,{ready:async()=>{},recordDelivery:async()=>{throw Error();},evidence:async()=>undefined},undefined,control);s.on('request',(req:any,res:any)=>{if(req.method==='POST'&&req.url?.endsWith('/dispositions')){const chunks:Buffer[]=[];req.on('data',(c:Buffer)=>chunks.push(c));req.once('end',()=>bodies.push(Buffer.concat(chunks).toString()));if(loseReply){const end=res.end.bind(res);res.end=(...args:any[])=>{if(loseReply&&res.statusCode===200){loseReply=false;res.destroy();return res;}return end(...args);};}}});s.listen(0,'127.0.0.1');await once(s,'listening');servers.push(s);return `http://127.0.0.1:${s.address().port}`;};
 const url=await start(),request={schemaVersion:'v1alpha1',reviewId:f.request.id,subject:f.request.subject,expectedVersion:2,operationId:randomUUID(),disposition:'false-positive',reason:'Operator inspected the retained assertion and classified it',evidenceDigest:digest('operator-evidence-reference')},client=new ModelReviewClient({url,readToken:config.evidenceToken,operatorToken:config.operatorToken,maxAttempts:1}),counts=async()=>[Number((await f.pool.query('SELECT count(*) FROM agentci_operator_receipts')).rows[0].count),Number((await f.pool.query('SELECT count(*) FROM agentci_finding_events')).rows[0].count)];
 return {...f,admission:f.request,config,url,request,client,start,bodies,counts,closeAll:async()=>{for(const s of servers){s.closeAllConnections();await new Promise<void>(r=>s.close(()=>r()));}await f.close();}};
}catch(error){await f.close();throw error;}}
test('operator-only disposition rejects forged receipts/confirmation, wrong scope/review/version and invalid transitions without retained mutation',async()=>{const f=await fixture();try{
 const path=`${f.url}/v1/findings/${encodeURIComponent(f.f.initial.id)}/dispositions`,post=(body:any,token=f.config.operatorToken)=>fetch(path,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)});
 assert.equal((await post(f.request,f.config.evidenceToken)).status,403);assert.equal((await post(f.request,'wrong-token')).status,401);
 for(const body of [{...f.request,disposition:'confirmed'},{...f.request,receipt:{actor:'operator'}},{...f.request,actor:'operator'},{...f.request,reason:' '},{...f.request,reason:'x'.repeat(4097)}])assert.equal((await post(body)).status,400);
 assert.equal((await post({...f.request,subject:{...f.request.subject,repository:'other/repo'}})).status,404);assert.equal((await post({...f.request,reviewId:randomUUID()})).status,404);assert.equal((await post({...f.request,expectedVersion:1})).status,409);const invalid=await post({...f.request,disposition:'resolved'});assert.equal(invalid.status,409);assert.deepEqual(await invalid.json(),{error:{code:'invalid-transition'}});assert.deepEqual(await f.counts(),[0,2]);
 await assert.rejects(new ModelReviewClient({url:f.url,readToken:f.config.evidenceToken}).setFindingDisposition(f.admission,f.f.initial.id,f.request),(e:any)=>e instanceof AgentCIError&&e.code==='operator-token-required');
}finally{await f.closeAll();}});
test('concurrent exact operator requests retain one immutable receipt/event; replay after resolution/restart preserves original outcome and CLI/current reads agree',async()=>{const f=await fixture(),dir=await mkdtemp(join(tmpdir(),'disposition-cli-'));try{
 const fail=(code:string)=>(e:any)=>e instanceof AgentCIError&&e.code===code,admission=f.admission;
 const [a,b]=await Promise.all([f.client.setFindingDisposition(admission,f.f.initial.id,f.request),f.client.setFindingDisposition(admission,f.f.initial.id,f.request)]);assert.deepEqual(a,b);assert.equal(a.event.finding.state,'false-positive');assert.equal(a.event.receipt.actor,'operator');assert.equal(a.event.receipt.assertionDigest,null);assert.deepEqual(await f.counts(),[1,3]);
 const originalFetch=globalThis.fetch;try{globalThis.fetch=async(...args:Parameters<typeof fetch>)=>{const response=await originalFetch(...args);if(args[1]?.method==='POST'&&String(args[0]).endsWith('/dispositions')&&response.status===200){const value=await response.json();value.event.operationId=randomUUID();value.digest=digest(canonical(value.event));return new Response(JSON.stringify(value),{status:200,headers:response.headers});}return response;};await assert.rejects(f.client.setFindingDisposition(admission,f.f.initial.id,f.request),fail('invalid-response'));}finally{globalThis.fetch=originalFetch;}assert.deepEqual(await f.counts(),[1,3]);
 await assert.rejects(f.client.setFindingDisposition(admission,f.f.initial.id,{...f.request,reason:'Changed claim'}),fail('idempotency-conflict'));await assert.rejects(f.client.setFindingDisposition(admission,f.f.initial.id,{...f.request,operationId:randomUUID()}),fail('version-conflict'));
 const resolved=await f.client.setFindingDisposition(admission,f.f.initial.id,{...f.request,operationId:randomUUID(),expectedVersion:3,disposition:'resolved',reason:'Operator supplied a correction reference'});assert.equal(resolved.event.finding.state,'resolved');assert.equal((await f.client.finding(admission,f.f.initial.id)).event.finding.state,'resolved');assert.deepEqual(await f.client.setFindingDisposition(admission,f.f.initial.id,f.request),a);
 const restartedUrl=await f.start(),restarted=new ModelReviewClient({url:restartedUrl,operatorToken:f.config.operatorToken,maxAttempts:1});assert.deepEqual(await restarted.setFindingDisposition(admission,f.f.initial.id,f.request),a);
 const admissionPath=join(dir,'admission.json'),input=join(dir,'disposition.json');await writeFile(admissionPath,JSON.stringify(admission));await writeFile(input,JSON.stringify(f.request));const run=promisify(execFile),args=[resolve(root,'dist/cmd/agentci/main.js'),'finding','disposition','--request',admissionPath,'--id',f.f.initial.id,'--disposition',input],env={...process.env,AGENTCI_API_URL:restartedUrl,AGENTCI_EVIDENCE_TOKEN:f.config.evidenceToken,AGENTCI_OPERATOR_TOKEN:f.config.operatorToken};assert.deepEqual(JSON.parse((await run(process.execPath,args,{env})).stdout),a);
 const fifo=join(dir,'input.fifo');await run('mkfifo',[fifo]);await assert.rejects(run(process.execPath,args.map(v=>v===input?fifo:v),{env,timeout:2000}),(e:any)=>e.code===2&&!e.killed&&e.stdout===''&&JSON.parse(e.stderr).error.code==='invalid-disposition-file');
 for(const sql of ['UPDATE agentci_operator_receipts SET receipt=receipt','DELETE FROM agentci_operator_receipts'])await assert.rejects(f.pool.query(sql),/Immutable/);
 const migration=await readFile(new URL('../../deploy/migrations/020_m3_operator_receipts.sql',import.meta.url),'utf8');await f.pool.query(migration);assert.deepEqual(await f.counts(),[2,4]);await assert.rejects(f.pool.query(migration.replace('CREATE TABLE agentci_operator_receipts','CREATE TABLE changed_operator_receipts')),/checksum/);await f.pool.query('ROLLBACK');assert.deepEqual(await f.counts(),[2,4]);
}finally{await rm(dir,{recursive:true,force:true});await f.closeAll();}});
test('history insert failure rolls back receipt, redacts database details and original operation can recover; trusted reader rejects corruption and cross-scope access',async()=>{const f=await fixture();try{
 const admission=f.admission;
 await f.pool.query("CREATE FUNCTION disposition_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'private-db-detail'; END $$; CREATE TRIGGER disposition_failure BEFORE INSERT ON agentci_finding_events FOR EACH ROW EXECUTE FUNCTION disposition_failure()");await assert.rejects(f.client.setFindingDisposition(admission,f.f.initial.id,f.request),(e:any)=>e instanceof AgentCIError&&e.code==='service-unavailable'&&!e.message.includes('private-db-detail'));assert.deepEqual(await f.counts(),[0,2]);await f.pool.query('DROP TRIGGER disposition_failure ON agentci_finding_events');await f.client.setFindingDisposition(admission,f.f.initial.id,f.request);
 const c=await f.pool.connect(),id=operatorDispositionReceiptId(f.request.operationId),receipts=new OperatorReceipts(f.scope);try{assert.equal((await receipts.read(c,id,f.request.subject)).actor,'operator');await assert.rejects(receipts.read(c,id,{...f.request.subject,headSha:'e'.repeat(40)}));await assert.rejects(new OperatorReceipts({...f.scope,repository:'other/repo'}).read(c,id,f.request.subject));
  const original=(await c.query('SELECT event,digest FROM agentci_finding_events WHERE operation_id=$1',[f.request.operationId])).rows[0],changedEvent={...original.event,operationId:randomUUID()};await c.query('ALTER TABLE agentci_finding_events DISABLE TRIGGER finding_event_immutable');try{await c.query('UPDATE agentci_finding_events SET event=$1,digest=$2 WHERE operation_id=$3',[changedEvent,digest(canonical(changedEvent)),f.request.operationId]);await assert.rejects(receipts.read(c,id,f.request.subject),/operator-receipt-unavailable/);}finally{await c.query('UPDATE agentci_finding_events SET event=$1,digest=$2 WHERE operation_id=$3',[original.event,original.digest,f.request.operationId]);await c.query('ALTER TABLE agentci_finding_events ENABLE TRIGGER finding_event_immutable');}assert.equal((await receipts.read(c,id,f.request.subject)).actor,'operator');
  await c.query('ALTER TABLE agentci_operator_receipts DISABLE TRIGGER operator_receipt_immutable');const row=(await c.query('SELECT * FROM agentci_operator_receipts')).rows[0],badRequest={...row.request,reason:'rehashed-substitution'},badReceipt={...row.receipt,reason:badRequest.reason};await c.query('UPDATE agentci_operator_receipts SET request=$1,request_digest=$2,receipt=$3,receipt_digest=$4',[badRequest,digest(canonical(badRequest)),badReceipt,digest(canonical(badReceipt))]);await assert.rejects(receipts.read(c,id,f.request.subject));await c.query('ALTER TABLE agentci_operator_receipts ENABLE TRIGGER operator_receipt_immutable');
 }finally{c.release();}
}finally{await f.closeAll();}});
test('lost disposition response retries exact operator input with one receipt/event and no implicit evaluator execution',async()=>{const f=await fixture(true);try{
 const admission=f.admission,client=new ModelReviewClient({url:f.url,operatorToken:f.config.operatorToken,maxAttempts:2});const result=await client.setFindingDisposition(admission,f.f.initial.id,f.request);assert.equal(result.event.finding.state,'false-positive');assert.equal(f.bodies.length,2);assert.equal(f.bodies[0],f.bodies[1]);assert.deepEqual(await f.counts(),[1,3]);for(const table of ['agentci_eval_jobs','agentci_eval_units','agentci_reproduction_dispatch_attempts'])assert.equal((await f.pool.query(`SELECT count(*) FROM ${table}`)).rows[0].count,'0');
}finally{await f.closeAll();}});
