import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {FindingHistoryStore} from '../../packages/storage/finding-history.ts';
import {findingsFromReviewer,deduplicateFindings} from '../../packages/findings/model.ts';
import {buildReviewContext} from '../../packages/reviewers/context.ts';
import {canonical,digest} from '../../packages/review/engine.ts';
import type {FindingReceipt} from '../../packages/findings/lifecycle.ts';
const url=process.env.AGENTCI_TEST_DATABASE_URL;
if(!url)throw Error('Finding history integration requires AGENTCI_TEST_DATABASE_URL; never silently skip');
test('PostgreSQL finding history authenticates proposals, fences concurrent writes and reconstructs immutable events',async()=>{
 const schema=`finding_${randomUUID().replaceAll('-','')}`,admin=new Pool({connectionString:url});
 await admin.query(`CREATE SCHEMA ${schema}`);
 const pool=new Pool({connectionString:url,options:`-c search_path=${schema}`,connectionTimeoutMillis:5000});
 try{
  const sql=await readFile(new URL('../../deploy/migrations/006_m3_finding_history.sql',import.meta.url),'utf8');
  await pool.query(sql);await pool.query(sql);
  const result=JSON.parse(await readFile(new URL('../../specs/api/fixtures/reviewer-result.json',import.meta.url),'utf8'));
  result.subject.organizationId=randomUUID();result.requestId=randomUUID();
  const docs=[{kind:'source',side:'head',path:'app.ts',content:'fixture',digest:digest('fixture')}];
  result.contextDigest=buildReviewContext(result.subject,docs).digest;
  result.response.structuredOutput={findings:[{category:'security',severity:'high',claim:'Missing authorization',evidence:[{side:'head',path:'app.ts',digest:docs[0]!.digest,startLine:1,endLine:1}]}]};
  result.proposal.output=structuredClone(result.response.structuredOutput);result.responseDigest=digest(canonical(result.response));
  const finding=deduplicateFindings(findingsFromReviewer(result,result.subject,docs),result.subject)[0]!;
  const scope={organizationId:result.subject.organizationId,repository:result.subject.repository};
  let unavailable=false;
  const receipts=new Map<string,FindingReceipt>();
  const readers={async reviewer(id:string){if(unavailable)throw Error('secret');assert.equal(id,result.requestId);return {result,documents:docs};},async receipt(id:string){if(!receipts.has(id))throw Error('secret');return receipts.get(id)!;}};
  const store=new FindingHistoryStore(pool,scope,readers);
  await assert.rejects(store.create({...finding,severity:'critical'},finding.subject,randomUUID()),/finding-history-conflict/);
  assert.deepEqual(await store.get(finding.id,finding.subject),[]);
  const operation=randomUUID();const concurrent=await Promise.allSettled(Array.from({length:4},()=>store.create(finding,finding.subject,operation)));
  assert.ok(concurrent.some(r=>r.status==='fulfilled'));
  for(const r of concurrent)if(r.status==='rejected')assert.match(r.reason.message,/finding-history-conflict/);
  const initial=await store.create(finding,finding.subject,operation);assert.equal(initial.event.finding.state,'deduplicated');
  unavailable=true;assert.deepEqual(await store.create(finding,finding.subject,operation),initial);unavailable=false;
  await assert.rejects(store.create({...finding,severity:'critical'},finding.subject,operation),/finding-history-conflict/);
  const mutations=await Promise.allSettled([store.transition(finding.id,finding.subject,{type:'queue'},1,randomUUID()),store.transition(finding.id,finding.subject,{type:'queue'},1,randomUUID())]);
  assert.equal(mutations.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(mutations.filter(r=>r.status==='rejected').length,1);
  let history=await store.get(finding.id,finding.subject);assert.equal(history.length,2);assert.deepEqual(history[0],initial);
  const queued=history[1]!;assert.deepEqual(await store.transition(finding.id,finding.subject,{type:'queue'},1,queued.event.operationId),queued);
  await assert.rejects(store.transition(finding.id,finding.subject,{type:'queue'},1,randomUUID()),/finding-history-conflict/);
  const receiptId=randomUUID();
  await assert.rejects(store.transition(finding.id,finding.subject,{type:'reproduce',receiptId},2,randomUUID()),/finding-history-unavailable/);
  assert.equal((await store.get(finding.id,finding.subject)).length,2);
  receipts.set(receiptId,{findingId:finding.id,subjectDigest:digest(canonical(finding.subject)),evidenceDigest:digest('retained execution'),assertionDigest:digest('assertion'),actor:'reproduction',outcome:'reproduced',reason:'Synthetic fixture reproduction'});
  const correct=structuredClone(receipts.get(receiptId)!);receipts.set(receiptId,{...correct,findingId:digest('wrong')});
  await assert.rejects(store.transition(finding.id,finding.subject,{type:'reproduce',receiptId},2,randomUUID()),/finding-history-conflict/);
  assert.equal((await store.get(finding.id,finding.subject)).length,2);receipts.set(receiptId,correct);
  const confirmOperation=randomUUID();const confirmed=await store.transition(finding.id,finding.subject,{type:'reproduce',receiptId},2,confirmOperation);
  receipts.clear();assert.deepEqual(await store.transition(finding.id,finding.subject,{type:'reproduce',receiptId},2,confirmOperation),confirmed);
  const recovery=new FindingHistoryStore(pool,scope,readers);history=await recovery.get(finding.id,finding.subject);assert.equal(history.length,3);assert.equal(history[2]!.event.finding.state,'confirmed');assert.deepEqual(history[0],initial);
  const restartedPool=new Pool({connectionString:url,options:`-c search_path=${schema}`});
  try{assert.deepEqual(await new FindingHistoryStore(restartedPool,scope,readers).get(finding.id,finding.subject),history);}finally{await restartedPool.end();}
  await assert.rejects(new FindingHistoryStore(restartedPool,scope,readers).get(finding.id,finding.subject),/finding-history-unavailable/);
  const otherScope={...scope,organizationId:randomUUID()};const other=new FindingHistoryStore(pool,otherScope,readers);
  assert.deepEqual(await other.get(finding.id,{...finding.subject,organizationId:otherScope.organizationId}),[]);
  await assert.rejects(other.get(finding.id,finding.subject),/finding-history-conflict/);
  await assert.rejects(store.get(finding.id,{...finding.subject,headSha:'c'.repeat(40)}),/finding-history-conflict/);
  await assert.rejects(pool.query('UPDATE agentci_finding_events SET digest=$1',[digest('tamper')]),/Immutable finding event/);
  await assert.rejects(pool.query('DELETE FROM agentci_finding_events'),/Immutable finding event/);
  assert.deepEqual(await recovery.get(finding.id,finding.subject),history);
 }finally{await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
});
