import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile,writeFile,rm,mkdtemp,realpath} from 'node:fs/promises';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';import {once} from 'node:events';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {reproductionStagingFixture} from '../helpers/reproduction-staging-fixture.ts';import {Store} from '../../packages/storage/postgres.ts';import {canonical,digest} from '../../packages/review/engine.ts';import {ReproductionDispatchStore} from '../../packages/storage/reproduction-dispatch.ts';import {ReproductionNonExecutionStore} from '../../packages/storage/reproduction-non-execution.ts';import {FindingHistoryStore} from '../../packages/storage/finding-history.ts';
if(!process.env.AGENTCI_TEST_DATABASE_URL)throw Error('Reproduction client acceptance requires real PostgreSQL; never silently skip');
const packageRoot=process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT,sourceRoot=new URL('../../',import.meta.url).pathname,root=packageRoot??sourceRoot;
const probe=resolve(packageRoot?resolve(packageRoot,'../..'):sourceRoot,`agentci-reproduction-client-${randomUUID()}.mjs`);
await writeFile(probe,"export {ModelReviewClient,AgentCIError} from 'agentci/client';export const resolved=import.meta.resolve('agentci/client');\n");let publicClient:any;try{publicClient=await import(pathToFileURL(probe).href);}finally{await rm(probe);}
assert.equal(publicClient.resolved,pathToFileURL(await realpath(resolve(root,'dist/packages/client/index.js'))).href,'must consume production public export without source fallback');
const {ModelReviewClient,AgentCIError}=publicClient,apiFactory=(await import(pathToFileURL(resolve(root,'dist/apps/control/server.js')).href)).createControlApi,controlFactory=(await import(pathToFileURL(resolve(root,'dist/apps/control/model-reviews.js')).href)).createModelReviewControl;

test('compiled public client and executable CLI verify fresh reservation, operator intent, restart and non-execution recovery over real HTTP/PostgreSQL',{timeout:30000},async()=>{
 const f=await reproductionStagingFixture(),servers:any[]=[],dir=await mkdtemp(join(tmpdir(),'real-reproduction-client-'));
 try{
  await new Store(f.pool,f.scope.organizationId,f.scope.repository).ready();for(const name of ['015_m3_reproduction_eval_source','016_m3_reproduction_authority','017_m3_reproduction_dispatch_state','018_m3_reproduction_dispatch_settlement','019_m3_reproduction_dispatch_initialization'])await f.pool.query(await readFile(new URL(`../../deploy/migrations/${name}.sql`,import.meta.url),'utf8'));
  const reserved=await f.store.reserve(f.f.initial.id,f.selector),reference={schemaVersion:'v1alpha1',id:reserved.reproductionId,operationId:reserved.operationId,reviewId:reserved.reviewId,subject:f.f.finding.subject,finding:{id:f.f.finding.id,queuedVersion:reserved.queuedVersion,digest:digest(canonical(f.f.plan.finding))},planDigest:reserved.planDigest,requestDigest:reserved.requestDigest};
  const config={...f.scope,installationId:1,secret:'hook-test-'.repeat(4),evidenceToken:'reader-test-'.repeat(4),operatorToken:'operator-test-'.repeat(4)};
  const start=async()=>{const control=await controlFactory(f.pool,config),s=apiFactory(config,{ready:async()=>{},recordDelivery:async()=>{throw Error();},evidence:async()=>undefined},undefined,control);s.listen(0,'127.0.0.1');await once(s,'listening');servers.push(s);return `http://127.0.0.1:${s.address().port}`;};
  const url=await start(),client=new ModelReviewClient({url,readToken:config.evidenceToken,operatorToken:config.operatorToken,maxAttempts:1}),dispatch=new ReproductionDispatchStore(f.pool,f.scope);
  const queued=await client.reproductionStatus(f.request,reference);assert.equal(queued.dispatch.state,'queued');assert.equal(queued.receipt,null);assert.equal(queued.dispatch.cancelRequested,false);
  const failure=(c:string)=>(e:any)=>e instanceof AgentCIError&&e.code===c;
  await assert.rejects(new ModelReviewClient({url,readToken:'wrong-credential-'.repeat(4),maxAttempts:1}).reproductionStatus(f.request,reference),failure('unauthorized'));
  await assert.rejects(client.cancelReproduction(f.request,{...reference,requestDigest:digest('substituted')}),failure('invalid-response'));assert.equal((await dispatch.get(f.selector.operationId))!.cancellation,null);
  const requestFile=join(dir,'request.json'),referenceFile=join(dir,'reference.json');await writeFile(requestFile,JSON.stringify(f.request));await writeFile(referenceFile,JSON.stringify(reference));const main=resolve(root,'dist/cmd/agentci/main.js'),exec=promisify(execFile),args=['finding','reproduction-status','--request',requestFile,'--reproduction',referenceFile];
  const env={...process.env,AGENTCI_API_URL:url,AGENTCI_EVIDENCE_TOKEN:config.evidenceToken,AGENTCI_OPERATOR_TOKEN:config.operatorToken};
  assert.deepEqual(JSON.parse((await exec(process.execPath,[main,...args],{env})).stdout),queued);
  await assert.rejects(exec(process.execPath,[main,...args.map(a=>a==='reproduction-status'?'cancel-reproduction':a)],{env:{...env,AGENTCI_OPERATOR_TOKEN:undefined}}),(e:any)=>e.code===2&&JSON.parse(e.stderr).error.code==='operator-token-required'&&e.stdout==='');
  const fifo=join(dir,'reference.fifo');await exec('mkfifo',[fifo]);
  for(const command of ['reproduction-status','cancel-reproduction'])await assert.rejects(exec(process.execPath,[main,...args.map(a=>a==='reproduction-status'?command:a===referenceFile?fifo:a)],{env,timeout:2000}),(e:any)=>e.code===2&&!e.killed&&e.stdout===''&&JSON.parse(e.stderr).error.code==='invalid-reproduction-reference-file');
  assert.equal((await dispatch.get(f.selector.operationId))!.cancellation,null,'nonregular reference never records cancellation');
  const cancelled=await exec(process.execPath,[main,...args.map(a=>a==='reproduction-status'?'cancel-reproduction':a)],{env});assert.equal(cancelled.stderr,'');assert.deepEqual(JSON.parse(cancelled.stdout),{schemaVersion:'v1alpha1',id:reference.id,cancelRequested:true});
  const restartedUrl=await start(),restarted=new ModelReviewClient({url:restartedUrl,operatorToken:config.operatorToken,maxAttempts:1});assert.equal((await restarted.reproductionStatus(f.request,reference)).dispatch.cancelRequested,true);assert.deepEqual(await restarted.cancelReproduction(f.request,reference),JSON.parse(cancelled.stdout));assert.equal(await dispatch.claim(),undefined);assert.equal(await dispatch.backfill(),0);
  await f.pool.query('INSERT INTO agentci_reproduction_cancellations(organization_id,repository,id) VALUES($1,$2,$3)',[f.scope.organizationId,f.scope.repository,reference.id]);const proofs=new ReproductionNonExecutionStore(f.pool,f.scope),proof=await proofs.cancelled(reference.id),history=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:async()=>{throw Error();},nonExecution:(id,subject)=>proofs.read(id,subject)}),h=await history.unavailable(f.f.initial.id,f.f.initial.subject,{type:'unavailable',proofId:proof.id},2,proof.id),recovery=new ReproductionDispatchStore(f.pool,f.scope,async()=>({kind:'never-staged',history:h,proof})),claim=await recovery.claim('recovery');assert.ok(claim);await recovery.settle(claim);
  const settled=await restarted.reproductionStatus(f.request,reference);assert.equal(settled.dispatch.state,'settled');assert.equal(settled.receipt,null);assert.deepEqual(settled.nonExecution.value,proof);assert.equal(settled.nonExecution.value.verified,false);assert.deepEqual(await restarted.cancelReproduction(f.request,reference),JSON.parse(cancelled.stdout));assert.deepEqual(await restarted.reproductionStatus(f.request,reference),settled);
  const cliSettled=await exec(process.execPath,[main,...args],{env:{...env,AGENTCI_API_URL:restartedUrl}});assert.deepEqual(JSON.parse(cliSettled.stdout),settled);assert.ok(!cliSettled.stdout.includes(config.operatorToken));
  for(const table of ['agentci_reproduction_dispatch_attempts','agentci_eval_jobs','agentci_eval_units','agentci_reproduction_receipts'])assert.equal((await f.pool.query(`SELECT count(*) FROM ${table}`)).rows[0].count,'0',table+' remains empty before controller execution');
 }finally{for(const s of servers){s.closeAllConnections();await new Promise<void>(r=>s.close(()=>r()));}await rm(dir,{recursive:true,force:true});await f.close();}
});
