import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import {readFile} from 'node:fs/promises';import {once} from 'node:events';import {Pool} from 'pg';import type {Octokit} from '@octokit/rest';
import {Client,Connection} from '@temporalio/client';import {NativeConnection,Worker} from '@temporalio/worker';
import {createReviewerRuntime,validateReviewerRuntime} from '../../packages/runtime/reviewers.ts';
import {validateReviewerProfile} from '../../packages/reviewers/profile.ts';
import {validateModelReviewStatus,validateModelReviewAccepted,validateReviewerProfileList,validateModelReviewCancellation} from '../../packages/reviewers/transport.ts';
import {initializeReviewerController} from '../../apps/worker/reviewer-runtime.ts';
import {dispatchAdmittedReviews} from '../../apps/worker/reviewer-dispatch.ts';
import {createModelReviewControl} from '../../apps/control/model-reviews.ts';
import {createControlApi} from '../../apps/control/server.ts';
const url=process.env.AGENTCI_TEST_DATABASE_URL,address=process.env.AGENTCI_TEST_TEMPORAL_ADDRESS;if(!url||!address)throw Error('Model review API acceptance requires real PostgreSQL and Temporal; never silently skip');
test('real HTTP admissions preserve scope/replay and drive configured Temporal reviews, reads and cancellation',{timeout:60000},async()=>{
 const schema=`http_review_${randomUUID().replaceAll('-','')}`,admin=new Pool({connectionString:url});await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString:url,options:`-c search_path=${schema}`});
 const connection=await Connection.connect({address}),native=await NativeConnection.connect({address}),client=new Client({connection});let worker:Worker|undefined,running:Promise<void>|undefined;const servers:ReturnType<typeof createControlApi>[]=[];
 try{
  for(const name of ['004_m3_model_budget','005_m3_reviewer_results','006_m3_finding_history','008_m3_review_admissions','009_m3_review_dispatch','010_m3_reviewer_profiles','011_m3_review_summaries','012_m3_review_recovery'])await pool.query(await readFile(new URL(`../../deploy/migrations/${name}.sql`,import.meta.url),'utf8'));
  const definition=JSON.parse(await readFile(new URL('../../deploy/reviewers.synthetic.example.json',import.meta.url),'utf8'));definition.profiles[0].budget.id=randomUUID();const runtime=createReviewerRuntime(definition,{}),selected=validateReviewerProfile(runtime.definition.profiles[0]);
  const config={organizationId:randomUUID(),repository:'owner/repo',installationId:123,secret:'webhook-fixture-'.repeat(3),evidenceToken:'evidence-fixture-'.repeat(3),operatorToken:'operator-fixture-'.repeat(3)},baseSha='a'.repeat(40),headSha='b'.repeat(40),treeSha='c'.repeat(40),content='Synthetic repository fixture\n',blobSha=createHash('sha1').update(`blob ${Buffer.byteLength(content)}\0${content}`).digest('hex');let current=headSha,prReads=0,blobReads=0;
  const assertScope=(params:any)=>{assert.equal(params.owner,'owner');assert.equal(params.repo,'repo');};
  const github={pulls:{get:async(params:any)=>{prReads++;assertScope(params);assert.equal(params.pull_number,1);return {data:{state:'open',base:{sha:baseSha},head:{sha:current}}};}},git:{getCommit:async(params:any)=>{assertScope(params);assert.equal(params.commit_sha,headSha);return {data:{sha:headSha,tree:{sha:treeSha}}};},getTree:async(params:any)=>{assertScope(params);return {data:{sha:treeSha,truncated:false,tree:[{type:'blob',mode:'100644',path:'README.md',sha:blobSha,size:Buffer.byteLength(content)}]}};},getBlob:async(params:any)=>{assertScope(params);assert.equal(params.file_sha,blobSha);blobReads++;return {data:{sha:blobSha,encoding:'base64',content:Buffer.from(content).toString('base64')}};}}} as unknown as Octokit;
  const controller=await initializeReviewerController(pool,github,config,runtime);
  const serve=async(enabled:boolean,scope=config)=>{const backend=await createModelReviewControl(pool,scope,enabled?definition:null,enabled?github:undefined),server=createControlApi(scope,{ready:async()=>{},evidence:async()=>undefined,recordDelivery:async()=>'accepted'},undefined,backend);servers.push(server);server.listen(0,'127.0.0.1');await once(server,'listening');const a=server.address();if(!a||typeof a==='string')throw Error();return `http://127.0.0.1:${a.port}`;};
  const origin=await serve(true),headers={authorization:`Bearer ${config.operatorToken}`},readHeaders={authorization:`Bearer ${config.evidenceToken}`};
  const id=randomUUID(),request={schemaVersion:'v1alpha1',id,subject:{organizationId:config.organizationId,repository:config.repository,pullRequest:1,baseSha,headSha},profile:{id:selected.profile.id,revision:selected.revision},mode:'synthetic'};
  const post=(body:unknown,base=origin)=>fetch(base+'/v1/model-reviews',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(body)});
  const get=async(reviewId=id,base=origin)=>{const r=await fetch(base+'/v1/model-reviews/'+reviewId,{headers:readHeaders});assert.equal(r.status,200);return validateModelReviewStatus(await r.json());};
  const profiles=await fetch(origin+'/v1/reviewer-profiles',{headers:readHeaders});assert.equal(profiles.status,200);assert.deepEqual(validateReviewerProfileList(await profiles.json()).profiles,[{id:selected.profile.id,revision:selected.revision,mode:'synthetic',revoked:false}]);
  const responses=await Promise.all(Array.from({length:5},()=>post(request)));for(const response of responses){assert.equal(response.status,202);assert.equal(response.headers.get('location'),'/v1/model-reviews/'+id);assert.equal(validateModelReviewAccepted(await response.json()).id,id);}
  assert.equal((await pool.query('SELECT count(*) FROM agentci_review_admission_outbox')).rows[0].count,'1');assert.equal((await get()).execution.state,'queued','Configured authority must not invent a live worker');
  const first=(await get()).admission,priorReads=prReads;current='d'.repeat(40);assert.equal((await post(request)).status,202);assert.equal(prReads,priorReads,'exact authenticated replay does not authorize another execution');
  assert.equal((await post({...request,id:randomUUID()})).status,403);assert.equal((await post({...request,mode:'live'})).status,409);assert.equal((await post({...request,id:randomUUID(),subject:{...request.subject,organizationId:randomUUID()}})).status,404);current=headSha;
  const other=await serve(false,{...config,organizationId:randomUUID()});assert.equal((await fetch(other+'/v1/model-reviews/'+id,{headers:readHeaders})).status,404);
  const taskQueue=`http-review-${randomUUID()}`,workflowsPath=new URL('../../dist/apps/worker/workflows.js',import.meta.url).pathname;
  worker=await Worker.create({connection:native,taskQueue,workflowsPath,activities:controller.activities});running=worker.run();await dispatchAdmittedReviews(controller.dispatch,client,{taskQueue,timeoutMs:45000});
  const state=(await controller.dispatch.get(id))!,handle=client.workflow.getHandle(state.workflowId,state.runId!);
  // Concurrent transport reads must never mix terminal and summary snapshots.
  await Promise.all([handle.result(),...Array.from({length:12},()=>get())]);
  const completed=await get();assert.equal(completed.execution.state,'completed');assert.equal(completed.summary!.summary.coverage.completedRoles,7);assert.equal(completed.summary!.summary.findings.length,0);assert.deepEqual(completed.admission,first);assert.equal(blobReads,1);
  assert.equal((await pool.query('SELECT count(*) FROM agentci_model_attempts')).rows[0].count,'7');
  const restarted=await serve(false);assert.deepEqual(await get(id,restarted),completed);assert.equal((await post({...request,id:randomUUID()},restarted)).status,503);
  const emptyProfiles=await fetch(restarted+'/v1/reviewer-profiles',{headers:headers});assert.deepEqual(await emptyProfiles.json(),{schemaVersion:'v1alpha1',profiles:[]});
  for(let i=0;i<2;i++){const late=await fetch(restarted+'/v1/model-reviews/'+id+'/cancellation',{method:'POST',headers});assert.equal(late.status,202);validateModelReviewCancellation(await late.json());}
  assert.equal((await get(id,restarted)).execution.state,'completed');assert.equal((await get(id,restarted)).execution.terminalDigest,completed.execution.terminalDigest);
  const cancelId=randomUUID();assert.equal((await post({...request,id:cancelId})).status,202);await fetch(origin+'/v1/model-reviews/'+cancelId+'/cancellation',{method:'POST',headers});await dispatchAdmittedReviews(controller.dispatch,client,{taskQueue,timeoutMs:45000});const cancelled=(await controller.dispatch.get(cancelId))!;await assert.rejects(client.workflow.getHandle(cancelled.workflowId,cancelled.runId!).result());assert.equal((await get(cancelId)).execution.state,'cancelled');assert.equal((await get(cancelId)).summary,null);assert.equal((await pool.query('SELECT count(*) FROM agentci_model_attempts')).rows[0].count,'7');
  await controller.profiles.revoke(selected.profile.id,selected.revision);assert.equal((await post({...request,id:randomUUID()})).status,403);assert.equal((await post(request)).status,202);
  const revoked=await fetch(origin+'/v1/reviewer-profiles',{headers:readHeaders});assert.equal((await revoked.json() as any).profiles[0].revoked,true);
  // Control-side authority can load live definitions without model keys or SDK
  // construction. Its scoped GitHub reader is still mandatory; no paid call.
  const external=structuredClone(definition);external.providers=[{kind:'openai',models:[{model:'fixture-only',contextTokens:10000,maxOutputTokens:1000,capabilities:{stream:false,tools:false,structuredOutput:true,developerInstructions:true,extensions:false},temperature:false,topP:false,inputUsdMicrosPerMillion:1000,outputUsdMicrosPerMillion:1000,pricingRevision:'fixture-only'}]}];external.profiles[0].mode='live';for(const role of external.profiles[0].reviewers){role.provider='openai';role.model='fixture-only';role.providerExtensions={};}
  await createModelReviewControl(pool,config,validateReviewerRuntime(external),github);await assert.rejects(createModelReviewControl(pool,config,definition),/authority-unavailable/);
 }finally{for(const server of servers){server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}worker?.shutdown();await running;await native.close();await connection.close();await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
});
