import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {reproductionStagingFixture} from '../helpers/reproduction-staging-fixture.ts';import {Store} from '../../packages/storage/postgres.ts';import {canonical,digest} from '../../packages/review/engine.ts';
import {loadReproductionConfig,type ReproductionOperatorConfig} from '../../packages/findings/reproduction-config.ts';import {ReproductionAuthorityStore,ReproductionAuthorityConflict} from '../../packages/storage/reproduction-authority.ts';
async function fixture(image?:string){const f=await reproductionStagingFixture(image?{image}:{});try{await new Store(f.pool,f.scope.organizationId,f.scope.repository).ready();for(const name of ['015_m3_reproduction_eval_source','016_m3_reproduction_authority'])await f.pool.query(await readFile(new URL(`../../deploy/migrations/${name}.sql`,import.meta.url),'utf8'));
 const config:ReproductionOperatorConfig={schemaVersion:'v1alpha1',...f.scope,revision:1,approvals:[{planId:f.f.plan.id,planDigest:digest(canonical(f.f.plan)),findingId:f.f.initial.id,findingVersion:1,findingDigest:digest(canonical(f.f.initial)),enabled:true,expiresAt:'2100-01-01T00:00:00.000Z'}]};
 const readers={finding:async()=>f.f.initial,plan:async()=>f.f.plan,snapshot:async(_subject:unknown,side:'base'|'head')=>f.f[side]};let permission=true;const store=new ReproductionAuthorityStore(f.pool,f.scope,readers,async()=>permission);return {...f,reservations:f.store,config,readers,store,setPermission:(value:boolean)=>{permission=value;}};
 }catch(e){await f.close();throw e;}}
test('operator references bind exact trusted inputs and forbid executable/caller configuration',async()=>{const f=await fixture();try{
 const loaded=await loadReproductionConfig(f.config,f.readers);assert.equal(loaded.identity.digest,digest(canonical(f.config)));assert.equal(loaded.registry.select(f.selector,f.f.initial).plan.id,f.f.plan.id);
 for(const change of [(v:any)=>{v.command=['node','evil'];},(v:any)=>{v.approvals[0].image='evil';},(v:any)=>{v.approvals[0].planDigest=digest('other');},(v:any)=>{v.approvals[0].findingVersion=2;},(v:any)=>{v.approvals[0].expiresAt='invalid';}]){const config=structuredClone(f.config);change(config);await assert.rejects(loadReproductionConfig(config,f.readers),/invalid-reproduction/);}
 await assert.rejects(loadReproductionConfig(f.config,{...f.readers,snapshot:async(s,side)=>({...f.f[side],files:{...f.f[side].files,'app.mjs':'substituted'}})}),/invalid-reproduction/);
 }finally{await f.close();}});
test('config apply CAS races, replay, permanent revocation and stale startup fail closed',async()=>{const f=await fixture();try{
 const first=await f.store.apply(f.config,null);assert.deepEqual(await f.store.apply(f.config,null),first);assert.deepEqual(await f.store.read(first),f.config);
 const variants=[{...f.config,revision:2,approvals:[]},{...f.config,revision:2,approvals:[{...f.config.approvals[0]!,enabled:false}]}];const results=await Promise.allSettled(variants.map(c=>f.store.apply(c,first)));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected'&&r.reason instanceof ReproductionAuthorityConflict).length,1);const current=(results.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<typeof first>).value;
 await assert.rejects(f.store.read(first),ReproductionAuthorityConflict);await assert.rejects(f.store.apply(f.config,null),ReproductionAuthorityConflict);await assert.rejects(f.store.apply({...f.config,revision:3},current),ReproductionAuthorityConflict);let invoked=false;await assert.rejects(f.store.withApproval(current,f.f.plan.id,async()=>{invoked=true;}),ReproductionAuthorityConflict);assert.equal(invoked,false);assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_config_versions')).rows[0].count,'2');assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_revocations')).rows[0].count,'1');
 }finally{await f.close();}});
test('revocation serializes after an in-flight permitted SQL effect and permission loss rolls back',async()=>{const f=await fixture();try{
 await f.pool.query('CREATE TABLE fixture_effects(id integer PRIMARY KEY)');const identity=await f.store.apply(f.config,null);let entered!:()=>void,release!:()=>void;const atEffect=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);
 const pending=f.store.withApproval(identity,f.f.plan.id,async c=>{await c.query('INSERT INTO fixture_effects VALUES(1)');entered();await gate;});await atEffect;
 const revoke=f.store.apply({...f.config,revision:2,approvals:[]},identity);f.setPermission(false);release();await assert.rejects(pending,ReproductionAuthorityConflict);await revoke;assert.equal((await f.pool.query('SELECT count(*) FROM fixture_effects')).rows[0].count,'0');
 }finally{await f.close();}});
test('expired approval cannot reach a side effect even under matching config identity',async()=>{const f=await fixture();try{
 const config={...f.config,approvals:[{...f.config.approvals[0]!,expiresAt:'2000-01-01T00:00:00.000Z'}]},identity=await f.store.apply(config,null);let invoked=false;await assert.rejects(f.store.withApproval(identity,f.f.plan.id,async()=>{invoked=true;}),ReproductionAuthorityConflict);assert.equal(invoked,false);
 }finally{await f.close();}});
import {randomUUID} from 'node:crypto';import {ReproductionNonExecutionStore} from '../../packages/storage/reproduction-non-execution.ts';import {FindingHistoryStore} from '../../packages/storage/finding-history.ts';import {ReproductionEvalStore,ReproductionEvalInputLimit} from '../../packages/storage/reproduction-evals.ts';import {EvalStore} from '../../packages/storage/evals.ts';import {FindingReproductionStore} from '../../packages/storage/finding-reproduction.ts';import {compileFindingReproduction} from '../../packages/findings/reproduction.ts';import {createReproductionApprovalRegistry} from '../../packages/findings/approval-registry.ts';import {ReproductionReservations} from '../../packages/storage/reproduction-reservations.ts';import {validateFindingHistoryRecord} from '../../packages/findings/history.ts';import {executeStoredUnit} from '../../apps/eval-worker/unit.ts';
function stores(f:Awaited<ReturnType<typeof fixture>>){const proofs=new ReproductionNonExecutionStore(f.pool,f.scope),evals=new EvalStore(f.pool,f.scope.organizationId,f.scope.repository),staging=new ReproductionEvalStore(f.pool,f.scope,f.registry);let reproduction:FindingReproductionStore;const history=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:(id,subject)=>reproduction.readReceipt(id,subject),nonExecution:(id,subject)=>proofs.read(id,subject)});reproduction=new FindingReproductionStore(f.pool,f.scope,history,evals,{approvedPlan:async()=>f.f.plan},staging);return {proofs,evals,staging,history,reproduction};}
test('never-staged cancellation has a distinct proof, mixed-version history and fresh approved retry',async()=>{const f=await fixture();try{
 await f.reservations.reserve(f.f.initial.id,f.selector);const s=stores(f);await s.reproduction.cancel(f.f.plan.id);const proof=await s.proofs.cancelled(f.f.plan.id);assert.equal(proof.executionReceipt,null);assert.equal(proof.verified,false);assert.equal(proof.status,'cancelled');assert.deepEqual(await s.proofs.cancelled(f.f.plan.id),proof);
 const result=await s.history.unavailable(f.f.initial.id,f.f.initial.subject,{type:'unavailable',proofId:proof.id},2,proof.id);assert.equal(result.event.schemaVersion,'v1alpha2');assert.equal(result.event.receipt,null);assert.equal(result.event.finding.state,'unconfirmed');assert.equal(result.event.finding.disposition!.outcome,'error');await assert.rejects(s.reproduction.readReceipt(f.f.plan.id,f.f.initial.subject));await assert.rejects(s.staging.stage(f.f.plan.id,f.f.base,f.f.head));
 assert.deepEqual(await s.history.unavailable(f.f.initial.id,f.f.initial.subject,{type:'unavailable',proofId:proof.id},2,proof.id),result);const chain=await s.history.get(f.f.initial.id,f.f.initial.subject);assert.deepEqual(chain.map(r=>r.event.schemaVersion),['v1alpha1','v1alpha1','v1alpha2']);
 for(const mutate of [(r:any)=>{r.event.schemaVersion='v1alpha3';},(r:any)=>{r.event.schemaVersion='v1alpha1';},(r:any)=>{r.event.nonExecution.organizationId=randomUUID();},(r:any)=>{r.event.nonExecution.queuedVersion=1;},(r:any)=>{r.event.receipt={};}]){const altered=structuredClone(result);mutate(altered);altered.digest=digest(canonical(altered.event));assert.throws(()=>validateFindingHistoryRecord(altered,f.f.initial.subject));}
 const current=result.event.finding,queued={...current,version:4,state:'reproduction-pending' as const,disposition:null},approval={...f.f.approval,id:randomUUID(),findingDigest:digest(canonical(queued))},plan=compileFindingReproduction(queued,approval,f.f.base,f.f.head,f.f.policy,f.f.limits),registry=await createReproductionApprovalRegistry([{current,plan,base:f.f.base,head:f.f.head}]);
 const reservation=new ReproductionReservations(f.pool,f.scope,registry),request={...f.selector,operationId:randomUUID(),expectedVersion:3,approvalId:plan.id,approvalDigest:digest(canonical(plan))};await reservation.reserve(current.id,request);const staged=await new ReproductionEvalStore(f.pool,f.scope,registry).stage(plan.id,f.f.base,f.f.head);assert.ok(staged.unitId);assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_receipts')).rows[0].count,'0');assert.equal((await s.history.get(current.id,current.subject)).at(-1)!.event.finding.state,'reproduction-pending');
 }finally{await f.close();}});
test('permanent input-limit proof refuses arbitrary errors and cannot race into a staged job',async()=>{const f=await fixture();try{
 await f.reservations.reserve(f.f.initial.id,f.selector);const s=stores(f);await assert.rejects(s.proofs.inputLimit(f.f.plan.id,Error('caller claims input-limit')),/conflict/);await assert.rejects(s.proofs.cancelled(f.f.plan.id),/unavailable/);const proof=await s.proofs.inputLimit(f.f.plan.id,new ReproductionEvalInputLimit());assert.equal(proof.status,'unavailable');await assert.rejects(s.staging.stage(f.f.plan.id,f.f.base,f.f.head));assert.equal((await f.pool.query('SELECT count(*) FROM agentci_eval_jobs')).rows[0].count,'0');await s.history.unavailable(f.f.initial.id,f.f.initial.subject,{type:'unavailable',proofId:proof.id},2,proof.id);assert.equal((await s.history.get(f.f.initial.id,f.f.initial.subject)).at(-1)!.event.finding.state,'unconfirmed');
 }finally{await f.close();}});
test('staging and non-execution proof race has one winner and cannot overwrite completed execution evidence',async()=>{
 const image=process.env.AGENTCI_TEST_RUNNER_IMAGE;if(!image)throw Error('Authority execution acceptance requires immutable runner image');
 const f=await fixture(image);try{await f.reservations.reserve(f.f.initial.id,f.selector);const s=stores(f);const race=await Promise.allSettled([s.staging.stage(f.f.plan.id,f.f.base,f.f.head),s.proofs.inputLimit(f.f.plan.id,new ReproductionEvalInputLimit())]);assert.equal(race.filter(r=>r.status==='fulfilled').length,1);const jobs=Number((await f.pool.query('SELECT count(*) FROM agentci_eval_jobs')).rows[0].count),proofs=Number((await f.pool.query('SELECT count(*) FROM agentci_reproduction_non_execution')).rows[0].count);assert.equal(jobs+proofs,1);
 }finally{await f.close();}
 const completed=await fixture(image);try{await completed.reservations.reserve(completed.f.initial.id,completed.selector);const s=stores(completed),staged=await s.reproduction.stage(completed.f.plan.id,completed.f.base,completed.f.head);await executeStoredUnit(s.evals,staged.unitId,{image});await s.reproduction.finalize(completed.f.plan.id);const before=await s.reproduction.readReceipt(completed.f.plan.id,completed.f.initial.subject);await assert.rejects(s.proofs.inputLimit(completed.f.plan.id,new ReproductionEvalInputLimit()));await s.reproduction.cancel(completed.f.plan.id);await assert.rejects(s.proofs.cancelled(completed.f.plan.id));assert.deepEqual(await s.reproduction.readReceipt(completed.f.plan.id,completed.f.initial.subject),before);assert.equal((await completed.pool.query('SELECT count(*) FROM agentci_reproduction_non_execution')).rows[0].count,'0');
 }finally{await completed.close();}
});
test('permission callback timeout is bounded and aborts; expiry recheck rolls back a pending effect',async()=>{
 const f=await fixture();try{
  const identity=await f.store.apply(f.config,null);let aborted=false;const hanging=new ReproductionAuthorityStore(f.pool,f.scope,f.readers,async(_ref,signal)=>{signal.addEventListener('abort',()=>{aborted=true;});return new Promise(()=>{});});const started=Date.now();let invoked=false;await assert.rejects(hanging.withApproval(identity,f.f.plan.id,async()=>{invoked=true;}),ReproductionAuthorityConflict);assert.ok(Date.now()-started<8000);assert.equal(aborted,true);assert.equal(invoked,false);assert.deepEqual(await f.store.read(identity),f.config);
 }finally{await f.close();}
 const expiry=await fixture();try{await expiry.pool.query('CREATE TABLE fixture_effects(id integer)');const config={...expiry.config,approvals:[{...expiry.config.approvals[0]!,expiresAt:new Date(Date.now()+1000).toISOString()}]},identity=await expiry.store.apply(config,null);let invoked=false;await assert.rejects(expiry.store.withApproval(identity,expiry.f.plan.id,async c=>{invoked=true;await c.query('INSERT INTO fixture_effects VALUES(1)');await c.query('SELECT pg_sleep(1.1)');}),ReproductionAuthorityConflict);assert.equal(invoked,true);assert.equal((await expiry.pool.query('SELECT count(*) FROM fixture_effects')).rows[0].count,'0');
 }finally{await expiry.close();}
});
test('controller proof reads reject rehashed retained scope/operation/version substitutions',async()=>{const f=await fixture();try{
 await f.reservations.reserve(f.f.initial.id,f.selector);const s=stores(f);await s.reproduction.cancel(f.f.plan.id);const proof=await s.proofs.cancelled(f.f.plan.id);
 for(const patch of [{organizationId:randomUUID()},{reservationOperationId:randomUUID()},{queuedVersion:3},{queuedFindingDigest:digest('other')},{planDigest:digest('other')}]){const changed={...proof,...patch};await f.pool.query('ALTER TABLE agentci_reproduction_non_execution DISABLE TRIGGER reproduction_non_execution_immutable');await f.pool.query('UPDATE agentci_reproduction_non_execution SET proof=$1,digest=$2',[changed,digest(canonical(changed))]);await f.pool.query('ALTER TABLE agentci_reproduction_non_execution ENABLE TRIGGER reproduction_non_execution_immutable');await assert.rejects(s.proofs.read(proof.id,f.f.initial.subject));}
 }finally{await f.close();}});
test('approval expiring during the final permission callback rolls back before commit',async()=>{const f=await fixture();try{
 await f.pool.query('CREATE TABLE fixture_effects(id integer)');const config={...f.config,approvals:[{...f.config.approvals[0]!,expiresAt:new Date(Date.now()+1000).toISOString()}]};let checks=0;const store=new ReproductionAuthorityStore(f.pool,f.scope,f.readers,async()=>{if(++checks===2)await new Promise(r=>setTimeout(r,1100));return true;}),identity=await store.apply(config,null);let invoked=false;
 await assert.rejects(store.withApproval(identity,f.f.plan.id,async c=>{invoked=true;await c.query('INSERT INTO fixture_effects VALUES(1)');}),ReproductionAuthorityConflict);assert.equal(invoked,true);assert.equal(checks,2);assert.equal((await f.pool.query('SELECT count(*) FROM fixture_effects')).rows[0].count,'0');
 }finally{await f.close();}});
test('transaction deadline destroys queued SQL before a late callback can autocommit',async()=>{const f=await fixture();try{
 await f.pool.query('CREATE TABLE fixture_effects(id integer)');const identity=await f.store.apply(f.config,null);let late!:Promise<unknown>,lateError:unknown;
 await assert.rejects(f.store.withApproval(identity,f.f.plan.id,async c=>{
  await new Promise(r=>setTimeout(r,11000));
  // The active query crosses the12s deadline. Even if a callback catches that
  // cancellation and tries another SQL statement, its client is already dead.
  late=(async()=>{try{await c.query('SELECT pg_sleep(2)');}catch{}try{await c.query('INSERT INTO fixture_effects VALUES(1)');}catch(e){lateError=e;}})();await late;
 }),ReproductionAuthorityConflict);
 await late;assert.ok(lateError,'late SQL must reject on the destroyed client');assert.equal((await f.pool.query('SELECT count(*) FROM fixture_effects')).rows[0].count,'0');assert.deepEqual(await f.store.read(identity),f.config);
 }finally{await f.close();}});
