import test from 'node:test';import assert from 'node:assert/strict';
import {Client,Connection} from '@temporalio/client';import {NativeConnection,Worker} from '@temporalio/worker';
import {reproductionConsumerFixture} from '../helpers/reproduction-consumer-fixture.ts';import {createEvalActivities} from '../../apps/eval-worker/activities.ts';import {dispatchAdmittedReproductions} from '../../apps/worker/reproduction-consumer-dispatch.ts';import {reconcileAdmittedReproductions} from '../../apps/worker/reproduction-consumer-recovery.ts';
const address=process.env.AGENTCI_TEST_TEMPORAL_ADDRESS;if(!address||!process.env.AGENTCI_TEST_DATABASE_URL||!process.env.AGENTCI_TEST_RUNNER_IMAGE)throw Error('Physical consumer acceptance requires PostgreSQL, Temporal and immutable Docker runner');
for(const scenario of ['positive','negative','error'] as const)test(`real consumer ${scenario} retains actual isolated execution receipt and settlement`,{timeout:90000},async()=>{
 const script=scenario==='positive'?undefined:scenario==='negative'?"import{writeFileSync}from'node:fs';writeFileSync('repro.json',JSON.stringify({schemaVersion:'v1alpha1',results:[{scenario:'namespace-bypass',status:'failed'}]}));process.exitCode=1;":"process.exit(7);";
 const f=await reproductionConsumerFixture(script),connection=await Connection.connect({address}),native=await NativeConnection.connect({address}),client=new Client({connection});const workers:Worker[]=[],runs:Promise<void>[]=[];
 try{
  const evaluator=await Worker.create({connection:native,taskQueue:f.evalTaskQueue,workflowsPath:new URL('../../dist/apps/eval-worker/workflows.js',import.meta.url).pathname,activities:createEvalActivities(f.workerStore,()=>({image:f.image}),{maintenanceMs:250,leaseSeconds:3}),maxHeartbeatThrottleInterval:'100 milliseconds'});
  const controller=await Worker.create({connection:native,taskQueue:f.taskQueue,workflowsPath:new URL('../../dist/apps/worker/workflows.js',import.meta.url).pathname,activities:f.runtime.activities});workers.push(evaluator,controller);runs.push(evaluator.run(),controller.run());
  await dispatchAdmittedReproductions(f.dispatch,client,{taskQueue:f.taskQueue,evalTaskQueue:f.evalTaskQueue,config:f.expected,timeoutMs:60000});const retained=(await f.dispatch.get(f.selector.operationId))!;
  assert.equal(await client.workflow.getHandle(retained.workflowId,retained.runId!).result(),f.selector.operationId);
  await reconcileAdmittedReproductions(f.dispatch,client,f.runtime.activities,{markRuntimeQuiescent:f.runtime.markRuntimeQuiescent,settle:entry=>f.dispatch.settle(entry).then(()=>{})});
  const receipt=await f.reproduction.readReceipt(f.f.plan.id,f.f.initial.subject),latest=(await f.history.get(f.f.initial.id,f.f.initial.subject)).at(-1)!;
  assert.equal(receipt.outcome,scenario==='positive'?'reproduced':scenario==='negative'?'not-reproduced':'error');assert.equal(latest.event.finding.state,scenario==='positive'?'confirmed':'unconfirmed');assert.ok((await f.dispatch.get(f.selector.operationId))!.settlement);
  assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reviews')).rows[0].count,'0');assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_receipts')).rows[0].count,'1');assert.equal((await f.pool.query('SELECT count(*) FROM agentci_eval_jobs')).rows[0].count,'1');
  const before=JSON.stringify(receipt);await f.runtime.activities.finalizeAdmittedReproduction(f.selector.operationId,retained.attempt!.token);assert.equal(JSON.stringify(await f.reproduction.readReceipt(f.f.plan.id,f.f.initial.subject)),before);
 }finally{const record=await f.dispatch.get(f.selector.operationId);if(record)try{await client.workflow.getHandle(record.workflowId).terminate('Owned fixture cleanup');}catch{}for(const w of workers)w.shutdown();await Promise.all(runs);await native.close();await connection.close();await f.dispose();}
});

test('SIGKILL isolated evaluator recovers retained checkpoint in the same parent and child runs',{timeout:100000},async()=>{
 const {fork,execFile}=await import('node:child_process');const {once}=await import('node:events');const {promisify}=await import('node:util');const docker=promisify(execFile);
 const f=await reproductionConsumerFixture(),connection=await Connection.connect({address}),native=await NativeConnection.connect({address}),client=new Client({connection});const children:import('node:child_process').ChildProcess[]=[];
 const launch=(phase:'pause'|'recover')=>{
  const child=fork(new URL('./fixtures/reproduction-isolated-worker.ts',import.meta.url),[f.schema,f.scope.organizationId,f.scope.repository,f.evalTaskQueue,phase],{execArgv:['--import','tsx'],env:{PATH:process.env.PATH,HOME:process.env.HOME,PGUSER:undefined,PGPASSWORD:undefined,AGENTCI_FIXTURE_EVAL_DATABASE_URL:f.workerDatabaseUrl,AGENTCI_TEST_TEMPORAL_ADDRESS:address,AGENTCI_TEST_RUNNER_IMAGE:f.image},stdio:['ignore','pipe','pipe','ipc']});children.push(child);let output='';const events=new Map<string,any>();child.stdout!.on('data',v=>{output=(output+v).slice(-8000);});child.stderr!.on('data',v=>{output=(output+v).slice(-8000);});child.on('message',(value:any)=>events.set(value.event,value));
  const event=(name:string)=>new Promise<any>((resolve,reject)=>{if(events.has(name)){resolve(events.get(name));return;}const timer=setTimeout(()=>{cleanup();reject(Error(`Owned evaluator missing ${name}: ${output}`));},20000);const message=(v:any)=>{if(v.event===name){cleanup();resolve(v);}},exit=()=>{cleanup();reject(Error(`Owned evaluator exited before ${name}: ${output}`));},cleanup=()=>{clearTimeout(timer);child.off('message',message);child.off('exit',exit);};child.on('message',message);child.once('exit',exit);});return {child,event};
 };
 const controller=await Worker.create({connection:native,taskQueue:f.taskQueue,workflowsPath:new URL('../../dist/apps/worker/workflows.js',import.meta.url).pathname,activities:f.runtime.activities}),running=controller.run();
 try{
  const original=launch('pause');await original.event('ready');await dispatchAdmittedReproductions(f.dispatch,client,{taskQueue:f.taskQueue,evalTaskQueue:f.evalTaskQueue,config:f.expected,timeoutMs:80000});const record=(await f.dispatch.get(f.selector.operationId))!;
  const checkpoint=await original.event('checkpoint'),inspection=await f.runtime.activities.inspectAdmittedReproduction(record.operationId,record.attempt!.token);assert.equal(checkpoint.unitId,inspection.unitIds[0]!.unitId);const childBefore=await client.workflow.getHandle(inspection.unitIds[0]!.unitWorkflowId).describe();
  const retained=(await f.pool.query('SELECT digest FROM agentci_eval_trials WHERE unit_id=$1',[checkpoint.unitId])).rows;assert.equal(retained.length,1);const exited=once(original.child,'exit');assert.ok(original.child.kill('SIGKILL'));assert.deepEqual(await exited,[null,'SIGKILL']);
  const replacement=launch('recover');await replacement.event('ready');assert.equal(await client.workflow.getHandle(record.workflowId,record.runId!).result(),record.operationId);
  await reconcileAdmittedReproductions(f.dispatch,client,f.runtime.activities,{markRuntimeQuiescent:f.runtime.markRuntimeQuiescent,settle:entry=>f.dispatch.settle(entry).then(()=>{})});
  assert.deepEqual((await f.pool.query('SELECT digest FROM agentci_eval_trials WHERE unit_id=$1',[checkpoint.unitId])).rows,retained);assert.equal((await client.workflow.getHandle(inspection.unitIds[0]!.unitWorkflowId).describe()).runId,childBefore.runId);assert.equal((await f.dispatch.get(record.operationId))!.runId,record.runId);assert.equal((await f.reproduction.readReceipt(f.f.plan.id,f.f.initial.subject)).outcome,'reproduced');assert.ok((await f.dispatch.get(record.operationId))!.settlement);
  const remaining=await docker('docker',['ps','--all','--quiet','--filter',`label=agentci.eval.unit=${checkpoint.unitId}`]);assert.equal(remaining.stdout.trim(),'');console.log('isolated-restart-evidence',JSON.stringify({parentRunId:record.runId,childRunId:childBefore.runId,unitId:checkpoint.unitId,trialDigest:retained[0].digest,signal:'SIGKILL',ownedContainers:0}));
  const finished=once(replacement.child,'exit');replacement.child.send('shutdown');await finished;
 }finally{for(const child of children)if(child.exitCode===null&&child.signalCode===null){const exit=once(child,'exit');child.kill('SIGKILL');await exit;}const record=await f.dispatch.get(f.selector.operationId);if(record)try{await client.workflow.getHandle(record.workflowId).terminate('Owned fixture cleanup');}catch{}controller.shutdown();await running;await native.close();await connection.close();await f.dispose();}
});

for(const mode of ['parent-terminated','permission-lost'] as const)test(`${mode} with an active isolated container recovers owned cleanup`,{timeout:90000},async()=>{
 const {execFile}=await import('node:child_process'),{promisify}=await import('node:util'),docker=promisify(execFile);
 const f=await reproductionConsumerFixture("await new Promise(r=>setTimeout(r,4500));process.exit(7);"),connection=await Connection.connect({address}),native=await NativeConnection.connect({address}),client=new Client({connection});
 const evaluator=await Worker.create({connection:native,taskQueue:f.evalTaskQueue,workflowsPath:new URL('../../dist/apps/eval-worker/workflows.js',import.meta.url).pathname,activities:createEvalActivities(f.workerStore,()=>({image:f.image}),{maintenanceMs:250,leaseSeconds:3}),maxHeartbeatThrottleInterval:'100 milliseconds'}),controller=await Worker.create({connection:native,taskQueue:f.taskQueue,workflowsPath:new URL('../../dist/apps/worker/workflows.js',import.meta.url).pathname,activities:f.runtime.activities});
 const runs=[evaluator.run(),controller.run()];
 try{
  await dispatchAdmittedReproductions(f.dispatch,client,{taskQueue:f.taskQueue,evalTaskQueue:f.evalTaskQueue,config:f.expected,timeoutMs:60000});const record=(await f.dispatch.get(f.selector.operationId))!;
  let unitId:string|undefined;const deadline=Date.now()+10000;
  while(Date.now()<deadline){const inspection=await f.runtime.activities.inspectAdmittedReproduction(record.operationId,record.attempt!.token);unitId=inspection.unitIds[0]?.unitId;if(unitId&&(await docker('docker',['ps','--quiet','--filter',`label=agentci.eval.unit=${unitId}`])).stdout.trim())break;await new Promise(r=>setTimeout(r,50));}
  assert.ok(unitId);assert.ok((await docker('docker',['ps','--quiet','--filter',`label=agentci.eval.unit=${unitId}`])).stdout.trim(),'must observe real running owned container before parent termination');
  if(mode==='parent-terminated'){await client.workflow.getHandle(record.workflowId,record.runId!).terminate('Owned physical recovery acceptance');const config=await f.authority.read(f.expected);await f.authority.apply({...config,revision:2,approvals:config.approvals.map(a=>({...a,enabled:false}))},f.expected);}f.setAllowed(false);
  let retryCount=0;const recoveryDeadline=Date.now()+40000;
  while(Date.now()<recoveryDeadline){try{await reconcileAdmittedReproductions(f.dispatch,client,f.runtime.activities,{markRuntimeQuiescent:f.runtime.markRuntimeQuiescent,settle:entry=>f.dispatch.settle(entry).then(()=>{})});}catch(error){assert.match(String(error),/reproduction-recovery-unavailable/);retryCount++;}if((await f.dispatch.get(record.operationId))!.settlement)break;await new Promise(r=>setTimeout(r,200));}
  assert.ok((await f.dispatch.get(record.operationId))!.settlement,'settlement requires actual terminal and cleanup evidence');assert.equal((await f.reproduction.readReceipt(f.f.plan.id,f.f.initial.subject)).outcome,'error');assert.equal((await client.workflow.getHandle(record.workflowId,record.runId!).describe()).status.name,mode==='parent-terminated'?'TERMINATED':'CANCELLED');if(mode==='permission-lost')assert.equal((await f.dispatch.get(record.operationId))!.cancellation!.cause,'permission-denied');
  const inspection=await f.runtime.activities.inspectAdmittedReproduction(record.operationId,record.attempt!.token),cleanup=await client.workflow.getHandle(inspection.unitIds[0]!.cleanupWorkflowId).describe();assert.equal(cleanup.status.name,'COMPLETED');assert.equal(await client.workflow.getHandle(cleanup.workflowId,cleanup.runId).result(),unitId);
  assert.equal((await docker('docker',['ps','--all','--quiet','--filter',`label=agentci.eval.unit=${unitId}`])).stdout.trim(),'');console.log('isolated-parent-termination-evidence',JSON.stringify({parentRunId:record.runId,cleanupRunId:cleanup.runId,unitId,mode,revokedRevision:mode==='parent-terminated'?2:null,retryCount,ownedContainers:0}));
 }finally{const record=await f.dispatch.get(f.selector.operationId);if(record)try{await client.workflow.getHandle(record.workflowId).terminate('Owned fixture cleanup');}catch{}controller.shutdown();evaluator.shutdown();await Promise.all(runs);await native.close();await connection.close();await f.dispose();}
});
