import {ReproductionNonExecutionStore} from '../../packages/storage/reproduction-non-execution.ts';
import {FindingHistoryStore} from '../../packages/storage/finding-history.ts';
import {EvalStore} from '../../packages/storage/evals.ts';
import {ReproductionEvalStore} from '../../packages/storage/reproduction-evals.ts';
import {FindingReproductionStore} from '../../packages/storage/finding-reproduction.ts';
import type {DispatchSettlementEvidence,DispatchSettlementReader} from '../../packages/storage/reproduction-dispatch.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';
import {reproductionStagingFixture} from '../helpers/reproduction-staging-fixture.ts';import {Store} from '../../packages/storage/postgres.ts';import {canonical,digest} from '../../packages/review/engine.ts';import {ReproductionAuthorityStore} from '../../packages/storage/reproduction-authority.ts';import {ReproductionDispatchStore,ReproductionDispatchConflict,ReproductionDispatchLeaseLost} from '../../packages/storage/reproduction-dispatch.ts';
async function fixture(){const f=await reproductionStagingFixture();try{await new Store(f.pool,f.scope.organizationId,f.scope.repository).ready();for(const n of ['015_m3_reproduction_eval_source','016_m3_reproduction_authority'])await f.pool.query(await readFile(new URL(`../../deploy/migrations/${n}.sql`,import.meta.url),'utf8'));await f.store.reserve(f.f.initial.id,f.selector);
 const readers={finding:async()=>f.f.initial,plan:async()=>f.f.plan,snapshot:async(_s:unknown,side:'base'|'head')=>f.f[side]};const authority=new ReproductionAuthorityStore(f.pool,f.scope,readers,async()=>true);const config=await authority.apply({schemaVersion:'v1alpha1',...f.scope,revision:1,approvals:[{planId:f.f.plan.id,planDigest:digest(canonical(f.f.plan)),findingId:f.f.initial.id,findingVersion:1,findingDigest:digest(canonical(f.f.initial)),enabled:true,expiresAt:'2100-01-01T00:00:00.000Z'}]},null);
 const migration=await readFile(new URL('../../deploy/migrations/017_m3_reproduction_dispatch_state.sql',import.meta.url),'utf8');await f.pool.query(migration);await f.pool.query(migration);const dispatch=new ReproductionDispatchStore(f.pool,f.scope);await f.pool.query(await readFile(new URL('../../deploy/migrations/018_m3_reproduction_dispatch_settlement.sql',import.meta.url),'utf8'));await dispatch.ready();return {...f,dispatch,migration,authority,options:{taskQueue:'reproduction-controller',evalTaskQueue:'reproduction-eval',config}};
 }catch(e){await f.close();throw e;}}
async function bound(f:Awaited<ReturnType<typeof fixture>>){const claim=await f.dispatch.claim();assert.ok(claim);return f.dispatch.bind(claim,f.options);}

test('new lease adopts exact retained prior attempt after ambiguous old start',async()=>{const f=await fixture();try{const old=await bound(f);await f.dispatch.release(old,0);const config=await f.authority.read(f.options.config);const next=await f.authority.apply({...config,revision:2},f.options.config);const claimed=await f.dispatch.claim();assert.ok(claimed);const fresh=await f.dispatch.bind(claimed,{...f.options,config:next});const runId=randomUUID();const adopted=await f.dispatch.adoptObservedRun(fresh,{attemptToken:old.attempt!.token,runId});assert.equal(adopted.runId,runId);assert.deepEqual(adopted.attempt,old.attempt);assert.deepEqual(await f.dispatch.adoptObservedRun(fresh,{attemptToken:old.attempt!.token,runId}),adopted);await assert.rejects(f.dispatch.adoptObservedRun(fresh,{attemptToken:fresh.attempt!.token,runId}),ReproductionDispatchConflict);await assert.rejects(f.dispatch.adoptObservedRun(fresh,{attemptToken:old.attempt!.token,runId:randomUUID()}),ReproductionDispatchConflict);}finally{await f.close();}});
test('old attempt adoption rejects absent, wrong-scope, stale CAS and expired owners',async()=>{const f=await fixture(),other=await fixture();try{const old=await bound(f),foreign=await bound(other);await f.dispatch.release(old,0);const fresh=await f.dispatch.claim();assert.ok(fresh);for(const token of [randomUUID(),foreign.attempt!.token])await assert.rejects(f.dispatch.adoptObservedRun(fresh,{attemptToken:token,runId:randomUUID()}),ReproductionDispatchConflict);await assert.rejects(f.dispatch.adoptObservedRun({...fresh,attempt:null},{attemptToken:old.attempt!.token,runId:randomUUID()}),ReproductionDispatchConflict);await assert.rejects(f.dispatch.adoptObservedRun(old,{attemptToken:old.attempt!.token,runId:randomUUID()}),ReproductionDispatchLeaseLost);await f.pool.query("UPDATE agentci_reproduction_dispatch_state SET lease_until=clock_timestamp()-interval '1 second'");await assert.rejects(f.dispatch.adoptObservedRun(fresh,{attemptToken:old.attempt!.token,runId:randomUUID()}),ReproductionDispatchLeaseLost);assert.equal((await f.dispatch.get(old.operationId))!.runId,null);}finally{await f.close();await other.close();}});
test('competing observed runs cannot replace acknowledged identity; cancellation intent survives adoption',async()=>{const f=await fixture();try{const c=await bound(f);await f.dispatch.requestCancellation(c.operationId,'superseded');const results=await Promise.allSettled([f.dispatch.adoptObservedRun(c,{attemptToken:c.attempt!.token,runId:randomUUID()}),f.dispatch.adoptObservedRun(c,{attemptToken:c.attempt!.token,runId:randomUUID()})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const retained=await f.dispatch.get(c.operationId);assert.equal(retained!.cancellation!.cause,'superseded');assert.ok(retained!.runId);}finally{await f.close();}});
test('observed prior attempt cannot be adopted after expiry during row lock wait',async()=>{const f=await fixture(),lock=await f.pool.connect();try{const c=await bound(f);await lock.query('BEGIN');await lock.query("UPDATE agentci_reproduction_dispatch_state SET lease_until=clock_timestamp()+interval '150 milliseconds'");const rejected=assert.rejects(f.dispatch.adoptObservedRun(c,{attemptToken:c.attempt!.token,runId:randomUUID()}),ReproductionDispatchLeaseLost);await lock.query('SELECT pg_sleep(0.2)');await lock.query('COMMIT');await rejected;assert.equal((await f.dispatch.get(c.operationId))!.runId,null);}finally{lock.release();await f.close();}});

async function noExecution(f:Awaited<ReturnType<typeof fixture>>){const proofs=new ReproductionNonExecutionStore(f.pool,f.scope);await f.pool.query('INSERT INTO agentci_reproduction_cancellations(organization_id,repository,id) VALUES($1,$2,$3)',[f.scope.organizationId,f.scope.repository,f.f.plan.id]);const proof=await proofs.cancelled(f.f.plan.id);const history=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:async()=>{throw Error('no receipt');},nonExecution:(id,subject)=>proofs.read(id,subject)});const event=await history.unavailable(f.f.initial.id,f.f.initial.subject,{type:'unavailable',proofId:proof.id},2,proof.id);return {kind:'never-staged' as const,proof,history:event};}
async function operator(f:Awaited<ReturnType<typeof fixture>>){const receipt={findingId:f.f.finding.id,subjectDigest:digest(canonical(f.f.finding.subject)),assertionDigest:null,evidenceDigest:digest('operator-approved-disposition'),actor:'operator' as const,outcome:'false-positive' as const,reason:'Operator classified the finding'};const store=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:async()=>receipt});return store.transition(f.f.finding.id,f.f.finding.subject,{type:'false-positive',receiptId:randomUUID()},2,randomUUID());}
async function execution(f:Awaited<ReturnType<typeof fixture>>,supersede=false){const evals=new EvalStore(f.pool,f.scope.organizationId,f.scope.repository),staging=new ReproductionEvalStore(f.pool,f.scope,f.registry);let reproduction:FindingReproductionStore;const history=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:(id,subject)=>reproduction.readReceipt(id,subject)});reproduction=new FindingReproductionStore(f.pool,f.scope,history,evals,{approvedPlan:async()=>f.f.plan},staging);const staged=await reproduction.stage(f.f.plan.id,f.f.base,f.f.head);await evals.cancel(staged.jobId);if(supersede){const event=await operator(f);await assert.rejects(reproduction.finalize(f.f.plan.id));return {kind:'superseded' as const,history:event,receipt:await reproduction.readReceipt(f.f.plan.id,f.f.finding.subject),proof:null};}await reproduction.finalize(f.f.plan.id);return {kind:'receipt-retained' as const,history:(await history.get(f.f.finding.id,f.f.finding.subject)).at(-1)!,receipt:await reproduction.readReceipt(f.f.plan.id,f.f.finding.subject)};}
test('never-staged settlement requires real proof plus unavailable event, then excludes both claim lanes',async()=>{const f=await fixture();try{const evidence=await noExecution(f);const store=new ReproductionDispatchStore(f.pool,f.scope,async()=>evidence);const c=await store.claim();assert.ok(c);const done=await store.settle(c);assert.equal(done!.settlement!.kind,'never-staged');assert.equal(done!.settlement!.retainedReceiptDigest,null);assert.equal(await store.claim(),undefined);assert.equal(await store.claim('recovery'),undefined);assert.deepEqual(await store.settle(c),done);await assert.rejects(f.pool.query('UPDATE agentci_reproduction_dispatch_state SET settlement=NULL,settled_at=NULL'),/Immutable/);}finally{await f.close();}});
test('cancelled zero-trial execution receipt is retained without claiming success',async()=>{const f=await fixture();try{const evidence=await execution(f);assert.equal(evidence.receipt.outcome,'error');const store=new ReproductionDispatchStore(f.pool,f.scope,async()=>evidence),c=await store.claim();assert.ok(c);const done=await store.settle(c);assert.equal(done!.settlement!.kind,'receipt-retained');assert.equal(done!.settlement!.retainedReceiptDigest,digest(canonical(evidence.receipt)));assert.equal((await f.pool.query('SELECT count(*) FROM agentci_eval_trials')).rows[0].count,'0');}finally{await f.close();}});
test('superseded operator disposition preserves actual receipt even when reproduction event lost CAS',async()=>{const f=await fixture();try{const evidence=await execution(f,true);const store=new ReproductionDispatchStore(f.pool,f.scope,async()=>evidence),c=await store.claim();assert.ok(c);const done=await store.settle(c);assert.equal(done!.settlement!.kind,'superseded');assert.equal(done!.settlement!.retainedReceiptDigest,digest(canonical(evidence.receipt)));assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_receipts')).rows[0].count,'1');assert.equal(evidence.history.event.action.type,'false-positive');}finally{await f.close();}});
test('missing, forged and wrong-scope settlement evidence never retires the dispatch',async()=>{const f=await fixture(),other=await fixture();try{const correct=await noExecution(f),foreign=await noExecution(other);let value:DispatchSettlementEvidence|undefined;const store=new ReproductionDispatchStore(f.pool,f.scope,async()=>value),c=await store.claim();assert.ok(c);assert.equal(await store.settle(c),undefined);for(const bad of [foreign,{...correct,proof:{...correct.proof,reservationOperationId:randomUUID()}},{...correct,history:{...correct.history,digest:digest('missing')}}]){value=bad;await assert.rejects(store.settle(c));assert.equal((await store.get(c.operationId))!.settlement,null);}value=correct;assert.equal((await store.settle(c))!.settlement!.kind,'never-staged');}finally{await f.close();await other.close();}});
test('settlement rechecks lease after trusted reader awaits',async()=>{const f=await fixture();try{const evidence=await noExecution(f);const store=new ReproductionDispatchStore(f.pool,f.scope,async c=>{await c.query("UPDATE agentci_reproduction_dispatch_state SET lease_until=clock_timestamp()-interval '1 second'");return evidence;}),claim=await store.claim();assert.ok(claim);await assert.rejects(store.settle(claim),ReproductionDispatchLeaseLost);assert.equal((await store.get(claim.operationId))!.settlement,null);}finally{await f.close();}});
test('superseded disposition preserves never-staged proof without fabricating unavailable history',async()=>{const f=await fixture();try{const proofs=new ReproductionNonExecutionStore(f.pool,f.scope);await f.pool.query('INSERT INTO agentci_reproduction_cancellations(organization_id,repository,id) VALUES($1,$2,$3)',[f.scope.organizationId,f.scope.repository,f.f.plan.id]);const proof=await proofs.cancelled(f.f.plan.id),history=await operator(f);const evidence={kind:'superseded' as const,history,receipt:null,proof};const store=new ReproductionDispatchStore(f.pool,f.scope,async()=>evidence),c=await store.claim();assert.ok(c);const result=await store.settle(c);assert.equal(result!.settlement!.retainedProofDigest,digest(canonical(proof)));assert.equal((await f.pool.query("SELECT count(*) FROM agentci_finding_events WHERE event->'action'->>'type'='unavailable'")).rows[0].count,'0');}finally{await f.close();}});
test('superseded event cannot retire outstanding evaluator work or omit a retained receipt',async()=>{const f=await fixture();try{const stage=new ReproductionEvalStore(f.pool,f.scope,f.registry);await stage.stage(f.f.plan.id,f.f.base,f.f.head);const evidence={kind:'superseded' as const,history:await operator(f),receipt:null,proof:null};const store=new ReproductionDispatchStore(f.pool,f.scope,async()=>evidence),c=await store.claim();assert.ok(c);await assert.rejects(store.settle(c),ReproductionDispatchConflict);assert.equal((await store.get(c.operationId))!.settlement,null);}finally{await f.close();}
 const g=await fixture();try{const real=await execution(g,true);if(real.kind!=='superseded')throw Error('fixture');let evidence:DispatchSettlementEvidence={...real,receipt:null};const store=new ReproductionDispatchStore(g.pool,g.scope,async()=>evidence),c=await store.claim();assert.ok(c);await assert.rejects(store.settle(c),ReproductionDispatchConflict);evidence={...real,receipt:{...real.receipt,evidenceDigest:digest('forged')}};await assert.rejects(store.settle(c),ReproductionDispatchConflict);assert.equal((await store.get(c.operationId))!.settlement,null);}finally{await g.close();}});
