import {createReproductionConsumerRuntime} from '../../apps/worker/reproduction-consumer-runtime.ts';
import {ReproductionNonExecutionStore} from '../../packages/storage/reproduction-non-execution.ts';
import {FindingHistoryStore} from '../../packages/storage/finding-history.ts';
import {EvalStore} from '../../packages/storage/evals.ts';
import {ReproductionEvalStore} from '../../packages/storage/reproduction-evals.ts';
import {FindingReproductionStore} from '../../packages/storage/finding-reproduction.ts';
import type {DispatchSettlementEvidence,DispatchSettlementReader} from '../../packages/storage/reproduction-dispatch.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';
import {reproductionStagingFixture} from '../helpers/reproduction-staging-fixture.ts';import {Store} from '../../packages/storage/postgres.ts';import {canonical,digest} from '../../packages/review/engine.ts';import {ReproductionAuthorityStore} from '../../packages/storage/reproduction-authority.ts';import {ReproductionDispatchStore,ReproductionDispatchConflict,ReproductionDispatchLeaseLost} from '../../packages/storage/reproduction-dispatch.ts';
async function fixture(){const f=await reproductionStagingFixture();try{await new Store(f.pool,f.scope.organizationId,f.scope.repository).ready();for(const n of ['015_m3_reproduction_eval_source','016_m3_reproduction_authority'])await f.pool.query(await readFile(new URL(`../../deploy/migrations/${n}.sql`,import.meta.url),'utf8'));await f.store.reserve(f.f.initial.id,f.selector);
 const readers={finding:async()=>f.f.initial,plan:async()=>f.f.plan,snapshot:async(_s:unknown,side:'base'|'head')=>f.f[side]};const authority=new ReproductionAuthorityStore(f.pool,f.scope,readers,async()=>true);const config=await authority.apply({schemaVersion:'v1alpha1',...f.scope,revision:1,approvals:[{planId:f.f.plan.id,planDigest:digest(canonical(f.f.plan)),findingId:f.f.initial.id,findingVersion:1,findingDigest:digest(canonical(f.f.initial)),enabled:true,expiresAt:'2100-01-01T00:00:00.000Z'}]},null);
 const migration=await readFile(new URL('../../deploy/migrations/017_m3_reproduction_dispatch_state.sql',import.meta.url),'utf8');await f.pool.query(migration);await f.pool.query(migration);const dispatch=new ReproductionDispatchStore(f.pool,f.scope);await f.pool.query(await readFile(new URL('../../deploy/migrations/018_m3_reproduction_dispatch_settlement.sql',import.meta.url),'utf8'));await dispatch.ready();return {...f,dispatch,migration,authority,options:{taskQueue:'reproduction-controller',evalTaskQueue:'reproduction-eval',config}};
 }catch(e){await f.close();throw e;}}
async function bound(f:Awaited<ReturnType<typeof fixture>>){const claim=await f.dispatch.claim();assert.ok(claim);return f.dispatch.bind(claim,f.options);}


async function runtimeFixture(){const f=await fixture();let permissionCalls=0,permission:()=>Promise<boolean>=async()=>true;const authority=new ReproductionAuthorityStore(f.pool,f.scope,{finding:async()=>f.f.initial,plan:async()=>f.f.plan,snapshot:async(_s,side)=>f.f[side]},async()=>{permissionCalls++;return permission();});const evals=new EvalStore(f.pool,f.scope.organizationId,f.scope.repository),staging=new ReproductionEvalStore(f.pool,f.scope,f.registry),proofs=new ReproductionNonExecutionStore(f.pool,f.scope);let reproduction:FindingReproductionStore;const history=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:(id,subject)=>reproduction.readReceipt(id,subject),nonExecution:(id,subject)=>proofs.read(id,subject)});reproduction=new FindingReproductionStore(f.pool,f.scope,history,evals,{approvedPlan:async()=>f.f.plan},staging);const runtime=createReproductionConsumerRuntime({pool:f.pool,scope:f.scope,authority,staging,reproduction,history,proofs,evals,dispatch:f.dispatch,snapshots:async(_subject,side)=>f.f[side],evalTaskQueue:f.options.evalTaskQueue});const dispatch=new ReproductionDispatchStore(f.pool,f.scope,runtime.settlementReader);const start=await bound(f);return {...f,authority,evals,staging,proofs,history,reproduction,runtime,dispatch,start,setPermission:(p:()=>Promise<boolean>)=>{permission=p;},permissionCalls:()=>permissionCalls};}
async function supersede(f:Awaited<ReturnType<typeof runtimeFixture>>){const receipt={findingId:f.f.finding.id,subjectDigest:digest(canonical(f.f.finding.subject)),assertionDigest:null,evidenceDigest:digest('operator-evidence'),actor:'operator' as const,outcome:'false-positive' as const,reason:'Operator disposition'};const h=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:async()=>receipt});return h.transition(f.f.finding.id,f.f.finding.subject,{type:'false-positive',receiptId:randomUUID()},2,randomUUID());}
test('factory stages actual typed job with current authority and rolls back final permission denial',async()=>{const f=await runtimeFixture();try{const staged=await f.runtime.activities.stageAdmittedReproduction(f.start.operationId,f.start.attempt!.token);assert.equal(staged.kind,'staged');assert.equal(f.permissionCalls(),2);assert.equal((await f.pool.query('SELECT count(*) FROM agentci_eval_jobs WHERE source IS NOT NULL')).rows[0].count,'1');}finally{await f.close();}
 const g=await runtimeFixture();try{let calls=0;g.setPermission(async()=>++calls===1);assert.deepEqual(await g.runtime.activities.stageAdmittedReproduction(g.start.operationId,g.start.attempt!.token),{kind:'not-started'});assert.equal((await g.dispatch.get(g.start.operationId))!.cancellation!.cause,'permission-denied');assert.equal((await g.pool.query('SELECT count(*) FROM agentci_eval_jobs')).rows[0].count,'0');assert.equal((await g.pool.query('SELECT count(*) FROM agentci_eval_units')).rows[0].count,'0');}finally{await g.close();}});
test('durable cancellation is consumed before unavailable permission and creates real nonexecution history',async()=>{const f=await runtimeFixture();try{f.setPermission(async()=>{throw Error('permission outage');});await f.dispatch.requestCancellation(f.start.operationId,'user');const result=await f.runtime.activities.stageAdmittedReproduction(f.start.operationId,f.start.attempt!.token);assert.deepEqual(result,{kind:'not-started'});assert.equal(f.permissionCalls(),0);const last=(await f.history.get(f.f.finding.id,f.f.finding.subject)).at(-1)!;assert.equal(last.event.action.type,'unavailable');assert.equal(last.event.receipt,null);assert.equal(last.event.nonExecution!.reason,'cancelled');assert.equal((await f.pool.query('SELECT count(*) FROM agentci_eval_jobs')).rows[0].count,'0');}finally{await f.close();}});
test('historical approval cannot bypass fresh operator disposition; outages do not become denial',async()=>{const f=await runtimeFixture();try{await supersede(f);await assert.rejects(f.runtime.activities.stageAdmittedReproduction(f.start.operationId,f.start.attempt!.token));assert.equal((await f.pool.query('SELECT count(*) FROM agentci_eval_jobs')).rows[0].count,'0');assert.equal((await f.runtime.activities.checkAdmittedReproduction(f.start.operationId,f.start.attempt!.token)).allowed,false);f.setPermission(async()=>{throw Error('private permission diagnostic');});await assert.rejects(f.runtime.activities.checkAdmittedReproduction(f.start.operationId,f.start.attempt!.token),/reproduction-authority-unavailable/);}finally{await f.close();}});
test('old originating attempt survives unchanged-plan config advancement; revocation cannot authorize another stage',async()=>{const f=await runtimeFixture();try{const config=await f.authority.read(f.options.config),next=await f.authority.apply({...config,revision:2},f.options.config);assert.equal((await f.runtime.activities.stageAdmittedReproduction(f.start.operationId,f.start.attempt!.token)).kind,'staged');await f.authority.apply({...config,revision:3,approvals:config.approvals.map(a=>({...a,enabled:false}))},next);assert.equal((await f.runtime.activities.checkAdmittedReproduction(f.start.operationId,f.start.attempt!.token)).allowed,false);const cleanup=await f.runtime.activities.cancelAdmittedReproduction(f.start.operationId,f.start.attempt!.token,'denied');assert.equal(cleanup.unitIds.length,1);assert.equal((await f.dispatch.get(f.start.operationId))!.cancellation!.cause,'revoked');await f.runtime.activities.finalizeAdmittedReproduction(f.start.operationId,f.start.attempt!.token);assert.equal((await f.reproduction.readReceipt(f.f.plan.id,f.f.finding.subject)).outcome,'error');}finally{await f.close();}});
test('settlement needs exact external quiescence and expires with the recovery lease identity',async()=>{const f=await runtimeFixture();try{await f.runtime.activities.cancelAdmittedReproduction(f.start.operationId,f.start.attempt!.token,'cancelled');const runId=randomUUID();await f.dispatch.acknowledge(f.start,runId);const claim=await f.dispatch.claim('recovery');assert.ok(claim);assert.equal(await f.dispatch.settle(claim),undefined);await assert.rejects(f.runtime.markRuntimeQuiescent(claim,{runId:randomUUID(),status:'CANCELLED',units:[],cleanup:[]}));await f.runtime.markRuntimeQuiescent(claim,{runId,status:'CANCELLED',units:[],cleanup:[]});await f.dispatch.release(claim,0);const fresh=await f.dispatch.claim('recovery');assert.ok(fresh);assert.equal(await f.dispatch.settle(fresh),undefined);await f.runtime.markRuntimeQuiescent(fresh,{runId,status:'CANCELLED',units:[],cleanup:[]});assert.equal((await f.dispatch.settle(fresh))!.settlement!.kind,'never-staged');}finally{await f.close();}});
test('operator disposition racing stage serializes at finding fence and blocks subsequent execution checks',async()=>{const f=await runtimeFixture();try{let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(r=>{release=r;}),ready=new Promise<void>(r=>{entered=r;});let calls=0;f.setPermission(async()=>{if(++calls===2){entered();await gate;}return true;});const staging=f.runtime.activities.stageAdmittedReproduction(f.start.operationId,f.start.attempt!.token);await ready;const disposition=supersede(f);release();assert.equal((await staging).kind,'staged');await disposition;assert.equal((await f.runtime.activities.checkAdmittedReproduction(f.start.operationId,f.start.attempt!.token)).allowed,false);await f.runtime.activities.cancelAdmittedReproduction(f.start.operationId,f.start.attempt!.token,'superseded');await f.runtime.activities.finalizeAdmittedReproduction(f.start.operationId,f.start.attempt!.token);assert.equal((await f.history.get(f.f.finding.id,f.f.finding.subject)).at(-1)!.event.action.type,'false-positive');assert.equal((await f.reproduction.readReceipt(f.f.plan.id,f.f.finding.subject)).outcome,'error');}finally{await f.close();}});
test('system outage cancellation retains unavailable cause and cannot claim completed-parent cleanup',async()=>{const f=await runtimeFixture();try{const staged=await f.runtime.activities.stageAdmittedReproduction(f.start.operationId,f.start.attempt!.token);assert.equal(staged.kind,'staged');if(staged.kind!=='staged')throw Error('fixture');await f.runtime.activities.cancelAdmittedReproduction(f.start.operationId,f.start.attempt!.token,'unavailable');assert.equal((await f.dispatch.get(f.start.operationId))!.cancellation!.cause,'unavailable');await f.runtime.activities.finalizeAdmittedReproduction(f.start.operationId,f.start.attempt!.token);const runId=randomUUID();await f.dispatch.acknowledge(f.start,runId);const claim=await f.dispatch.claim('recovery');assert.ok(claim);const unit={unitId:staged.unitId,workflowId:staged.unitWorkflowId,runId:null,status:'NOT_STARTED'};await assert.rejects(f.runtime.markRuntimeQuiescent(claim,{runId,status:'COMPLETED',units:[unit],cleanup:[]}));await assert.rejects(f.runtime.markRuntimeQuiescent(claim,{runId,status:'FAILED',units:[unit],cleanup:[]}));await f.runtime.markRuntimeQuiescent(claim,{runId,status:'FAILED',units:[unit],cleanup:[{unitId:staged.unitId,workflowId:staged.cleanupWorkflowId,runId:randomUUID()}]});assert.equal((await f.dispatch.settle(claim))!.settlement!.kind,'receipt-retained');}finally{await f.close();}});

test('stage permission outage remains unavailable with no denial, execution or nonexecution proof fabricated',async()=>{const f=await runtimeFixture();try{f.setPermission(async()=>{throw Error('private upstream diagnostic');});await assert.rejects(f.runtime.activities.stageAdmittedReproduction(f.start.operationId,f.start.attempt!.token),/^Error: reproduction-authority-unavailable$/);assert.equal((await f.dispatch.get(f.start.operationId))!.cancellation,null);for(const table of ['agentci_eval_jobs','agentci_reproduction_receipts','agentci_reproduction_non_execution'])assert.equal((await f.pool.query(`SELECT count(*) FROM ${table}`)).rows[0].count,'0');assert.equal((await f.history.get(f.f.finding.id,f.f.finding.subject)).at(-1)!.event.finding.state,'reproduction-pending');}finally{await f.close();}});
