import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {reproductionStagingFixture} from '../helpers/reproduction-staging-fixture.ts';
import {canonical,digest} from '../../packages/review/engine.ts';
import {parseReproductionCatalog,reproductionCatalogReaders} from '../../packages/runtime/reproduction-catalog.ts';
import {ReproductionAuthorityStore} from '../../packages/storage/reproduction-authority.ts';
import {pathToFileURL} from 'node:url';
const {applyReproductionOperator}=process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT
 ?await import(pathToFileURL(join(process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT,'dist/packages/operator/reproduction.js')).href)
 :await import('../../packages/operator/reproduction.ts');
async function fixture(){const f=await reproductionStagingFixture(),dir=await mkdtemp(join(tmpdir(),'agentci-operator-'));try{await f.pool.query(await readFile(new URL('../../deploy/migrations/016_m3_reproduction_authority.sql',import.meta.url),'utf8'));const document={schemaVersion:'v1alpha1' as const,...f.scope,plans:[{digest:digest(canonical(f.f.plan)),plan:f.f.plan}]},catalog=parseReproductionCatalog(document,f.scope,digest(canonical(document))),readers=reproductionCatalogReaders(f.pool,f.scope,catalog,'independent-fixture-key-'.repeat(3),async(_s,side)=>f.f[side]);const authority=new ReproductionAuthorityStore(f.pool,f.scope,readers,async()=>{throw Error('Apply must not grant live execution permission');});const config={schemaVersion:'v1alpha1' as const,...f.scope,revision:1,approvals:[{planId:f.f.plan.id,planDigest:digest(canonical(f.f.plan)),findingId:f.f.initial.id,findingVersion:1,findingDigest:digest(canonical(f.f.initial)),enabled:true,expiresAt:'2100-01-01T00:00:00.000Z'}]};return {...f,dir,catalog,authority,config,closeAll:async()=>{await rm(dir,{recursive:true,force:true});await f.close();}};}catch(error){await rm(dir,{recursive:true,force:true});await f.close();throw error;}}
test('operator command bootstraps before reservation, applies pinned CAS revision, preserves exact replay and revocation',async()=>{
 const f=await fixture();try{const path=join(f.dir,'config.json');let closed=0;const apply=async(config:typeof f.config,expected:string)=>{await writeFile(path,JSON.stringify(config));const identity={revision:config.revision,digest:digest(canonical(config))};const result=await applyReproductionOperator(['apply','--config',path,'--config-digest',identity.digest,'--expected',expected],async()=>({runtime:{catalog:f.catalog,expected:identity,evalTaskQueue:'agentci-eval-v1'},authority:f.authority,close:async()=>{closed++;}}));assert.deepEqual(result,identity);return result;};
  const initial=await apply(f.config,'initial');assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_plans')).rows[0].count,'0');assert.deepEqual(await apply(f.config,'initial'),initial);assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_config_versions')).rows[0].count,'1');
  const revoked={...f.config,revision:2,approvals:f.config.approvals.map(a=>({...a,enabled:false}))};const next=await apply(revoked,`${initial.revision}:${initial.digest}`);assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_revocations')).rows[0].count,'1');
  await writeFile(path,JSON.stringify({...f.config,revision:3}));const hash=digest(canonical({...f.config,revision:3}));await assert.rejects(applyReproductionOperator(['apply','--config',path,'--config-digest',hash,'--expected',`${next.revision}:${next.digest}`],async()=>({runtime:{catalog:f.catalog,expected:{revision:3,digest:hash},evalTaskQueue:'agentci-eval-v1'},authority:f.authority,close:async()=>{closed++;}})),/authority-conflict/);assert.equal(closed,4);assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_config_versions')).rows[0].count,'2');
 }finally{await f.closeAll();}
});
test('operator rejects unpinned bytes before connecting and wrong target identity without writes; failures close connection',async()=>{
 const f=await fixture();try{const path=join(f.dir,'config.json'),hash=digest(canonical(f.config));await writeFile(path,JSON.stringify(f.config));let connected=0,closed=0;const connect=async()=>{connected++;return {runtime:{catalog:f.catalog,expected:{revision:2,digest:hash},evalTaskQueue:'agentci-eval-v1'},authority:f.authority,close:async()=>{closed++;}};};
  for(const args of [[],['apply','--config','relative.json','--config-digest',hash,'--expected','initial'],['apply','--config',path,'--config-digest',digest('wrong'),'--expected','initial'],['apply','--config',path,'--config-digest',hash,'--expected','01:'+hash]])await assert.rejects(applyReproductionOperator(args,connect));assert.equal(connected,0);
  await assert.rejects(applyReproductionOperator(['apply','--config',path,'--config-digest',hash,'--expected','initial'],connect),/invalid-reproduction-operator-arguments/);assert.equal(connected,1);assert.equal(closed,1);assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_config_versions')).rows[0].count,'0');
  await writeFile(path,Buffer.alloc(65537,32));await assert.rejects(applyReproductionOperator(['apply','--config',path,'--config-digest',hash,'--expected','initial'],connect));assert.equal(connected,1);
 }finally{await f.closeAll();}
});
