import test from 'node:test';import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
test('Compose consumer opt-in renders pinned authority and read-only catalog without adding evaluator privileges',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'agentci-reproduction-compose-'));try{const envFile=join(dir,'fixture.env'),catalog=join(dir,'catalog.json');await writeFile(catalog,'{}');await writeFile(envFile,'POSTGRES_PASSWORD=fixture-only\nGITHUB_PRIVATE_KEY_FILE=/fixture/app.pem\nAGENTCI_REPRODUCTION_CATALOG_FILE='+catalog+'\nAGENTCI_REPRODUCTION_CATALOG_DIGEST=sha256:'+'a'.repeat(64)+'\nAGENTCI_REPRODUCTION_CONFIG_REVISION=1\nAGENTCI_REPRODUCTION_CONFIG_DIGEST=sha256:'+'b'.repeat(64)+'\nAGENTCI_CURSOR_KEY='+'k'.repeat(40)+'\n');
 const packageRoot=process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT??resolve('.'),base=['compose','--env-file',envFile,'-f',join(packageRoot,'deploy/compose.yaml')],environment={PATH:process.env.PATH,HOME:process.env.HOME,DOCKER_CONFIG:process.env.DOCKER_CONFIG,AGENTCI_ENV_FILE:envFile};
 const plain=JSON.parse(execFileSync('docker',[...base,'config','--format','json'],{env:environment,encoding:'utf8'}));assert.equal(plain.services.worker.image,'agentci-worker:0.3.1-m2');assert.ok(!plain.services.worker.volumes.some((v:any)=>v.target==='/run/agentci/reproduction-catalog.json'));
 const merged=JSON.parse(execFileSync('docker',[...base,'-f',join(packageRoot,'deploy/reproduction.compose.yaml'),'config','--format','json'],{env:environment,encoding:'utf8'})),worker=merged.services.worker;assert.equal(worker.image,'agentci-worker:0.4.0-m3-dev.1');assert.equal(worker.environment.AGENTCI_REPRODUCTION_CATALOG_FILE,'/run/agentci/reproduction-catalog.json');assert.equal(worker.environment.AGENTCI_REPRODUCTION_CONFIG_REVISION,'1');assert.equal(worker.environment.AGENTCI_REPRODUCTION_CONFIG_DIGEST,'sha256:'+'b'.repeat(64));assert.equal(worker.environment.AGENTCI_REPRODUCTION_CATALOG_DIGEST,'sha256:'+'a'.repeat(64));const mount=worker.volumes.find((v:any)=>v.target==='/run/agentci/reproduction-catalog.json');assert.equal(mount.source,catalog);assert.equal(mount.read_only,true);assert.ok(!worker.privileged);assert.ok(!worker.volumes.some((v:any)=>/docker\.sock|podman\.sock/.test(v.source)));assert.deepEqual(merged.services.api,plain.services.api);
 }finally{await rm(dir,{recursive:true,force:true});}
});
