import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile,writeFile,rm,realpath} from 'node:fs/promises';import {once} from 'node:events';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
import {reproductionStagingFixture} from '../helpers/reproduction-staging-fixture.ts';import {Store} from '../../packages/storage/postgres.ts';import {FindingHistoryStore} from '../../packages/storage/finding-history.ts';import {ReproductionNonExecutionStore} from '../../packages/storage/reproduction-non-execution.ts';import {FindingReproductionStore} from '../../packages/storage/finding-reproduction.ts';import {ReproductionEvalStore} from '../../packages/storage/reproduction-evals.ts';import {EvalStore} from '../../packages/storage/evals.ts';import {createControlApi} from '../../apps/control/server.ts';import {createModelReviewControl} from '../../apps/control/model-reviews.ts';import {canonical,digest} from '../../packages/review/engine.ts';
if(!process.env.AGENTCI_TEST_DATABASE_URL)throw Error('Installed v2 reader acceptance requires real PostgreSQL; never silently skip');
const packageRoot=process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT,sourceRoot=new URL('../../',import.meta.url).pathname;
const probe=resolve(packageRoot?resolve(packageRoot,'../..'):sourceRoot,`agentci-v2-consumer-${randomUUID()}.mjs`);
await writeFile(probe,"export {ModelReviewClient,AgentCIError} from 'agentci/client';export const resolved=import.meta.resolve('agentci/client');\n");
let publicClient:any;try{publicClient=await import(pathToFileURL(probe).href);}finally{await rm(probe);}
const {ModelReviewClient,AgentCIError}=publicClient;
assert.equal(publicClient.resolved,pathToFileURL(await realpath(resolve(packageRoot??sourceRoot,'dist/packages/client/index.js'))).href,'must resolve the supported compiled public export, with no source-client fallback');

test('public compiled or installed client reads authenticated retained v2 finding and paginated mixed history',{timeout:30000},async()=>{
 const f=await reproductionStagingFixture(),servers:ReturnType<typeof createControlApi>[]=[];
 try{
  await new Store(f.pool,f.scope.organizationId,f.scope.repository).ready();for(const name of ['015_m3_reproduction_eval_source','016_m3_reproduction_authority'])await f.pool.query(await readFile(new URL(`../../deploy/migrations/${name}.sql`,import.meta.url),'utf8'));
  await f.store.reserve(f.f.initial.id,f.selector);const proofs=new ReproductionNonExecutionStore(f.pool,f.scope),evals=new EvalStore(f.pool,f.scope.organizationId,f.scope.repository),staging=new ReproductionEvalStore(f.pool,f.scope,f.registry);let reproduction:FindingReproductionStore;
  const history=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:(id,subject)=>reproduction.readReceipt(id,subject),nonExecution:(id,subject)=>proofs.read(id,subject)});reproduction=new FindingReproductionStore(f.pool,f.scope,history,evals,{approvedPlan:async()=>f.f.plan},staging);
  await reproduction.cancel(f.f.plan.id);const proof=await proofs.cancelled(f.f.plan.id);await history.unavailable(f.f.initial.id,f.f.initial.subject,{type:'unavailable',proofId:proof.id},2,proof.id);const retained=await history.get(f.f.initial.id,f.f.initial.subject);
  const config={...f.scope,installationId:1,secret:'owned-hook-'.repeat(4),evidenceToken:'owned-reader-'.repeat(4),cursorKey:'owned-cursor-'.repeat(4)};
  let fault:'none'|'future'|'proof'='none';const control=await createModelReviewControl(f.pool,config,null);
  const alter=(value:any)=>{const r=structuredClone(value);if(r.event.schemaVersion==='v1alpha2'&&fault!=='none'){if(fault==='future')r.event.schemaVersion='v1alpha999';else r.event.nonExecution.subjectDigest=digest('substituted proof subject');r.digest=digest(canonical(r.event));}return r;};
  // Fault injection changes only outbound records after genuine authenticated DB
  // reads. It proves the installed client's independent transport validation.
  const boundFinding=control.finding!,boundHistory=control.history!;
  control.finding=async(...args)=>alter(await boundFinding(...args));control.history=async(...args)=>{const page=await boundHistory(...args);return {...page,items:page.items.map(alter)};};
  const serve=async(api:typeof control)=>{const server=createControlApi(config,{ready:async()=>{},recordDelivery:async()=>{throw Error('Unused legacy route');},evidence:async()=>undefined},undefined,api);servers.push(server);server.listen(0,'127.0.0.1');await once(server,'listening');return `http://127.0.0.1:${(server.address() as {port:number}).port}`;};
  const url=await serve(control),client=new ModelReviewClient({url,readToken:config.evidenceToken,maxAttempts:1}),current=await client.finding(f.request,f.f.initial.id);assert.deepEqual(current,retained[2]);assert.ok(current?.event.nonExecution);assert.ok(current.event.finding.disposition);assert.equal(current.event.receipt,null);assert.equal(current.event.nonExecution.executionReceipt,null);assert.equal(current.event.nonExecution.verified,false);assert.equal(current.event.finding.state,'unconfirmed');assert.equal(current.event.finding.disposition.outcome,'error');
  const pages=[];for await(const page of client.findingHistory(f.request,f.f.initial.id,{limit:1}))pages.push(page);assert.equal(pages.length,3);assert.deepEqual(pages.flatMap(p=>p.items),retained);assert.deepEqual(pages.map(p=>p.items[0].event.schemaVersion),['v1alpha1','v1alpha1','v1alpha2']);assert.equal(pages[2].nextCursor,null);assert.deepEqual(await client.finding(f.request,f.f.initial.id,{version:1}),retained[0]);
  const rejected=(code:string)=>(e:any)=>e instanceof AgentCIError&&e.code===code;
  const unauthorized=new ModelReviewClient({url,readToken:'wrong-token-'.repeat(4),maxAttempts:1});await assert.rejects(unauthorized.finding(f.request,f.f.initial.id),rejected('unauthorized'));
  await assert.rejects(client.finding({...f.request,subject:{...f.request.subject,repository:'other/repo'}},f.f.initial.id),rejected('identity-mismatch'));
  const other=await createModelReviewControl(f.pool,{...config,organizationId:randomUUID()},null),scoped=new ModelReviewClient({url:await serve(other),readToken:config.evidenceToken,maxAttempts:1});await assert.rejects(scoped.finding(f.request,f.f.initial.id),rejected('not-found'));
  for(const mode of ['future','proof'] as const){fault=mode;await assert.rejects(client.finding(f.request,f.f.initial.id),rejected('invalid-response'));let delivered=0;await assert.rejects(async()=>{for await(const _page of client.findingHistory(f.request,f.f.initial.id,{limit:1}))delivered++;},rejected('invalid-response'));assert.equal(delivered,2,'valid v1 pages precede rejected v2/future record; traversal never completes');}
  fault='none';assert.deepEqual(await client.finding(f.request,f.f.initial.id),retained[2]);for(const table of ['agentci_reviews','agentci_eval_jobs','agentci_eval_units','agentci_reproduction_receipts'])assert.equal((await f.pool.query(`SELECT count(*) FROM ${table}`)).rows[0].count,'0',table+' must remain empty');
 }finally{for(const server of servers){server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}await f.close();}
});
