import {pathToFileURL} from 'node:url';import {resolve} from 'node:path';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';import {once} from 'node:events';
import {reproductionStagingFixture} from '../helpers/reproduction-staging-fixture.ts';
import {Store} from '../../packages/storage/postgres.ts';import {canonical,digest} from '../../packages/review/engine.ts';
import {ReproductionAuthorityStore} from '../../packages/storage/reproduction-authority.ts';import {ReproductionDispatchStore} from '../../packages/storage/reproduction-dispatch.ts';
import {ReproductionReads} from '../../packages/storage/reproduction-reads.ts';import {ReproductionNonExecutionStore} from '../../packages/storage/reproduction-non-execution.ts';
import {FindingHistoryStore} from '../../packages/storage/finding-history.ts';import {EvalStore} from '../../packages/storage/evals.ts';import {ReproductionEvalStore} from '../../packages/storage/reproduction-evals.ts';import {FindingReproductionStore} from '../../packages/storage/finding-reproduction.ts';
import {createControlApi} from '../../apps/control/server.ts';import {createModelReviewControl} from '../../apps/control/model-reviews.ts';
import {validateFindingReproductionStatus} from '../../packages/findings/reproduction-transport.ts';
import {Ajv} from 'ajv';import type {Pool,PoolClient} from 'pg';
const contract=JSON.parse(await readFile(new URL('../../specs/api/openapi.json',import.meta.url),'utf8')),ajv=new Ajv({strict:false});
const statusShape=ajv.compile({$ref:'#/components/schemas/FindingReproductionStatus',components:contract.components});
const packageRoot=process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT;
const apiFactory=packageRoot?(await import(pathToFileURL(resolve(packageRoot,'dist/apps/control/server.js')).href)).createControlApi:createControlApi;
const controlFactory=packageRoot?(await import(pathToFileURL(resolve(packageRoot,'dist/apps/control/model-reviews.js')).href)).createModelReviewControl:createModelReviewControl;

async function fixture(){const f=await reproductionStagingFixture();try{
 await new Store(f.pool,f.scope.organizationId,f.scope.repository).ready();for(const n of ['015_m3_reproduction_eval_source','016_m3_reproduction_authority','017_m3_reproduction_dispatch_state','018_m3_reproduction_dispatch_settlement'])await f.pool.query(await readFile(new URL(`../../deploy/migrations/${n}.sql`,import.meta.url),'utf8'));
 const authority=new ReproductionAuthorityStore(f.pool,f.scope,{finding:async()=>f.f.initial,plan:async()=>f.f.plan,snapshot:async(_s:unknown,side:'base'|'head')=>f.f[side]},async()=>true);
 const identity=await authority.apply({schemaVersion:'v1alpha1',...f.scope,revision:1,approvals:[{planId:f.f.plan.id,planDigest:digest(canonical(f.f.plan)),findingId:f.f.initial.id,findingVersion:1,findingDigest:digest(canonical(f.f.initial)),enabled:true,expiresAt:'2100-01-01T00:00:00.000Z'}]},null);
 await f.store.reserve(f.f.initial.id,f.selector);const dispatch=new ReproductionDispatchStore(f.pool,f.scope);await dispatch.backfill();
 const config={...f.scope,installationId:1,secret:'s'.repeat(32),evidenceToken:'r'.repeat(32),operatorToken:'o'.repeat(32)},servers:ReturnType<typeof createControlApi>[]=[];
 const start=async()=>{const control=await controlFactory(f.pool,config),server=apiFactory(config,{ready:async()=>{},recordDelivery:async()=>{throw Error();},evidence:async()=>undefined},undefined,control);server.listen(0,'127.0.0.1');await once(server,'listening');servers.push(server);return `http://127.0.0.1:${(server.address() as {port:number}).port}`;};
 const origin=await start(),path=`/v1/finding-reproductions/${f.f.plan.id}`,query=`?reviewId=${f.request.id}`;
 const call=(suffix=query,token=config.evidenceToken,init:RequestInit={},host=origin)=>fetch(host+path+suffix,{...init,headers:{authorization:`Bearer ${token}`,...init.headers}});
 return {...f,config,origin,path,query,call,start,dispatch,authority,identity,reads:new ReproductionReads(f.pool,f.scope),dispose:async()=>{for(const s of servers){s.closeAllConnections();await new Promise<void>(resolve=>s.close(()=>resolve()));}await f.close();}};
 }catch(e){await f.close();throw e;}}
type Fixture=Awaited<ReturnType<typeof fixture>>;
async function bind(f:Fixture){const claim=await f.dispatch.claim();assert.ok(claim);return f.dispatch.bind(claim,{taskQueue:'http-controller',evalTaskQueue:'http-eval',config:f.identity});}
async function neverStaged(f:Fixture){await f.dispatch.requestCancellation(f.selector.operationId,'user');await f.pool.query('INSERT INTO agentci_reproduction_cancellations(organization_id,repository,id) VALUES($1,$2,$3)',[f.scope.organizationId,f.scope.repository,f.f.plan.id]);const proofs=new ReproductionNonExecutionStore(f.pool,f.scope),proof=await proofs.cancelled(f.f.plan.id),history=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:async()=>{throw Error();},nonExecution:(id,subject)=>proofs.read(id,subject)});const h=await history.unavailable(f.f.initial.id,f.f.initial.subject,{type:'unavailable',proofId:proof.id},2,proof.id);const store=new ReproductionDispatchStore(f.pool,f.scope,async()=>({kind:'never-staged',history:h,proof})),claim=await store.claim('recovery');assert.ok(claim);await store.settle(claim);return {proof,h};}
async function execution(f:Fixture,supersede=false){const evals=new EvalStore(f.pool,f.scope.organizationId,f.scope.repository),staging=new ReproductionEvalStore(f.pool,f.scope,f.registry);let reproduction:FindingReproductionStore;const history=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:(id,subject)=>reproduction.readReceipt(id,subject)});reproduction=new FindingReproductionStore(f.pool,f.scope,history,evals,{approvedPlan:async()=>f.f.plan},staging);const staged=await reproduction.stage(f.f.plan.id,f.f.base,f.f.head);await evals.cancel(staged.jobId);await reproduction.finalize(f.f.plan.id);const receipt=await reproduction.readReceipt(f.f.plan.id,f.f.finding.subject);let h=(await history.get(f.f.finding.id,f.f.finding.subject)).at(-1)!;
 if(supersede){const operator={findingId:f.f.finding.id,subjectDigest:digest(canonical(f.f.finding.subject)),assertionDigest:null,evidenceDigest:digest('authorized operator evidence'),actor:'operator' as const,outcome:'resolved' as const,reason:'Operator resolution fixture'};const store=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:async()=>operator});h=await store.transition(f.f.finding.id,f.f.finding.subject,{type:'resolve',receiptId:randomUUID()},3,randomUUID());}
 const dispatch=new ReproductionDispatchStore(f.pool,f.scope,async()=>supersede?{kind:'superseded',history:h,receipt,proof:null}:{kind:'receipt-retained',history:h,receipt}),claim=await dispatch.claim();assert.ok(claim);await dispatch.settle(claim);return {receipt,h};}
test('real HTTP preserves queued/bound/dispatched meanings, identity, auth and bounded errors',async()=>{const f=await fixture();try{
 assert.equal((await f.call(f.query,'wrong')).status,401);assert.equal((await f.call('/cancellation',f.config.evidenceToken,{method:'POST'})).status,403);
 for(const q of ['',f.query+'&reviewId='+f.request.id,f.query+'&extra=1','?reviewId=invalid'])assert.equal((await f.call(q)).status,400);
 assert.equal((await f.call('?reviewId='+randomUUID())).status,404);
 assert.equal((await f.call(f.query,f.config.evidenceToken,{method:'POST'})).status,405);
 const queued=await f.call();assert.equal(queued.status,200);assert.equal(queued.headers.get('cache-control'),'no-store');assert.equal(queued.headers.get('x-content-type-options'),'nosniff');assert.equal(queued.headers.get('retry-after'),'1');const value=await queued.json();assert.equal(value.dispatch.state,'queued');assert.equal(value.receipt,null);assert.equal(value.operationId,f.selector.operationId);assert.equal(value.finding.digest,digest(canonical(f.f.plan.finding)));assert.deepEqual(validateFindingReproductionStatus(value,{id:f.f.plan.id,reviewId:f.request.id,subject:f.f.initial.subject}),value);assert.ok(!JSON.stringify(value).includes('repro.mjs'));
 const c=await bind(f);assert.equal((await (await f.call()).json()).dispatch.state,'bound');await f.dispatch.acknowledge(c,randomUUID());assert.equal((await (await f.call()).json()).dispatch.state,'dispatched');
 for(const init of [{body:'x'},{headers:{'content-encoding':'gzip'}},{body:'x'.repeat(4097)}])assert.ok([400,413,415].includes((await f.call('/cancellation',f.config.operatorToken,{method:'POST',...init})).status));
 assert.equal((await f.call('/cancellation?extra=1',f.config.operatorToken,{method:'POST'})).status,400);
 }finally{await f.dispose();}});
test('durable cancellation survives control restart and revoked approval without fabricating receipt',async()=>{const f=await fixture();try{
 const cfg=await f.authority.read(f.identity);await f.authority.apply({...cfg,revision:2,approvals:cfg.approvals.map(a=>({...a,enabled:false}))},f.identity);
 const cancel=await f.call('/cancellation',f.config.operatorToken,{method:'POST'});assert.equal(cancel.status,202);assert.deepEqual(await cancel.json(),{schemaVersion:'v1alpha1',id:f.f.plan.id,cancelRequested:true});
 const restarted=await f.start();assert.equal((await f.call('/cancellation',f.config.operatorToken,{method:'POST'},restarted)).status,202);const v=await (await f.call(f.query,f.config.evidenceToken,{},restarted)).json();assert.equal(v.dispatch.cancelRequested,true);assert.equal(v.dispatch.cancellationCause,'user');assert.equal(v.receipt,null);assert.equal(v.settlement,null);assert.ok(await f.dispatch.claim('recovery'));
 assert.equal((await fetch(restarted+'/v1/finding-reproductions/'+randomUUID()+'/cancellation',{method:'POST',headers:{authorization:`Bearer ${f.config.operatorToken}`}})).status,404);
 }finally{await f.dispose();}});
test('never-staged settlement exposes authentic unverified proof and late cancellation preserves it',async()=>{const f=await fixture();try{const evidence=await neverStaged(f),r=await f.call();assert.equal(r.status,200);const v=await r.json();assert.equal(v.dispatch.state,'settled');assert.equal(v.receipt,null);assert.equal(v.nonExecution.value.verified,false);assert.deepEqual(v.nonExecution.value,evidence.proof);assert.equal(v.settlement.historyDigest,evidence.h.digest);assert.equal(r.headers.get('retry-after'),null);assert.equal((await f.call('/cancellation',f.config.operatorToken,{method:'POST'})).status,202);assert.deepEqual(await (await f.call()).json(),v);}finally{await f.dispose();}});
test('real retained error receipt and supersession keep execution separate from cleanup and cancellation',async()=>{for(const supersede of [false,true]){const f=await fixture();try{const e=await execution(f,supersede),r=await f.call();assert.equal(r.status,200);const v=await r.json();assert.equal(v.receipt.value.outcome,'error');assert.deepEqual(v.receipt.value,e.receipt);assert.equal(v.settlement.kind,supersede?'superseded':'receipt-retained');assert.equal(v.settlement.retainedReceiptDigest,digest(canonical(e.receipt)));assert.equal((await f.call('/cancellation',f.config.operatorToken,{method:'POST'})).status,202);const late=await (await f.call()).json();assert.deepEqual(late.receipt,v.receipt);assert.deepEqual(late.settlement,v.settlement);assert.equal(late.dispatch.cancelRequested,true);}finally{await f.dispose();}}});
test('scope and rehashed settlement substitution fail closed with redacted error and preserved cancellation',async()=>{const f=await fixture();try{await neverStaged(f);for(const scope of [{...f.scope,organizationId:randomUUID()},{...f.scope,repository:'other/repo'}]){const reads=new ReproductionReads(f.pool,scope);assert.equal(await reads.status(f.f.plan.id,f.request.id),undefined);assert.equal(await reads.cancel(f.f.plan.id),undefined);}
 await f.pool.query('ALTER TABLE agentci_reproduction_dispatch_state DISABLE TRIGGER reproduction_dispatch_settlement_guard');await f.pool.query("UPDATE agentci_reproduction_dispatch_state SET settlement=jsonb_set(settlement,'{historyDigest}',to_jsonb($1::text))",[digest('private substituted history')]);await f.pool.query('ALTER TABLE agentci_reproduction_dispatch_state ENABLE TRIGGER reproduction_dispatch_settlement_guard');
 const r=await f.call();assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:{code:'service-unavailable'}});assert.equal((await f.call('/cancellation',f.config.operatorToken,{method:'POST'})).status,503);
 }finally{await f.dispose();}});
test('concurrent proof/history/settlement commitment cannot stitch contradictory snapshots',async()=>{const f=await fixture();let fired=false;try{
 const pool={connect:async()=>{const c=await f.pool.connect(),query=c.query.bind(c);const proxy={query:async(text:string,values?:unknown[])=>{if(!fired&&text.startsWith('SELECT unit_id,digest,receipt')){fired=true;await neverStaged(f);}return query(text,values);},release:(broken?:boolean)=>c.release(broken)} as PoolClient;return proxy;}} as Pool;
 const before=await new ReproductionReads(pool,f.scope).status(f.f.plan.id,f.request.id);assert.ok(fired);assert.ok(before);assert.equal(before.dispatch.state,'queued');assert.equal(before.dispatch.cancelRequested,false);assert.equal(before.nonExecution,null);assert.equal(before.settlement,null);assert.ok(statusShape(before),JSON.stringify(statusShape.errors));
 const after=await f.reads.status(f.f.plan.id,f.request.id);assert.equal(after!.dispatch.state,'settled');assert.equal(after!.nonExecution!.value.verified,false);assert.ok(statusShape(after),JSON.stringify(statusShape.errors));
 }finally{await f.dispose();}});
test('rehashing a retained receipt cannot substitute a verdict inconsistent with its evaluator result',async()=>{const f=await fixture();try{await execution(f);await f.pool.query('ALTER TABLE agentci_reproduction_receipts DISABLE TRIGGER ALL');
 const row=(await f.pool.query('SELECT receipt FROM agentci_reproduction_receipts')).rows[0],receipt={...row.receipt,outcome:'reproduced'};await f.pool.query('UPDATE agentci_reproduction_receipts SET receipt=$1,digest=$2',[receipt,digest(canonical(receipt))]);await f.pool.query('ALTER TABLE agentci_reproduction_receipts ENABLE TRIGGER ALL');
 const r=await f.call();assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:{code:'service-unavailable'}});
 }finally{await f.dispose();}});
