import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp,rm,realpath} from 'node:fs/promises';import {createHash,randomUUID} from 'node:crypto';import {once} from 'node:events';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {Octokit} from '@octokit/rest';
import {reproductionStagingFixture} from '../helpers/reproduction-staging-fixture.ts';import {Store} from '../../packages/storage/postgres.ts';import {ReproductionAuthorityStore} from '../../packages/storage/reproduction-authority.ts';import {canonical,digest} from '../../packages/review/engine.ts';import {parseReproductionCatalog} from '../../packages/runtime/reproduction-catalog.ts';
if(!process.env.AGENTCI_TEST_DATABASE_URL)throw Error('Reproduction admission requires PostgreSQL; never silently skip');
const root=process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT??new URL('../../',import.meta.url).pathname,probe=resolve(process.env.AGENTCI_TEST_CLIENT_PACKAGE_ROOT?resolve(root,'../..'):root,`reservation-client-${randomUUID()}.mjs`);
await writeFile(probe,"export {ModelReviewClient,AgentCIError} from 'agentci/client';export const resolved=import.meta.resolve('agentci/client');\n");let publicClient:any;try{publicClient=await import(pathToFileURL(probe).href);}finally{await rm(probe);}assert.equal(publicClient.resolved,pathToFileURL(await realpath(resolve(root,'dist/packages/client/index.js'))).href);
const {ModelReviewClient,AgentCIError}=publicClient,{createModelReviewControl}=await import(pathToFileURL(resolve(root,'dist/apps/control/model-reviews.js')).href),{createControlApi}=await import(pathToFileURL(resolve(root,'dist/apps/control/server.js')).href);
async function fixture(expired=false,loseReply=false){const f=await reproductionStagingFixture();try{
 await new Store(f.pool,f.scope.organizationId,f.scope.repository).ready();for(const n of ['015_m3_reproduction_eval_source','016_m3_reproduction_authority','017_m3_reproduction_dispatch_state','018_m3_reproduction_dispatch_settlement','019_m3_reproduction_dispatch_initialization'])await f.pool.query(await readFile(new URL(`../../deploy/migrations/${n}.sql`,import.meta.url),'utf8'));
 const config={...f.scope,installationId:123,cursorKey:'independent-cursor-'.repeat(3),evidenceToken:'read-token-'.repeat(4),operatorToken:'operator-token-'.repeat(4),secret:'hook-test-'.repeat(4)};
 const document={schemaVersion:'v1alpha1' as const,...f.scope,plans:[{digest:digest(canonical(f.f.plan)),plan:f.f.plan}]},operatorConfig={schemaVersion:'v1alpha1' as const,...f.scope,revision:1,approvals:[{planId:f.f.plan.id,planDigest:digest(canonical(f.f.plan)),findingId:f.f.initial.id,findingVersion:1,findingDigest:digest(canonical(f.f.initial)),enabled:true,expiresAt:expired?'2000-01-01T00:00:00.000Z':'2100-01-01T00:00:00.000Z'}]};
 const authority=new ReproductionAuthorityStore(f.pool,f.scope,{finding:async()=>f.f.initial,plan:async()=>f.f.plan,snapshot:async(_s,side)=>f.f[side]},async()=>true),expected=await authority.apply(operatorConfig,null),runtime={catalog:parseReproductionCatalog(document,f.scope,digest(canonical(document))),expected,evalTaskQueue:'agentci-eval-v1'};
 let mode='live',pulls=0,calls=0;const github=new Octokit({request:{fetch:async(input:RequestInfo|URL,init?:RequestInit)=>{calls++;const path=new URL(String(input)).pathname,blobs=new Map<string,string>();
  for(const side of ['base','head'] as const){const snapshot=f.f[side],treeSha=(side==='base'?'c':'d').repeat(40),tree=Object.entries(snapshot.files).map(([name,text])=>{const bytes=Buffer.from(text),sha=createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex');blobs.set(sha,text);return {path:name,mode:'100644',type:'blob',sha,size:bytes.length};});if(path.endsWith(`/git/commits/${snapshot.sha}`))return Response.json({sha:snapshot.sha,tree:{sha:treeSha}});if(path.endsWith(`/git/trees/${treeSha}`))return Response.json({sha:treeSha,truncated:false,tree});}
  const sha=path.split('/').at(-1)!;if(path.includes('/git/blobs/')&&blobs.has(sha))return Response.json({sha,encoding:'base64',content:Buffer.from(blobs.get(sha)!).toString('base64')});
  if(path.endsWith('/installation')){assert.ok(init?.signal);return Response.json({id:mode==='installation'?456:123,suspended_at:null});}
  if(path.includes('/pulls/')){assert.ok(init?.signal);pulls++;return Response.json({number:f.f.finding.subject.pullRequest,state:'open',base:{sha:f.f.finding.subject.baseSha,repo:{full_name:f.scope.repository}},head:{sha:mode==='stale'||mode==='late-stale'&&pulls%2===0?'f'.repeat(40):f.f.finding.subject.headSha}});}throw Error('Unexpected request');
 }}}),control=await createModelReviewControl(f.pool,config,null,github,runtime),server=createControlApi(config,{ready:async()=>{},recordDelivery:async()=>{throw Error();},evidence:async()=>undefined},undefined,control);const bodies:string[]=[];server.on('request',(req:any,res:any)=>{if(req.method==='POST'&&req.url?.endsWith('/reproductions')){const chunks:Buffer[]=[];req.on('data',(c:Buffer)=>chunks.push(c));req.once('end',()=>bodies.push(Buffer.concat(chunks).toString()));if(loseReply){const end=res.end.bind(res);res.end=(...args:any[])=>{if(loseReply&&res.statusCode===202){loseReply=false;res.destroy();return res;}return end(...args);};}}});server.listen(0,'127.0.0.1');await once(server,'listening');const url=`http://127.0.0.1:${server.address().port}`,body={schemaVersion:'v1alpha1',reviewId:f.request.id,...f.selector},client=new ModelReviewClient({url,readToken:config.evidenceToken,operatorToken:config.operatorToken,maxAttempts:1});
 return {...f,config,authority,operatorConfig,url,body,client,bodies,calls:()=>calls,mode:(v:string)=>{mode=v;pulls=0;},closeAll:async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await f.close();}};
}catch(error){await f.close();throw error;}}
test('compiled reservation transport rejects unauthorized input and rolls back fresh or post-write permission denial',async()=>{const f=await fixture();try{
 const before=await f.counts(),path=`${f.url}/v1/findings/${encodeURIComponent(f.f.initial.id)}/reproductions`,post=(body:any,token=f.config.operatorToken)=>fetch(path,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)});
 assert.equal((await post(f.body,f.config.evidenceToken)).status,403);assert.equal(f.calls(),0);
 assert.equal((await post(f.body,'wrong-token')).status,401);
 assert.equal((await fetch(path,{method:'GET',headers:{authorization:`Bearer ${f.config.operatorToken}`}})).status,405);
 assert.equal((await fetch(path+'?reviewId='+f.request.id,{method:'POST',headers:{authorization:`Bearer ${f.config.operatorToken}`,'content-type':'application/json'},body:JSON.stringify(f.body)})).status,400);
 assert.equal((await fetch(path,{method:'POST',headers:{authorization:`Bearer ${f.config.operatorToken}`,'content-type':'text/plain'},body:JSON.stringify(f.body)})).status,415);
 assert.equal((await fetch(path,{method:'POST',headers:{authorization:`Bearer ${f.config.operatorToken}`,'content-type':'application/json'},body:' '.repeat(4097)})).status,413);assert.equal(f.calls(),0);

 for(const body of [{...f.body,command:['private-command']},{...f.body,expectedVersion:0}])assert.equal((await post(body)).status,400);assert.equal(f.calls(),0);
 assert.equal((await post({...f.body,subject:{...f.body.subject,repository:'other/repo'}})).status,404);
 for(const mode of ['installation','stale','late-stale']){f.mode(mode);const r=await post(f.body);assert.equal(r.status,403);assert.deepEqual(await r.json(),{error:{code:'reproduction-denied'}});assert.deepEqual(await f.counts(),before);assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_dispatch_state')).rows[0].count,'0');}
}finally{await f.closeAll();}});
test('public client concurrent retries reserve exactly once; installed CLI repeats original intent, reads/cancels immediately, and preserves conflict/expiry boundaries',async()=>{const f=await fixture(),dir=await mkdtemp(join(tmpdir(),'reservation-cli-'));try{
 const fail=(code:string)=>(e:any)=>e instanceof AgentCIError&&e.code===code;
 await assert.rejects(new ModelReviewClient({url:f.url,readToken:f.config.evidenceToken}).reserveReproduction(f.request,f.f.initial.id,f.body),fail('operator-token-required'));assert.equal(f.calls(),0);
 const [a,b]=await Promise.all([f.client.reserveReproduction(f.request,f.f.initial.id,f.body),f.client.reserveReproduction(f.request,f.f.initial.id,f.body)]);assert.deepEqual(a,b);assert.deepEqual(await f.counts(),[2,1,1,1]);assert.equal((await f.client.reproductionStatus(f.request,a)).dispatch.state,'queued');
 await assert.rejects(f.client.reserveReproduction(f.request,f.f.initial.id,{...f.body,expectedVersion:2}),fail('idempotency-conflict'));await assert.rejects(f.client.reserveReproduction(f.request,f.f.initial.id,{...f.body,operationId:randomUUID()}),fail('version-conflict'));
 const request=join(dir,'request.json'),reservation=join(dir,'reservation.json');await writeFile(request,JSON.stringify(f.request));await writeFile(reservation,JSON.stringify(f.body));const run=promisify(execFile),args=[resolve(root,'dist/cmd/agentci/main.js'),'finding','reserve-reproduction','--request',request,'--id',f.f.initial.id,'--reservation',reservation],env={...process.env,AGENTCI_API_URL:f.url,AGENTCI_EVIDENCE_TOKEN:f.config.evidenceToken,AGENTCI_OPERATOR_TOKEN:f.config.operatorToken};assert.deepEqual(JSON.parse((await run(process.execPath,args,{env})).stdout),a);
 const fifo=join(dir,'reservation.fifo');await run('mkfifo',[fifo]);await assert.rejects(run(process.execPath,args.map(v=>v===reservation?fifo:v),{env,timeout:2000}),(e:any)=>e.code===2&&!e.killed&&e.stdout===''&&JSON.parse(e.stderr).error.code==='invalid-reservation-file');
 await f.client.cancelReproduction(f.request,a);assert.equal((await f.client.reproductionStatus(f.request,a)).dispatch.cancelRequested,true);
 await f.authority.apply({...f.operatorConfig,revision:2,approvals:f.operatorConfig.approvals.map(r=>({...r,enabled:false}))},f.authority?{revision:1,digest:digest(canonical(f.operatorConfig))}:null);await assert.rejects(f.client.reserveReproduction(f.request,f.f.initial.id,f.body),fail('approval-conflict'));assert.deepEqual(await f.counts(),[2,1,1,1]);
 for(const t of ['agentci_eval_jobs','agentci_eval_units','agentci_reproduction_dispatch_attempts'])assert.equal((await f.pool.query(`SELECT count(*) FROM ${t}`)).rows[0].count,'0');
}finally{await rm(dir,{recursive:true,force:true});await f.closeAll();}});

test('expired applied approval cannot reserve intent even with an authenticated live repository and valid selector',async()=>{const f=await fixture(true);try{const before=await f.counts();await assert.rejects(f.client.reserveReproduction(f.request,f.f.initial.id,f.body),(e:any)=>e instanceof AgentCIError&&e.code==='approval-conflict');assert.deepEqual(await f.counts(),before);assert.equal((await f.pool.query('SELECT count(*) FROM agentci_reproduction_dispatch_state')).rows[0].count,'0');}finally{await f.closeAll();}});

test('ambiguous reservation response loss retries byte-identical selector and retains exactly one complete operation',async()=>{const f=await fixture(false,true);try{const client=new ModelReviewClient({url:f.url,readToken:f.config.evidenceToken,operatorToken:f.config.operatorToken,maxAttempts:2});const accepted=await client.reserveReproduction(f.request,f.f.initial.id,f.body);assert.equal(f.bodies.length,2);assert.equal(f.bodies[0],f.bodies[1]);assert.deepEqual(JSON.parse(f.bodies[0]!),f.body);assert.deepEqual(await f.counts(),[2,1,1,1]);assert.equal((await client.reproductionStatus(f.request,accepted)).dispatch.state,'queued');}finally{await f.closeAll();}});
