import {readFileSync} from 'node:fs';import {evalOpenApiSchema} from '../evals/openapi.ts';
const object=(properties:Record<string,unknown>)=>({type:'object',additionalProperties:false,properties,required:Object.keys(properties)}),ref=(name:string)=>({$ref:`#/components/schemas/${name}`}),hash={type:'string',pattern:'^sha256:[a-f0-9]{64}$'},uuid={type:'string',pattern:'^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$'},count={type:'integer',minimum:0,maximum:640000};
function reviewerSchema(){const convert=(v:any):any=>Array.isArray(v)?v.map(convert):v&&typeof v==='object'?v.type==='null'?{nullable:true,enum:[null]}:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,convert(x)])):v;return convert(evalOpenApiSchema(JSON.parse(readFileSync(new URL('./json/reviewer-result.schema.json',import.meta.url),'utf8'))));}
const header=object({schemaVersion:{type:'string',enum:['v1alpha1']},review:ref('ModelReviewStatus'),configuredRoles:{type:'array',minItems:1,maxItems:7,items:object({requestId:uuid,role:{type:'string'}})},retainedRoles:{type:'array',maxItems:7,items:object({requestId:uuid,digest:hash})},missingRoleIds:{type:'array',maxItems:7,items:uuid},findings:{type:'array',maxItems:64,items:object({id:hash,throughVersion:{type:'integer',minimum:1,maximum:10000},lastDigest:hash})},reviewerCount:{type:'integer',minimum:0,maximum:7},eventCount:count,snapshotDigest:hash});
const frame=(type:string,data:unknown)=>object({type:{type:'string',enum:[type]},data,sequence:{type:'integer',minimum:0,maximum:640008},previousDigest:hash,digest:hash});
export const modelReviewExportOpenApiSchemas={
 RetainedReviewerResult:reviewerSchema(),ModelReviewExportHeader:header,
 ModelReviewExportFrame:{oneOf:[frame('header',ref('ModelReviewExportHeader')),frame('reviewer',object({result:ref('RetainedReviewerResult'),digest:hash})),frame('finding',ref('FindingHistoryRecord')),frame('end',object({snapshotDigest:hash,reviewerCount:{type:'integer',minimum:0,maximum:7},eventCount:count,lastContentDigest:hash}))]},
};
