import {Pool} from 'pg';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';import {once} from 'node:events';
import {canonical,digest} from '../../packages/review/engine.ts';import {buildReviewContext} from '../../packages/reviewers/context.ts';import {findingsFromReviewer,deduplicateFindings} from '../../packages/findings/model.ts';import {FindingHistoryStore} from '../../packages/storage/finding-history.ts';import {ReviewAdmissionStore} from '../../packages/storage/review-admissions.ts';import {nameUuid} from '../../packages/evals/request-id.ts';import {createModelReviewControl} from '../../apps/control/model-reviews.ts';import {createControlApi} from '../../apps/control/server.ts';import type {ReviewAdmissionRequest} from '../../packages/reviewers/admission.ts';
/** Real scoped storage and HTTP, synthetic retained evidence; no provider calls. */
export async function findingReadFixture(){
 const url=process.env.AGENTCI_TEST_DATABASE_URL;if(!url)throw Error('Finding API requires PostgreSQL; never silently skip');
 const schema=`findingread_${randomUUID().replaceAll('-','')}`,admin=new Pool({connectionString:url});await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString:url,options:`-c search_path=${schema}`});
 for(const name of ['006_m3_finding_history','008_m3_review_admissions','009_m3_review_dispatch','011_m3_review_summaries','012_m3_review_recovery'])await pool.query(await readFile(new URL(`../../deploy/migrations/${name}.sql`,import.meta.url),'utf8'));
 const result=JSON.parse(await readFile(new URL('../../specs/api/fixtures/reviewer-result.json',import.meta.url),'utf8'));result.subject.organizationId=randomUUID();result.requestId=randomUUID();
 const scope={organizationId:result.subject.organizationId,repository:result.subject.repository},request:ReviewAdmissionRequest={schemaVersion:'v1alpha1',id:randomUUID(),subject:result.subject,profile:{id:'fixture',revision:digest('fixture-profile')},mode:'synthetic'};
 const admissions=new ReviewAdmissionStore(pool,scope,{approve:async r=>({requestDigest:digest(canonical(r)),policyDigest:digest('policy'),profileRevision:r.profile.revision,mode:r.mode})});await admissions.admit(request);
 const docs=[{kind:'source',side:'head',path:'app.ts',content:'fixture',digest:digest('fixture')}];result.contextDigest=buildReviewContext(result.subject,docs).digest;
 result.response.structuredOutput={findings:[{category:'security',severity:'high',claim:'Missing authorization',evidence:[{side:'head',path:'app.ts',digest:docs[0]!.digest,startLine:1,endLine:1}]}]};result.proposal.output=structuredClone(result.response.structuredOutput);result.responseDigest=digest(canonical(result.response));
 const finding=deduplicateFindings(findingsFromReviewer(result,result.subject,docs),result.subject)[0]!;
 const history=new FindingHistoryStore(pool,scope,{reviewer:async()=>({result,documents:docs}),receipt:async()=>{throw Error('fixture-no-receipt');}});
 const initial=await history.ingest(finding,finding.subject,nameUuid(request.id,`agentci:review-finding:v1:${finding.id}`));
 const config={...scope,installationId:1,secret:'s'.repeat(32),evidenceToken:'r'.repeat(32),operatorToken:'o'.repeat(32),cursorKey:'c'.repeat(32)};
 const control=await createModelReviewControl(pool,config),server=createControlApi(config,{ready:async()=>{},recordDelivery:async()=>{throw Error();},evidence:async()=>undefined},undefined,control);server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const get=(path:string,token=config.evidenceToken)=>fetch(origin+path,{headers:{authorization:`Bearer ${token}`}});
 const retainSummary=async()=>{const summary={schemaVersion:'v1alpha1',admissionId:request.id,admissionDigest:digest(canonical(request)),profileRevision:request.profile.revision,contextDigest:result.contextDigest,mode:'synthetic',coverage:{selectedFiles:1,configuredRoles:1,completedRoles:1,wholeRepository:false},roles:[{requestId:result.requestId,role:'security',digest:digest(canonical(result)),status:'completed'}],findings:[{id:finding.id,digest:initial.digest}]};await pool.query('INSERT INTO agentci_review_execution_summaries(organization_id,repository,id,summary,digest) VALUES($1,$2,$3,$4,$5)',[scope.organizationId,scope.repository,request.id,summary,digest(canonical(summary))]);return summary;};
 return {pool,scope,config,request,finding,initial,history,admissions,origin,get,retainSummary,close:async()=>{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}};
}
