import {readFileSync} from 'node:fs';import {canonical,digest} from '../../packages/review/engine.ts';import {nameUuid} from '../../packages/evals/request-id.ts';import {findingsFromRetainedReviewer,deduplicateFindings} from '../../packages/findings/model.ts';import {modelReviewExportFrame,type ModelReviewExportHeader,type ModelReviewExportFrame} from '../../packages/reviewers/export.ts';import type {ReviewAdmissionRequest} from '../../packages/reviewers/admission.ts';import type {FindingHistoryRecord} from '../../packages/findings/history.ts';
export function modelReviewExportFixture(){
 const result=JSON.parse(readFileSync(new URL('../../specs/api/fixtures/reviewer-result.json',import.meta.url),'utf8'));
 const request:ReviewAdmissionRequest={schemaVersion:'v1alpha1',id:'11111111-1111-4111-8111-111111111111',subject:result.subject,profile:{id:'fixture-export',revision:digest('fixture-export-profile')},mode:'synthetic'};
 result.requestId=nameUuid(request.id,`agentci:reviewer:v1:${request.profile.revision}:security`);result.role='security';
 result.response.structuredOutput={findings:[{category:'security',severity:'high',claim:'Missing authorization',evidence:[{side:'head',path:'app.ts',digest:digest('fixture'),startLine:1,endLine:1}]}]};result.proposal.output=structuredClone(result.response.structuredOutput);result.responseDigest=digest(canonical(result.response));
 const finding=deduplicateFindings(findingsFromRetainedReviewer(result,request.subject),request.subject)[0]!;
 const event={schemaVersion:'v1alpha1' as const,operationId:nameUuid(request.id,`agentci:review-finding:v1:${finding.id}`),inputDigest:digest(canonical({type:'create',finding})),previousDigest:null,action:{type:'create' as const},receipt:null,finding};const record:FindingHistoryRecord={event,digest:digest(canonical(event))};
 const configuredRoles=['operational-reliability','security'].map(role=>({role,requestId:nameUuid(request.id,`agentci:reviewer:v1:${request.profile.revision}:${role}`)}));
 const snapshot={schemaVersion:'v1alpha1' as const,review:{schemaVersion:'v1alpha1' as const,admission:{request,digest:digest(canonical(request))},execution:{state:'cancelled' as const,cancelRequested:true,terminalDigest:digest('fixture-cancellation')},summary:null},configuredRoles,retainedRoles:[{requestId:result.requestId,digest:digest(canonical(result))}],missingRoleIds:[configuredRoles[0]!.requestId],findings:[{id:finding.id,throughVersion:1,lastDigest:record.digest}],reviewerCount:1,eventCount:1};
 const header:ModelReviewExportHeader={...snapshot,snapshotDigest:digest(canonical(snapshot))},frames:ModelReviewExportFrame[]=[];let prior='sha256:'+'0'.repeat(64);
 for(const item of [{type:'header' as const,data:header},{type:'reviewer' as const,data:{result,digest:digest(canonical(result))}},{type:'finding' as const,data:record}]){const frame=modelReviewExportFrame(item,frames.length,prior);frames.push(frame);prior=frame.digest;}
 frames.push(modelReviewExportFrame({type:'end',data:{snapshotDigest:header.snapshotDigest,reviewerCount:1,eventCount:1,lastContentDigest:prior}},frames.length,prior));
 return {request,result,finding,record,header,frames};
}
