import {Pool} from 'pg';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import {once} from 'node:events';
import {canonical,digest} from '../../packages/review/engine.ts';import {ReviewAdmissionStore} from '../../packages/storage/review-admissions.ts';import {ReviewerProfileStore} from '../../packages/storage/reviewer-profiles.ts';import {ReviewDispatchStore,type ReviewTerminalStatus} from '../../packages/storage/review-dispatch.ts';import {createAdmittedReviewExecution} from '../../apps/worker/reviewer-execution.ts';import {findingProposalSchema} from '../../packages/findings/model.ts';import type {ModelProvider} from '../../packages/providers/types.ts';import {createModelReviewControl} from '../../apps/control/model-reviews.ts';import {createControlApi} from '../../apps/control/server.ts';import {ModelReviewExports} from '../../packages/storage/model-review-export.ts';import type {ReviewAdmissionRequest} from '../../packages/reviewers/admission.ts';
export async function modelReviewExportStorage(findingCount=1){
 const url=process.env.AGENTCI_TEST_DATABASE_URL;if(!url)throw Error('Model review export requires PostgreSQL; never silently skip');const schema=`export_${randomUUID().replaceAll('-','')}`,admin=new Pool({connectionString:url});await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({connectionString:url,options:`-c search_path=${schema}`,max:2});
 for(const name of ['004_m3_model_budget','005_m3_reviewer_results','006_m3_finding_history','008_m3_review_admissions','009_m3_review_dispatch','010_m3_reviewer_profiles','011_m3_review_summaries','012_m3_review_recovery'])await pool.query(await readFile(new URL(`../../deploy/migrations/${name}.sql`,import.meta.url),'utf8'));
 const scope={organizationId:randomUUID(),repository:'fixture/export'},input=JSON.parse(await readFile(new URL('../../specs/api/fixtures/reviewer-profile.json',import.meta.url),'utf8'));input.budget.id=randomUUID();input.reviewers[0].responseSchema=findingProposalSchema;input.reviewers.push({...structuredClone(input.reviewers[0]),role:'architecture'});
 const profile=await new ReviewerProfileStore(pool,scope).put(input),admissions=new ReviewAdmissionStore(pool,scope,{approve:async r=>({requestDigest:digest(canonical(r)),policyDigest:digest('fixture-policy'),profileRevision:r.profile.revision,mode:r.mode})});
 const request:ReviewAdmissionRequest={schemaVersion:'v1alpha1',id:randomUUID(),subject:{...scope,pullRequest:1,baseSha:'a'.repeat(40),headSha:'b'.repeat(40)},profile:{id:profile.profile.id,revision:profile.revision},mode:'synthetic'};await admissions.admit(request);
 const content='const authorized = false;\n';let calls=0;
 const provider:ModelProvider={id:'fixture',upstreamIdentity:'fixture',capabilities:()=>({stream:false,tools:false,structuredOutput:true,developerInstructions:false,extensions:false}),estimateCost:()=>({upperBoundUsdMicros:10,pricingRevision:'fixture',maxInputTokens:20000,maxOutputTokens:256}),async invoke(r,context){calls++;return {schemaVersion:'v1alpha1',requestId:r.requestId,attemptId:context.attemptId,provider:r.provider,model:r.model,status:'completed',text:'Synthetic retained finding',structuredOutput:{findings:Array.from({length:findingCount},(_,index)=>({category:'security',severity:'high',claim:`Missing authorization ${index}`,evidence:[{side:'head',path:'src/main.ts',digest:digest(content),startLine:1,endLine:1}]}))},toolCalls:[],usage:{inputTokens:1,outputTokens:1,costUsdMicros:1,costKind:'reported',pricingRevision:null},providerRequestId:null};},async *stream(){throw Error('unused');}};
 const run=createAdmittedReviewExecution({pool,scope,admissions,registrations:[{provider,execution:'fixture'}],authorize:async()=>null,readSnapshot:async(_repository,sha)=>({sha,files:{'src/main.ts':content}})}),dispatch=new ReviewDispatchStore(pool,scope);
 const config={...scope,installationId:1,secret:'s'.repeat(32),evidenceToken:'r'.repeat(32),operatorToken:'o'.repeat(32)},control=await createModelReviewControl(pool,config),server=createControlApi(config,{ready:async()=>{},recordDelivery:async()=>'accepted',evidence:async()=>undefined},undefined,control);server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 let runId:string|undefined;
 const execute=async(failure?:'summary'|'second-role')=>{
  const claim=(await dispatch.claim())!;runId=randomUUID();await dispatch.acknowledge(claim,runId);
  if(failure){const table=failure==='summary'?'agentci_review_execution_summaries':'agentci_reviewer_results',condition=failure==='summary'?'true':"(SELECT count(*) FROM agentci_reviewer_results)>0";await pool.query(`CREATE FUNCTION fixture_export_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF ${condition} THEN RAISE EXCEPTION 'fixture interruption'; END IF; RETURN NEW; END $$; CREATE TRIGGER fixture_failure BEFORE INSERT ON ${table} FOR EACH ROW EXECUTE FUNCTION fixture_export_failure()`);}
  return run(request.id);
 };
 return {pool,scope,request,config,content,origin,control,dispatch,exports:new ModelReviewExports(pool,scope),execute,calls:()=>calls,finish:async(status:ReviewTerminalStatus,summaryDigest?:string)=>{if(!runId)throw Error('not dispatched');return dispatch.finish(request.id,runId,status,summaryDigest??digest(canonical({admissionDigest:digest(canonical(request)),runId,status})));},get:()=>fetch(`${origin}/v1/model-reviews/${request.id}/export`,{headers:{authorization:`Bearer ${config.evidenceToken}`}}),close:async()=>{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}};
}
