import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import {Pool} from 'pg';
import {reproductionStagingFixture} from './reproduction-staging-fixture.ts';import {Store} from '../../packages/storage/postgres.ts';
import {canonical,digest} from '../../packages/review/engine.ts';import {parseReproductionCatalog,reproductionCatalogReaders,loadAppliedReproductionRegistry} from '../../packages/runtime/reproduction-catalog.ts';
import {ReproductionAuthorityStore} from '../../packages/storage/reproduction-authority.ts';import {ReproductionDispatchStore} from '../../packages/storage/reproduction-dispatch.ts';import {ReproductionEvalStore} from '../../packages/storage/reproduction-evals.ts';import {ReproductionNonExecutionStore} from '../../packages/storage/reproduction-non-execution.ts';import {FindingHistoryStore} from '../../packages/storage/finding-history.ts';import {FindingReproductionStore} from '../../packages/storage/finding-reproduction.ts';import {EvalStore} from '../../packages/storage/evals.ts';import {createReproductionConsumerRuntime} from '../../apps/worker/reproduction-consumer-runtime.ts';
export async function reproductionConsumerFixture(script?:string){
 const image=process.env.AGENTCI_TEST_RUNNER_IMAGE;if(!image)throw Error('Consumer isolated acceptance requires immutable runner image');
 const f=await reproductionStagingFixture({image,...(script?{extraFiles:{'repro.mjs':script}}:{})});let restricted:Pool|undefined;const role=`consumer_eval_${randomUUID().replaceAll('-','')}`,password=randomUUID();let created=false;
 try{
  await new Store(f.pool,f.scope.organizationId,f.scope.repository).ready();for(const n of ['015_m3_reproduction_eval_source','016_m3_reproduction_authority','017_m3_reproduction_dispatch_state','018_m3_reproduction_dispatch_settlement'])await f.pool.query(await readFile(new URL(`../../deploy/migrations/${n}.sql`,import.meta.url),'utf8'));
  const definition={schemaVersion:'v1alpha1' as const,...f.scope,plans:[{digest:digest(canonical(f.f.plan)),plan:f.f.plan}]},catalog=parseReproductionCatalog(definition,f.scope,digest(canonical(definition)));
  const snapshots=async(_subject:unknown,side:'base'|'head')=>structuredClone(f.f[side]),readers=reproductionCatalogReaders(f.pool,f.scope,catalog,'fixture-cursor-'+randomUUID(),snapshots);
  let allowed=true;const authority=new ReproductionAuthorityStore(f.pool,f.scope,readers,async()=>allowed);
  const expected=await authority.apply({schemaVersion:'v1alpha1',...f.scope,revision:1,approvals:[{planId:f.f.plan.id,planDigest:digest(canonical(f.f.plan)),findingId:f.f.initial.id,findingVersion:1,findingDigest:digest(canonical(f.f.initial)),enabled:true,expiresAt:'2100-01-01T00:00:00.000Z'}]},null);
  const loaded=await loadAppliedReproductionRegistry(f.pool,f.scope,readers);await f.store.reserve(f.f.initial.id,f.selector);
  const evals=new EvalStore(f.pool,f.scope.organizationId,f.scope.repository),staging=new ReproductionEvalStore(f.pool,f.scope,loaded.registry),proofs=new ReproductionNonExecutionStore(f.pool,f.scope);
  const history=new FindingHistoryStore(f.pool,f.scope,{reviewer:async()=>({result:f.f.reviewer,documents:f.f.documents}),receipt:(id,subject)=>reproduction.readReceipt(id,subject),nonExecution:(id,subject)=>proofs.read(id,subject)});
  const reproduction=new FindingReproductionStore(f.pool,f.scope,history,evals,{approvedPlan:async id=>catalog.plan(id)!},staging);
  let runtime:ReturnType<typeof createReproductionConsumerRuntime>;const dispatch=new ReproductionDispatchStore(f.pool,f.scope,(...args)=>runtime.settlementReader(...args));
  const taskQueue=`consumer-${randomUUID()}`,evalTaskQueue=`consumer-eval-${randomUUID()}`;
  runtime=createReproductionConsumerRuntime({pool:f.pool,scope:f.scope,authority,staging,reproduction,history,proofs,evals,dispatch,snapshots,evalTaskQueue});await dispatch.ready();await dispatch.backfill();
  await f.pool.query(`CREATE ROLE ${role} LOGIN PASSWORD '${password}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS`);created=true;await f.pool.query(`GRANT USAGE ON SCHEMA ${f.schema} TO ${role}`);await f.pool.query(`GRANT SELECT ON agentci_scope,agentci_eval_jobs,agentci_eval_units,agentci_eval_trials TO ${role}`);await f.pool.query(`GRANT UPDATE(status,lease_token,lease_until,result,result_digest,completed_at) ON agentci_eval_units TO ${role}`);await f.pool.query(`GRANT INSERT ON agentci_eval_trials TO ${role}`);
  const url=new URL(process.env.AGENTCI_TEST_DATABASE_URL!);url.username=role;url.password=password;restricted=new Pool({connectionString:url.toString(),options:`-c search_path=${f.schema}`});const workerStore=new EvalStore(restricted,f.scope.organizationId,f.scope.repository);await workerStore.ready();
  return {...f,image,authority,expected,dispatch,runtime,staging,history,reproduction,evals,workerStore,taskQueue,evalTaskQueue,workerDatabaseUrl:url.toString(),setAllowed:(value:boolean)=>{allowed=value;},dispose:async()=>{await restricted!.end();await f.pool.query(`DROP OWNED BY ${role}`);await f.pool.query(`DROP ROLE ${role}`);await f.close();}};
 }catch(e){await restricted?.end();if(created){await f.pool.query(`DROP OWNED BY ${role}`);await f.pool.query(`DROP ROLE ${role}`);}await f.close();throw e;}
}
